package dqr.addons.twilightForest;

import java.util.ArrayList;
import java.util.List;

import net.minecraft.entity.EnumCreatureType;
import net.minecraft.world.biome.BiomeGenBase;
import net.minecraft.world.biome.BiomeGenBase.SpawnListEntry;
import twilightforest.TFFeature;
import twilightforest.biomes.TFBiomeBase;
import dqr.entity.mobEntity.DqmMobBase;
import dqr.entity.mobEntity.monsterBoss.DqmEntityDesupisaro1;
import dqr.entity.mobEntity.monsterBoss.DqmEntityEsterk;
import dqr.entity.mobEntity.monsterBoss.DqmEntityMasterdoragon;
import dqr.entity.mobEntity.monsterBoss.DqmEntityRyuuou;
import dqr.entity.mobEntity.monsterBoss.DqmEntityZoma;
import dqr.entity.mobEntity.monsterDay.DqmEntityAyasiikage;
import dqr.entity.mobEntity.monsterDay.DqmEntityBigCrow;
import dqr.entity.mobEntity.monsterDay.DqmEntityBigguhatto;
import dqr.entity.mobEntity.monsterDay.DqmEntityBubsura;
import dqr.entity.mobEntity.monsterDay.DqmEntityBurauni;
import dqr.entity.mobEntity.monsterDay.DqmEntityButisuraimu;
import dqr.entity.mobEntity.monsterDay.DqmEntityDokuroarai;
import dqr.entity.mobEntity.monsterDay.DqmEntityDoronuba;
import dqr.entity.mobEntity.monsterDay.DqmEntityDorozara;
import dqr.entity.mobEntity.monsterDay.DqmEntityDoruido;
import dqr.entity.mobEntity.monsterDay.DqmEntityDragosuraimu;
import dqr.entity.mobEntity.monsterDay.DqmEntityDucksbill;
import dqr.entity.mobEntity.monsterDay.DqmEntityEbiruapple;
import dqr.entity.mobEntity.monsterDay.DqmEntityFaratto;
import dqr.entity.mobEntity.monsterDay.DqmEntityGaikotu;
import dqr.entity.mobEntity.monsterDay.DqmEntityGizumoAZ;
import dqr.entity.mobEntity.monsterDay.DqmEntityGuntaigani;
import dqr.entity.mobEntity.monsterDay.DqmEntityHitokuikibako;
import dqr.entity.mobEntity.monsterDay.DqmEntityHitokuisaberu;
import dqr.entity.mobEntity.monsterDay.DqmEntityHoimisura;
import dqr.entity.mobEntity.monsterDay.DqmEntityIkkakuusagi;
import dqr.entity.mobEntity.monsterDay.DqmEntityItamogu;
import dqr.entity.mobEntity.monsterDay.DqmEntityKimera;
import dqr.entity.mobEntity.monsterDay.DqmEntityKirapan;
import dqr.entity.mobEntity.monsterDay.DqmEntityKirikabuobake;
import dqr.entity.mobEntity.monsterDay.DqmEntityMadohando;
import dqr.entity.mobEntity.monsterDay.DqmEntityMomon;
import dqr.entity.mobEntity.monsterDay.DqmEntityMomonja;
import dqr.entity.mobEntity.monsterDay.DqmEntityObakekinoko;
import dqr.entity.mobEntity.monsterDay.DqmEntityObakeumiusi;
import dqr.entity.mobEntity.monsterDay.DqmEntityOnikozou;
import dqr.entity.mobEntity.monsterDay.DqmEntityOokiduti;
import dqr.entity.mobEntity.monsterDay.DqmEntityOokutibasi;
import dqr.entity.mobEntity.monsterDay.DqmEntityOomedama;
import dqr.entity.mobEntity.monsterDay.DqmEntityOonamekuji;
import dqr.entity.mobEntity.monsterDay.DqmEntityPapetkozou;
import dqr.entity.mobEntity.monsterDay.DqmEntityPurizunyan;
import dqr.entity.mobEntity.monsterDay.DqmEntityRemonsuraimu;
import dqr.entity.mobEntity.monsterDay.DqmEntityRippusu;
import dqr.entity.mobEntity.monsterDay.DqmEntityRiripat;
import dqr.entity.mobEntity.monsterDay.DqmEntitySabotenboru;
import dqr.entity.mobEntity.monsterDay.DqmEntitySibirekurage;
import dqr.entity.mobEntity.monsterDay.DqmEntitySimasimacat;
import dqr.entity.mobEntity.monsterDay.DqmEntitySirudokozou;
import dqr.entity.mobEntity.monsterDay.DqmEntitySukippaa;
import dqr.entity.mobEntity.monsterDay.DqmEntitySunomon;
import dqr.entity.mobEntity.monsterDay.DqmEntitySupini;
import dqr.entity.mobEntity.monsterDay.DqmEntitySura;
import dqr.entity.mobEntity.monsterDay.DqmEntitySuraimubesu;
import dqr.entity.mobEntity.monsterDay.DqmEntitySuraimunaito;
import dqr.entity.mobEntity.monsterDay.DqmEntitySuraimutawa;
import dqr.entity.mobEntity.monsterDay.DqmEntitySuraimutumuri;
import dqr.entity.mobEntity.monsterDay.DqmEntityTogebouzu;
import dqr.entity.mobEntity.monsterDay.DqmEntityTukaima;
import dqr.entity.mobEntity.monsterDay.DqmEntityUzusioking;
import dqr.entity.mobEntity.monsterDay.DqmEntityWaraibukuro;
import dqr.entity.mobEntity.monsterDay.DqmEntityZinmentyou;
import dqr.entity.mobEntity.monsterDay.DqmEntityZukkinya;
import dqr.entity.mobEntity.monsterEnd.DqmEntityAkairai;
import dqr.entity.mobEntity.monsterEnd.DqmEntityBassaimasin;
import dqr.entity.mobEntity.monsterEnd.DqmEntityBatorurex;
import dqr.entity.mobEntity.monsterEnd.DqmEntityBiggumoai;
import dqr.entity.mobEntity.monsterEnd.DqmEntityBurizado;
import dqr.entity.mobEntity.monsterEnd.DqmEntityDakuhobitto;
import dqr.entity.mobEntity.monsterEnd.DqmEntityDakunaito;
import dqr.entity.mobEntity.monsterEnd.DqmEntityDarktororu;
import dqr.entity.mobEntity.monsterEnd.DqmEntityDasudragon;
import dqr.entity.mobEntity.monsterEnd.DqmEntityDenga;
import dqr.entity.mobEntity.monsterEnd.DqmEntityDesujakkaru;
import dqr.entity.mobEntity.monsterEnd.DqmEntityDesunyago;
import dqr.entity.mobEntity.monsterEnd.DqmEntityDesusutoka;
import dqr.entity.mobEntity.monsterEnd.DqmEntityDragondarknaito;
import dqr.entity.mobEntity.monsterEnd.DqmEntityGamegonrejendo;
import dqr.entity.mobEntity.monsterEnd.DqmEntityGigantesu;
import dqr.entity.mobEntity.monsterEnd.DqmEntityGodraida;
import dqr.entity.mobEntity.monsterEnd.DqmEntityGorudensuraimu;
import dqr.entity.mobEntity.monsterEnd.DqmEntityJigokunoyoroi;
import dqr.entity.mobEntity.monsterEnd.DqmEntityKagenokisi;
import dqr.entity.mobEntity.monsterEnd.DqmEntityManemane;
import dqr.entity.mobEntity.monsterEnd.DqmEntityPandorabox;
import dqr.entity.mobEntity.monsterEnd.DqmEntityRyuiso;
import dqr.entity.mobEntity.monsterEnd.DqmEntityShadopan2;
import dqr.entity.mobEntity.monsterEnd.DqmEntityTororubonba;
import dqr.entity.mobEntity.monsterHell.DqmEntityAnkokumajin;
import dqr.entity.mobEntity.monsterHell.DqmEntityAroinpu;
import dqr.entity.mobEntity.monsterHell.DqmEntityBaburuking;
import dqr.entity.mobEntity.monsterHell.DqmEntityBarakku;
import dqr.entity.mobEntity.monsterHell.DqmEntityBariidodog;
import dqr.entity.mobEntity.monsterHell.DqmEntityBehomasuraimu;
import dqr.entity.mobEntity.monsterHell.DqmEntityBiggufeisu;
import dqr.entity.mobEntity.monsterHell.DqmEntityBighanma;
import dqr.entity.mobEntity.monsterHell.DqmEntityBosutororu;
import dqr.entity.mobEntity.monsterHell.DqmEntityBoureikensi;
import dqr.entity.mobEntity.monsterHell.DqmEntityBuraddosodo;
import dqr.entity.mobEntity.monsterHell.DqmEntityBurakkubejita;
import dqr.entity.mobEntity.monsterHell.DqmEntityDarkdoriado;
import dqr.entity.mobEntity.monsterHell.DqmEntityDarkslime;
import dqr.entity.mobEntity.monsterHell.DqmEntityDeddopekka;
import dqr.entity.mobEntity.monsterHell.DqmEntityDgizumo;
import dqr.entity.mobEntity.monsterHell.DqmEntityDollmaster;
import dqr.entity.mobEntity.monsterHell.DqmEntityDoragonsoruja;
import dqr.entity.mobEntity.monsterHell.DqmEntityDqmdragon;
import dqr.entity.mobEntity.monsterHell.DqmEntityDragonnaito;
import dqr.entity.mobEntity.monsterHell.DqmEntityDragonraida;
import dqr.entity.mobEntity.monsterHell.DqmEntityEriminator;
import dqr.entity.mobEntity.monsterHell.DqmEntityFureimu;
import dqr.entity.mobEntity.monsterHell.DqmEntityGamegon;
import dqr.entity.mobEntity.monsterHell.DqmEntityGamegonload;
import dqr.entity.mobEntity.monsterHell.DqmEntityGanirasu;
import dqr.entity.mobEntity.monsterHell.DqmEntityGoldman;
import dqr.entity.mobEntity.monsterHell.DqmEntityGoremu;
import dqr.entity.mobEntity.monsterHell.DqmEntityGorudentotemu;
import dqr.entity.mobEntity.monsterHell.DqmEntityHotatewarabi;
import dqr.entity.mobEntity.monsterHell.DqmEntityJigokunohasami;
import dqr.entity.mobEntity.monsterHell.DqmEntityKedamon;
import dqr.entity.mobEntity.monsterHell.DqmEntityKemunkurusu;
import dqr.entity.mobEntity.monsterHell.DqmEntityKimendousi;
import dqr.entity.mobEntity.monsterHell.DqmEntityKiraama;
import dqr.entity.mobEntity.monsterHell.DqmEntityKirakurabu;
import dqr.entity.mobEntity.monsterHell.DqmEntityKiramasin;
import dqr.entity.mobEntity.monsterHell.DqmEntityKiramasin2;
import dqr.entity.mobEntity.monsterHell.DqmEntityKisudragon;
import dqr.entity.mobEntity.monsterHell.DqmEntityKuinsuraimu;
import dqr.entity.mobEntity.monsterHell.DqmEntityMagematango;
import dqr.entity.mobEntity.monsterHell.DqmEntityMagemomonja;
import dqr.entity.mobEntity.monsterHell.DqmEntityMagumaron;
import dqr.entity.mobEntity.monsterHell.DqmEntityMajikaruhatto;
import dqr.entity.mobEntity.monsterHell.DqmEntityMaounokage;
import dqr.entity.mobEntity.monsterHell.DqmEntityMaporena;
import dqr.entity.mobEntity.monsterHell.DqmEntityMegazarurokku;
import dqr.entity.mobEntity.monsterHell.DqmEntityMetaruhanta;
import dqr.entity.mobEntity.monsterHell.DqmEntityMimikku;
import dqr.entity.mobEntity.monsterHell.DqmEntityPapettoman;
import dqr.entity.mobEntity.monsterHell.DqmEntityPikusi;
import dqr.entity.mobEntity.monsterHell.DqmEntityPombom;
import dqr.entity.mobEntity.monsterHell.DqmEntityPuyon;
import dqr.entity.mobEntity.monsterHell.DqmEntityRedsaikuron;
import dqr.entity.mobEntity.monsterHell.DqmEntitySaikuropusu;
import dqr.entity.mobEntity.monsterHell.DqmEntityShadopan;
import dqr.entity.mobEntity.monsterHell.DqmEntitySirubadebiru;
import dqr.entity.mobEntity.monsterHell.DqmEntitySiryou;
import dqr.entity.mobEntity.monsterHell.DqmEntitySiryounokisi;
import dqr.entity.mobEntity.monsterHell.DqmEntitySodofantomu;
import dqr.entity.mobEntity.monsterHell.DqmEntityStarkimera;
import dqr.entity.mobEntity.monsterHell.DqmEntityStonman;
import dqr.entity.mobEntity.monsterHell.DqmEntitySuraimubehomazun;
import dqr.entity.mobEntity.monsterHell.DqmEntitySuraimuhaitawa;
import dqr.entity.mobEntity.monsterHell.DqmEntitySuraimumadyura;
import dqr.entity.mobEntity.monsterHell.DqmEntityTororuking;
import dqr.entity.mobEntity.monsterHell.DqmEntityTubokku;
import dqr.entity.mobEntity.monsterHell.DqmEntityUmibouzu;
import dqr.entity.mobEntity.monsterHell.DqmEntityWhitepan2;
import dqr.entity.mobEntity.monsterNight.DqmEntityAkumanosyo;
import dqr.entity.mobEntity.monsterNight.DqmEntityAkumanotubo;
import dqr.entity.mobEntity.monsterNight.DqmEntityAnimaruzonbi;
import dqr.entity.mobEntity.monsterNight.DqmEntityArumiraji;
import dqr.entity.mobEntity.monsterNight.DqmEntityAxedoragon;
import dqr.entity.mobEntity.monsterNight.DqmEntityBaburin;
import dqr.entity.mobEntity.monsterNight.DqmEntityBakudanbebi;
import dqr.entity.mobEntity.monsterNight.DqmEntityBakudaniwa;
import dqr.entity.mobEntity.monsterNight.DqmEntityBebisatan;
import dqr.entity.mobEntity.monsterNight.DqmEntityBehoimisuraimu;
import dqr.entity.mobEntity.monsterNight.DqmEntityBehoimusuraimu;
import dqr.entity.mobEntity.monsterNight.DqmEntityBerobero;
import dqr.entity.mobEntity.monsterNight.DqmEntityBeronyaago;
import dqr.entity.mobEntity.monsterNight.DqmEntityBesuking;
import dqr.entity.mobEntity.monsterNight.DqmEntityBuchunpa;
import dqr.entity.mobEntity.monsterNight.DqmEntityBuraddihando;
import dqr.entity.mobEntity.monsterNight.DqmEntityButtizukinya;
import dqr.entity.mobEntity.monsterNight.DqmEntityDansunidoru;
import dqr.entity.mobEntity.monsterNight.DqmEntityDesufuratta;
import dqr.entity.mobEntity.monsterNight.DqmEntityDokuyazukin;
import dqr.entity.mobEntity.monsterNight.DqmEntityDoraki;
import dqr.entity.mobEntity.monsterNight.DqmEntityDorakima;
import dqr.entity.mobEntity.monsterNight.DqmEntityDoroningyou;
import dqr.entity.mobEntity.monsterNight.DqmEntityEnzeruslime;
import dqr.entity.mobEntity.monsterNight.DqmEntityFgizumo;
import dqr.entity.mobEntity.monsterNight.DqmEntityGaikotukensi;
import dqr.entity.mobEntity.monsterNight.DqmEntityGappurin;
import dqr.entity.mobEntity.monsterNight.DqmEntityGenjutusi;
import dqr.entity.mobEntity.monsterNight.DqmEntityGhost;
import dqr.entity.mobEntity.monsterNight.DqmEntityGorotuki;
import dqr.entity.mobEntity.monsterNight.DqmEntityHerughost;
import dqr.entity.mobEntity.monsterNight.DqmEntityHgizumo;
import dqr.entity.mobEntity.monsterNight.DqmEntityHitokuiga;
import dqr.entity.mobEntity.monsterNight.DqmEntityHoroghost;
import dqr.entity.mobEntity.monsterNight.DqmEntityHyouganmajin;
import dqr.entity.mobEntity.monsterNight.DqmEntityJeriman;
import dqr.entity.mobEntity.monsterNight.DqmEntityKingsura;
import dqr.entity.mobEntity.monsterNight.DqmEntityKirapan2;
import dqr.entity.mobEntity.monsterNight.DqmEntityKirasuko;
import dqr.entity.mobEntity.monsterNight.DqmEntityMapetman;
import dqr.entity.mobEntity.monsterNight.DqmEntityMarinsuraimu;
import dqr.entity.mobEntity.monsterNight.DqmEntityMatango;
import dqr.entity.mobEntity.monsterNight.DqmEntityMeijidoraki;
import dqr.entity.mobEntity.monsterNight.DqmEntityMeijikimera;
import dqr.entity.mobEntity.monsterNight.DqmEntityMeragosuto;
import dqr.entity.mobEntity.monsterNight.DqmEntityMetaruhantaken;
import dqr.entity.mobEntity.monsterNight.DqmEntityMetaruraida;
import dqr.entity.mobEntity.monsterNight.DqmEntityMetoroghost;
import dqr.entity.mobEntity.monsterNight.DqmEntityMinidemon;
import dqr.entity.mobEntity.monsterNight.DqmEntityMokomokojuu;
import dqr.entity.mobEntity.monsterNight.DqmEntityMrippusu;
import dqr.entity.mobEntity.monsterNight.DqmEntityNightwalker;
import dqr.entity.mobEntity.monsterNight.DqmEntityObakekyandoru;
import dqr.entity.mobEntity.monsterNight.DqmEntityOdoruhouseki;
import dqr.entity.mobEntity.monsterNight.DqmEntityPinkmomon;
import dqr.entity.mobEntity.monsterNight.DqmEntityRaimusuraimu;
import dqr.entity.mobEntity.monsterNight.DqmEntitySamayoutamasii;
import dqr.entity.mobEntity.monsterNight.DqmEntitySamayouyoroi;
import dqr.entity.mobEntity.monsterNight.DqmEntitySibireageha;
import dqr.entity.mobEntity.monsterNight.DqmEntitySibiredanbira;
import dqr.entity.mobEntity.monsterNight.DqmEntitySkullgaroo;
import dqr.entity.mobEntity.monsterNight.DqmEntitySumairurokku;
import dqr.entity.mobEntity.monsterNight.DqmEntitySumoruguru;
import dqr.entity.mobEntity.monsterNight.DqmEntitySupekutetto;
import dqr.entity.mobEntity.monsterNight.DqmEntitySura2;
import dqr.entity.mobEntity.monsterNight.DqmEntitySuraimubogu;
import dqr.entity.mobEntity.monsterNight.DqmEntitySuraimuburesu;
import dqr.entity.mobEntity.monsterNight.DqmEntitySyado;
import dqr.entity.mobEntity.monsterNight.DqmEntityTahodoraki;
import dqr.entity.mobEntity.monsterNight.DqmEntityTomosibikozou;
import dqr.entity.mobEntity.monsterNight.DqmEntityTonburero;
import dqr.entity.mobEntity.monsterNight.DqmEntityTororu;
import dqr.entity.mobEntity.monsterNight.DqmEntityTutiwarasi;
import dqr.entity.mobEntity.monsterNight.DqmEntityUmiusi;
import dqr.entity.mobEntity.monsterNight.DqmEntityYouganmajin;
import dqr.entity.mobEntity.monsterSP.DqmEntityAtorasu;
import dqr.entity.mobEntity.monsterSP.DqmEntityBazuzu;
import dqr.entity.mobEntity.monsterSP.DqmEntityBlackchack;
import dqr.entity.mobEntity.monsterSP.DqmEntityBurasu;
import dqr.entity.mobEntity.monsterSP.DqmEntityDarkRamia;
import dqr.entity.mobEntity.monsterSP.DqmEntityFureizado;
import dqr.entity.mobEntity.monsterSP.DqmEntityGodonheddo;
import dqr.entity.mobEntity.monsterSP.DqmEntityKandata;
import dqr.entity.mobEntity.monsterSP.DqmEntityKandatakobun;
import dqr.entity.mobEntity.monsterSP.DqmEntityKinghidora;
import dqr.entity.mobEntity.monsterSP.DqmEntityKiramajinga;
import dqr.entity.mobEntity.monsterSP.DqmEntityKiratoti;
import dqr.entity.mobEntity.monsterSP.DqmEntityMashougumo;
import dqr.entity.mobEntity.monsterSP.DqmEntityMasso;
import dqr.entity.mobEntity.monsterSP.DqmEntityPisaronaito;
import dqr.entity.mobEntity.monsterSP.DqmEntityPuremiasuraimu;
import dqr.entity.mobEntity.monsterSP.DqmEntitySirubamanto;
import dqr.entity.mobEntity.monsterSP.DqmEntitySuraimuemperor;
import dqr.entity.mobEntity.monsterSP.DqmEntitySuraimujeneraru;
import dqr.entity.mobEntity.monsterSP.DqmEntityTattyan;
import dqr.entity.mobEntity.monsterSP.DqmEntityTororubakkosu;
import dqr.entity.mobEntity.monsterSP.DqmEntityUragirikozou;
import dqr.entity.mobEntity.monsterSP.DqmEntityWanpakusatan;
import dqr.entity.mobEntity.monsterSP.DqmEntityYamatanooroti;
import dqr.entity.mobEntity.monsterTensei.DqmEntityArukemisuton;
import dqr.entity.mobEntity.monsterTensei.DqmEntityBebingosatan;
import dqr.entity.mobEntity.monsterTensei.DqmEntityDebirurodo;
import dqr.entity.mobEntity.monsterTensei.DqmEntityGoldmanto;
import dqr.entity.mobEntity.monsterTensei.DqmEntityGorudenkon;
import dqr.entity.mobEntity.monsterTensei.DqmEntityHatonaito;
import dqr.entity.mobEntity.monsterTensei.DqmEntityKirapike;
import dqr.entity.mobEntity.monsterTensei.DqmEntityKuinmomon;
import dqr.entity.mobEntity.monsterTensei.DqmEntityMaaburun;
import dqr.entity.mobEntity.monsterTensei.DqmEntityMadrainbow;
import dqr.entity.mobEntity.monsterTensei.DqmEntityMetaruhoimin;
import dqr.entity.mobEntity.monsterTensei.DqmEntityMomoirosansimai;
import dqr.entity.mobEntity.monsterTensei.DqmEntityMoonkimera;
import dqr.entity.mobEntity.monsterTensei.DqmEntityNoroinoiwa;
import dqr.entity.mobEntity.monsterTensei.DqmEntityPinkbonbon;
import dqr.entity.mobEntity.monsterTensei.DqmEntityReddoatya;
import dqr.entity.mobEntity.monsterTensei.DqmEntitySabotengold;
import dqr.entity.mobEntity.monsterTensei.DqmEntitySeigin;
import dqr.entity.mobEntity.monsterTensei.DqmEntityShuvaluts;
import dqr.entity.mobEntity.monsterTensei.DqmEntitySirudoaniki;
import dqr.entity.mobEntity.monsterTensei.DqmEntitySweetbag;
import dqr.entity.mobEntity.monsterTensei.DqmEntityTaipug;
import dqr.entity.mobEntity.monsterTensei.DqmEntityTogekonbou;
import dqr.entity.mobEntity.monsterTensei.DqmEntityTumurinmama;
import dqr.entity.mobEntity.monsterTensei.DqmEntityTyokonuba;


public class FuncMobSpawnChanger {

	public BiomeGenBase[] TFBiomes = {TFBiomeBase.twilightForest, TFBiomeBase.twilightForest2, TFBiomeBase.mushrooms, TFBiomeBase.clearing,
									  TFBiomeBase.oakSavanna, TFBiomeBase.deepMushrooms, TFBiomeBase.fireflyForest,
									  TFBiomeBase.tfSwamp, TFBiomeBase.fireSwamp,
									  TFBiomeBase.darkForest, TFBiomeBase.darkForestCenter,
									  TFBiomeBase.tfSnow, TFBiomeBase.glacier, TFBiomeBase.highlands,
									  TFBiomeBase.thornlands,
									  TFBiomeBase.highlandsCenter};

	public int[] TFBiomesCategs = {1, 1, 1, 1,
								   2, 2, 2,
								   3, 8,
								   4, 4,
								   5, 5, 5,
								   6,
								   7};
	public FuncMobSpawnChanger()
	{

		for(int cnt2 = 0; cnt2 < TFBiomes.length; cnt2++)
		{
			List removeList = new ArrayList();
			List list = TFBiomes[cnt2].getSpawnableList(EnumCreatureType.monster);

			for(int cnt = 0; cnt < list.size();cnt++)
			{
				SpawnListEntry test = (SpawnListEntry)list.get(cnt);
				if(DqmMobBase.class.isAssignableFrom(test.entityClass) ||
					test.entityClass.isInstance(DqmMobBase.class))
				{
					removeList.add(test);
				}
			}

			for(int cnt = 0; cnt < removeList.size();cnt++)
			{
				SpawnListEntry test = (SpawnListEntry)removeList.get(cnt);
				list.remove(test);
			}

			switch(TFBiomesCategs[cnt2])
			{
				case 1: setSpawnListOverworld(list); break;
				case 2: setSpawnListOverworld2(list); break;
				case 3: setSpawnListNether(list); break;
				case 4: setSpawnListNether2(list); break;
				case 5: setSpawnListEnd(list); break;
				case 6: setSpawnListHell1(list); break;
				case 7: setSpawnListHell2(list); break;
				case 8: setSpawnListDragon(list); break;
			}


			list = TFBiomes[cnt2].getSpawnableList(EnumCreatureType.monster);
			for(int cnt = 0; cnt < list.size();cnt++)
			{
				SpawnListEntry test = (SpawnListEntry)list.get(cnt);
				//System.out.println(cnt2 + " : " + test.entityClass.getName());
			}
		}

		TFFeature.lichTower.addMonster(DqmEntityAkumanosyo.class, 10, 4, 4);
		TFFeature.lichTower.addMonster(DqmEntityGaikotukensi.class, 10, 4, 4);
		TFFeature.lichTower.addMonster(DqmEntityObakekyandoru.class, 10, 4, 4);
		setLabyrinthMonster(TFFeature.labyrinth);
		setTFStrongHoldMonster(TFFeature.tfStronghold);
		setTFStrongHoldMonster(TFFeature.darkTower);

		//TFBiomeBase.darkForestCenter.
	}

	public void setSpawnListOverworld(List par1)
	{
		par1.add(new SpawnListEntry(DqmEntitySura.class, 12, 1, 1));
		par1.add(new SpawnListEntry(DqmEntitySuraimubesu.class, 12, 1, 1));
		par1.add(new SpawnListEntry(DqmEntityRemonsuraimu.class, 12, 1, 1));
		par1.add(new SpawnListEntry(DqmEntityBubsura.class, 12, 1, 1));
		par1.add(new SpawnListEntry(DqmEntityMomon.class, 12, 1, 1));
		par1.add(new SpawnListEntry(DqmEntityOonamekuji.class, 12, 1, 1));
		par1.add(new SpawnListEntry(DqmEntitySimasimacat.class, 12, 1, 1));
		par1.add(new SpawnListEntry(DqmEntityZinmentyou.class, 12, 1, 1));
		par1.add(new SpawnListEntry(DqmEntityBigCrow.class, 12, 1, 1));
		par1.add(new SpawnListEntry(DqmEntityButisuraimu.class, 12, 1, 1));
		par1.add(new SpawnListEntry(DqmEntityDorozara.class, 12, 1, 1));
		par1.add(new SpawnListEntry(DqmEntityBigguhatto.class, 12, 1, 1));
		par1.add(new SpawnListEntry(DqmEntityIkkakuusagi.class, 12, 1, 1));
		par1.add(new SpawnListEntry(DqmEntityItamogu.class, 12, 1, 1));
		par1.add(new SpawnListEntry(DqmEntityTogebouzu.class, 12, 1, 1));
		par1.add(new SpawnListEntry(DqmEntityZukkinya.class, 12, 1, 1));
		par1.add(new SpawnListEntry(DqmEntityOnikozou.class, 12, 1, 1));
		par1.add(new SpawnListEntry(DqmEntityAyasiikage.class, 12, 1, 1));
		par1.add(new SpawnListEntry(DqmEntitySukippaa.class, 12, 1, 1));
		par1.add(new SpawnListEntry(DqmEntityTukaima.class, 12, 1, 1));
		par1.add(new SpawnListEntry(DqmEntityDragosuraimu.class, 12, 1, 1));
		par1.add(new SpawnListEntry(DqmEntityGizumoAZ.class, 12, 1, 1));
		par1.add(new SpawnListEntry(DqmEntityMomonja.class, 12, 1, 1));
		par1.add(new SpawnListEntry(DqmEntityObakekinoko.class, 12, 1, 1));
		par1.add(new SpawnListEntry(DqmEntityRippusu.class, 12, 1, 1));
		par1.add(new SpawnListEntry(DqmEntitySuraimutumuri.class, 12, 1, 1));
		par1.add(new SpawnListEntry(DqmEntityHitokuikibako.class, 12, 1, 1));
		par1.add(new SpawnListEntry(DqmEntityOokiduti.class, 12, 1, 1));
		par1.add(new SpawnListEntry(DqmEntityGuntaigani.class, 12, 1, 1));
		par1.add(new SpawnListEntry(DqmEntityHoimisura.class, 12, 1, 1));
		par1.add(new SpawnListEntry(DqmEntityDokuroarai.class, 12, 1, 1));
		par1.add(new SpawnListEntry(DqmEntitySibirekurage.class, 12, 1, 1));
		par1.add(new SpawnListEntry(DqmEntitySunomon.class, 12, 1, 1));
		par1.add(new SpawnListEntry(DqmEntityKimera.class, 12, 1, 1));
		par1.add(new SpawnListEntry(DqmEntitySirudokozou.class, 12, 1, 1));
		par1.add(new SpawnListEntry(DqmEntityOomedama.class, 12, 1, 1));
		par1.add(new SpawnListEntry(DqmEntityHitokuisaberu.class, 12, 1, 1));
		par1.add(new SpawnListEntry(DqmEntityKirikabuobake.class, 12, 1, 1));
		par1.add(new SpawnListEntry(DqmEntityObakeumiusi.class, 12, 1, 1));
		par1.add(new SpawnListEntry(DqmEntityRiripat.class, 12, 1, 1));
		par1.add(new SpawnListEntry(DqmEntitySupini.class, 12, 1, 1));
		par1.add(new SpawnListEntry(DqmEntityDoronuba.class, 12, 1, 1));
		par1.add(new SpawnListEntry(DqmEntityEbiruapple.class, 12, 1, 1));
		par1.add(new SpawnListEntry(DqmEntityMadohando.class, 12, 1, 1));
		par1.add(new SpawnListEntry(DqmEntityBurauni.class, 12, 1, 1));
		par1.add(new SpawnListEntry(DqmEntityPapetkozou.class, 12, 1, 1));
		par1.add(new SpawnListEntry(DqmEntityPurizunyan.class, 12, 1, 1));
		par1.add(new SpawnListEntry(DqmEntityWaraibukuro.class, 12, 1, 1));
		par1.add(new SpawnListEntry(DqmEntityOokutibasi.class, 12, 1, 1));
		par1.add(new SpawnListEntry(DqmEntitySuraimutawa.class, 12, 1, 1));
		par1.add(new SpawnListEntry(DqmEntityUzusioking.class, 12, 1, 1));
		par1.add(new SpawnListEntry(DqmEntityDucksbill.class, 12, 1, 1));
		par1.add(new SpawnListEntry(DqmEntitySuraimunaito.class, 12, 1, 1));
		par1.add(new SpawnListEntry(DqmEntityKirapan.class, 12, 1, 1));
		par1.add(new SpawnListEntry(DqmEntityDoruido.class, 12, 1, 1));
		par1.add(new SpawnListEntry(DqmEntityFaratto.class, 12, 1, 1));
		par1.add(new SpawnListEntry(DqmEntityGaikotu.class, 12, 1, 1));
		par1.add(new SpawnListEntry(DqmEntitySabotenboru.class, 12, 1, 1));
		par1.add(new SpawnListEntry(DqmEntityDoraki.class, 20, 1, 1));
		par1.add(new SpawnListEntry(DqmEntityGhost.class, 20, 1, 1));
		par1.add(new SpawnListEntry(DqmEntityMeragosuto.class, 20, 1, 1));
		par1.add(new SpawnListEntry(DqmEntityObakekyandoru.class, 20, 1, 1));
		par1.add(new SpawnListEntry(DqmEntityDorakima.class, 20, 1, 1));
		par1.add(new SpawnListEntry(DqmEntitySyado.class, 20, 1, 1));
		par1.add(new SpawnListEntry(DqmEntityTutiwarasi.class, 20, 1, 1));
		par1.add(new SpawnListEntry(DqmEntityHitokuiga.class, 20, 1, 1));
		par1.add(new SpawnListEntry(DqmEntityMetoroghost.class, 20, 1, 1));
		par1.add(new SpawnListEntry(DqmEntityArumiraji.class, 20, 1, 1));
		par1.add(new SpawnListEntry(DqmEntityHgizumo.class, 20, 1, 1));
		par1.add(new SpawnListEntry(DqmEntityTahodoraki.class, 20, 1, 1));
		par1.add(new SpawnListEntry(DqmEntityAnimaruzonbi.class, 20, 1, 1));
		par1.add(new SpawnListEntry(DqmEntityHoroghost.class, 20, 1, 1));
		par1.add(new SpawnListEntry(DqmEntityKirasuko.class, 20, 1, 1));
		par1.add(new SpawnListEntry(DqmEntityPinkmomon.class, 20, 1, 1));
		par1.add(new SpawnListEntry(DqmEntityUmiusi.class, 20, 1, 1));
		par1.add(new SpawnListEntry(DqmEntitySibireageha.class, 20, 1, 1));
		par1.add(new SpawnListEntry(DqmEntityBerobero.class, 20, 1, 1));
		par1.add(new SpawnListEntry(DqmEntityFgizumo.class, 20, 1, 1));
		par1.add(new SpawnListEntry(DqmEntityHerughost.class, 20, 1, 1));
		par1.add(new SpawnListEntry(DqmEntitySuraimubogu.class, 20, 1, 1));
		par1.add(new SpawnListEntry(DqmEntityTomosibikozou.class, 20, 1, 1));
		par1.add(new SpawnListEntry(DqmEntityBebisatan.class, 20, 1, 1));
		par1.add(new SpawnListEntry(DqmEntityBehoimisuraimu.class, 20, 1, 1));
		par1.add(new SpawnListEntry(DqmEntityBuchunpa.class, 20, 1, 1));
		par1.add(new SpawnListEntry(DqmEntityHyouganmajin.class, 20, 1, 1));
		par1.add(new SpawnListEntry(DqmEntityMarinsuraimu.class, 20, 1, 1));
		par1.add(new SpawnListEntry(DqmEntityMatango.class, 20, 1, 1));
		par1.add(new SpawnListEntry(DqmEntityOdoruhouseki.class, 20, 1, 1));
		par1.add(new SpawnListEntry(DqmEntitySibiredanbira.class, 20, 1, 1));
		par1.add(new SpawnListEntry(DqmEntityTonburero.class, 20, 1, 1));
		par1.add(new SpawnListEntry(DqmEntityBakudanbebi.class, 20, 1, 1));
		par1.add(new SpawnListEntry(DqmEntityDesufuratta.class, 20, 1, 1));
		par1.add(new SpawnListEntry(DqmEntityJeriman.class, 20, 1, 1));
		par1.add(new SpawnListEntry(DqmEntityAkumanosyo.class, 20, 1, 1));
		par1.add(new SpawnListEntry(DqmEntityBakudaniwa.class, 20, 1, 1));
		par1.add(new SpawnListEntry(DqmEntityDokuyazukin.class, 20, 1, 1));
		par1.add(new SpawnListEntry(DqmEntitySamayoutamasii.class, 20, 1, 1));
		par1.add(new SpawnListEntry(DqmEntitySuraimuburesu.class, 20, 1, 1));
		par1.add(new SpawnListEntry(DqmEntityBaburin.class, 20, 1, 1));
		par1.add(new SpawnListEntry(DqmEntityAkumanotubo.class, 20, 1, 1));
		par1.add(new SpawnListEntry(DqmEntityBehoimusuraimu.class, 20, 1, 1));
		par1.add(new SpawnListEntry(DqmEntityEnzeruslime.class, 20, 1, 1));
		par1.add(new SpawnListEntry(DqmEntityGaikotukensi.class, 20, 1, 1));
		par1.add(new SpawnListEntry(DqmEntitySumoruguru.class, 20, 1, 1));
		par1.add(new SpawnListEntry(DqmEntitySupekutetto.class, 20, 1, 1));
		par1.add(new SpawnListEntry(DqmEntitySura2.class, 20, 1, 1));
		par1.add(new SpawnListEntry(DqmEntityBeronyaago.class, 20, 1, 1));
		par1.add(new SpawnListEntry(DqmEntityButtizukinya.class, 20, 1, 1));
		par1.add(new SpawnListEntry(DqmEntityMeijikimera.class, 20, 1, 1));
		par1.add(new SpawnListEntry(DqmEntityMetaruraida.class, 20, 1, 1));
		par1.add(new SpawnListEntry(DqmEntityNightwalker.class, 20, 1, 1));
		par1.add(new SpawnListEntry(DqmEntityYouganmajin.class, 20, 1, 1));
		par1.add(new SpawnListEntry(DqmEntityMrippusu.class, 20, 1, 1));
		par1.add(new SpawnListEntry(DqmEntityBuraddihando.class, 20, 1, 1));
		par1.add(new SpawnListEntry(DqmEntitySkullgaroo.class, 20, 1, 1));
		par1.add(new SpawnListEntry(DqmEntityMeijidoraki.class, 20, 1, 1));
		par1.add(new SpawnListEntry(DqmEntitySumairurokku.class, 20, 1, 1));
		par1.add(new SpawnListEntry(DqmEntityMapetman.class, 20, 1, 1));
		par1.add(new SpawnListEntry(DqmEntityKingsura.class, 20, 1, 1));
		par1.add(new SpawnListEntry(DqmEntityMinidemon.class, 20, 1, 1));
		par1.add(new SpawnListEntry(DqmEntityMetaruhantaken.class, 20, 1, 1));
		par1.add(new SpawnListEntry(DqmEntityKirapan2.class, 20, 1, 1));
		par1.add(new SpawnListEntry(DqmEntityAxedoragon.class, 20, 1, 1));
		par1.add(new SpawnListEntry(DqmEntityBesuking.class, 20, 1, 1));
		par1.add(new SpawnListEntry(DqmEntityDansunidoru.class, 20, 1, 1));
		par1.add(new SpawnListEntry(DqmEntityDoroningyou.class, 20, 1, 1));
		par1.add(new SpawnListEntry(DqmEntityGappurin.class, 20, 1, 1));
		par1.add(new SpawnListEntry(DqmEntityGenjutusi.class, 20, 1, 1));
		par1.add(new SpawnListEntry(DqmEntityMokomokojuu.class, 20, 1, 1));
		par1.add(new SpawnListEntry(DqmEntityRaimusuraimu.class, 20, 1, 1));
		par1.add(new SpawnListEntry(DqmEntitySamayouyoroi.class, 20, 1, 1));
		par1.add(new SpawnListEntry(DqmEntityTororu.class, 20, 1, 1));
		par1.add(new SpawnListEntry(DqmEntityGorotuki.class, 20, 1, 1));

	}


	public void setSpawnListOverworld2(List par1)
	{
		par1.add(new SpawnListEntry(DqmEntityDoraki.class, 20, 1, 1));
		par1.add(new SpawnListEntry(DqmEntityGhost.class, 20, 1, 1));
		par1.add(new SpawnListEntry(DqmEntityMeragosuto.class, 20, 1, 1));
		par1.add(new SpawnListEntry(DqmEntityObakekyandoru.class, 20, 1, 1));
		par1.add(new SpawnListEntry(DqmEntityDorakima.class, 20, 1, 1));
		par1.add(new SpawnListEntry(DqmEntitySyado.class, 20, 1, 1));
		par1.add(new SpawnListEntry(DqmEntityTutiwarasi.class, 20, 1, 1));
		par1.add(new SpawnListEntry(DqmEntityHitokuiga.class, 20, 1, 1));
		par1.add(new SpawnListEntry(DqmEntityMetoroghost.class, 20, 1, 1));
		par1.add(new SpawnListEntry(DqmEntityArumiraji.class, 20, 1, 1));
		par1.add(new SpawnListEntry(DqmEntityHgizumo.class, 20, 1, 1));
		par1.add(new SpawnListEntry(DqmEntityTahodoraki.class, 20, 1, 1));
		par1.add(new SpawnListEntry(DqmEntityAnimaruzonbi.class, 20, 1, 1));
		par1.add(new SpawnListEntry(DqmEntityHoroghost.class, 20, 1, 1));
		par1.add(new SpawnListEntry(DqmEntityKirasuko.class, 20, 1, 1));
		par1.add(new SpawnListEntry(DqmEntityPinkmomon.class, 20, 1, 1));
		par1.add(new SpawnListEntry(DqmEntityUmiusi.class, 20, 1, 1));
		par1.add(new SpawnListEntry(DqmEntitySibireageha.class, 20, 1, 1));
		par1.add(new SpawnListEntry(DqmEntityBerobero.class, 20, 1, 1));
		par1.add(new SpawnListEntry(DqmEntityFgizumo.class, 20, 1, 1));
		par1.add(new SpawnListEntry(DqmEntityHerughost.class, 20, 1, 1));
		par1.add(new SpawnListEntry(DqmEntitySuraimubogu.class, 20, 1, 1));
		par1.add(new SpawnListEntry(DqmEntityTomosibikozou.class, 20, 1, 1));
		par1.add(new SpawnListEntry(DqmEntityBebisatan.class, 20, 1, 1));
		par1.add(new SpawnListEntry(DqmEntityBehoimisuraimu.class, 20, 1, 1));
		par1.add(new SpawnListEntry(DqmEntityBuchunpa.class, 20, 1, 1));
		par1.add(new SpawnListEntry(DqmEntityHyouganmajin.class, 20, 1, 1));
		par1.add(new SpawnListEntry(DqmEntityMarinsuraimu.class, 20, 1, 1));
		par1.add(new SpawnListEntry(DqmEntityMatango.class, 20, 1, 1));
		par1.add(new SpawnListEntry(DqmEntityOdoruhouseki.class, 20, 1, 1));
		par1.add(new SpawnListEntry(DqmEntitySibiredanbira.class, 20, 1, 1));
		par1.add(new SpawnListEntry(DqmEntityTonburero.class, 20, 1, 1));
		par1.add(new SpawnListEntry(DqmEntityBakudanbebi.class, 20, 1, 1));
		par1.add(new SpawnListEntry(DqmEntityDesufuratta.class, 20, 1, 1));
		par1.add(new SpawnListEntry(DqmEntityJeriman.class, 20, 1, 1));
		par1.add(new SpawnListEntry(DqmEntityAkumanosyo.class, 20, 1, 1));
		par1.add(new SpawnListEntry(DqmEntityBakudaniwa.class, 20, 1, 1));
		par1.add(new SpawnListEntry(DqmEntityDokuyazukin.class, 20, 1, 1));
		par1.add(new SpawnListEntry(DqmEntitySamayoutamasii.class, 20, 1, 1));
		par1.add(new SpawnListEntry(DqmEntitySuraimuburesu.class, 20, 1, 1));
		par1.add(new SpawnListEntry(DqmEntityBaburin.class, 20, 1, 1));
		par1.add(new SpawnListEntry(DqmEntityAkumanotubo.class, 20, 1, 1));
		par1.add(new SpawnListEntry(DqmEntityBehoimusuraimu.class, 20, 1, 1));
		par1.add(new SpawnListEntry(DqmEntityEnzeruslime.class, 20, 1, 1));
		par1.add(new SpawnListEntry(DqmEntityGaikotukensi.class, 20, 1, 1));
		par1.add(new SpawnListEntry(DqmEntitySumoruguru.class, 20, 1, 1));
		par1.add(new SpawnListEntry(DqmEntitySupekutetto.class, 20, 1, 1));
		par1.add(new SpawnListEntry(DqmEntitySura2.class, 20, 1, 1));
		par1.add(new SpawnListEntry(DqmEntityBeronyaago.class, 20, 1, 1));
		par1.add(new SpawnListEntry(DqmEntityButtizukinya.class, 20, 1, 1));
		par1.add(new SpawnListEntry(DqmEntityMeijikimera.class, 20, 1, 1));
		par1.add(new SpawnListEntry(DqmEntityMetaruraida.class, 20, 1, 1));
		par1.add(new SpawnListEntry(DqmEntityNightwalker.class, 20, 1, 1));
		par1.add(new SpawnListEntry(DqmEntityYouganmajin.class, 20, 1, 1));
		par1.add(new SpawnListEntry(DqmEntityMrippusu.class, 20, 1, 1));
		par1.add(new SpawnListEntry(DqmEntityBuraddihando.class, 20, 1, 1));
		par1.add(new SpawnListEntry(DqmEntitySkullgaroo.class, 20, 1, 1));
		par1.add(new SpawnListEntry(DqmEntityMeijidoraki.class, 20, 1, 1));
		par1.add(new SpawnListEntry(DqmEntitySumairurokku.class, 20, 1, 1));
		par1.add(new SpawnListEntry(DqmEntityMapetman.class, 20, 1, 1));
		par1.add(new SpawnListEntry(DqmEntityKingsura.class, 20, 1, 1));
		par1.add(new SpawnListEntry(DqmEntityMinidemon.class, 20, 1, 1));
		par1.add(new SpawnListEntry(DqmEntityMetaruhantaken.class, 20, 1, 1));
		par1.add(new SpawnListEntry(DqmEntityKirapan2.class, 20, 1, 1));
		par1.add(new SpawnListEntry(DqmEntityAxedoragon.class, 20, 1, 1));
		par1.add(new SpawnListEntry(DqmEntityBesuking.class, 20, 1, 1));
		par1.add(new SpawnListEntry(DqmEntityDansunidoru.class, 20, 1, 1));
		par1.add(new SpawnListEntry(DqmEntityDoroningyou.class, 20, 1, 1));
		par1.add(new SpawnListEntry(DqmEntityGappurin.class, 20, 1, 1));
		par1.add(new SpawnListEntry(DqmEntityGenjutusi.class, 20, 1, 1));
		par1.add(new SpawnListEntry(DqmEntityMokomokojuu.class, 20, 1, 1));
		par1.add(new SpawnListEntry(DqmEntityRaimusuraimu.class, 20, 1, 1));
		par1.add(new SpawnListEntry(DqmEntitySamayouyoroi.class, 20, 1, 1));
		par1.add(new SpawnListEntry(DqmEntityTororu.class, 20, 1, 1));
		par1.add(new SpawnListEntry(DqmEntityGorotuki.class, 20, 1, 1));

		par1.add(new SpawnListEntry(DqmEntityMimikku.class, 12, 1, 1));
		par1.add(new SpawnListEntry(DqmEntityGorudentotemu.class, 12, 1, 1));
		par1.add(new SpawnListEntry(DqmEntitySiryounokisi.class, 12, 1, 1));
		par1.add(new SpawnListEntry(DqmEntityAroinpu.class, 12, 1, 1));
		par1.add(new SpawnListEntry(DqmEntityMajikaruhatto.class, 12, 1, 1));
		par1.add(new SpawnListEntry(DqmEntityMetaruhanta.class, 12, 1, 1));
		par1.add(new SpawnListEntry(DqmEntityUmibouzu.class, 12, 1, 1));
		par1.add(new SpawnListEntry(DqmEntityDeddopekka.class, 12, 1, 1));
		par1.add(new SpawnListEntry(DqmEntityBehomasuraimu.class, 12, 1, 1));
		par1.add(new SpawnListEntry(DqmEntityBiggufeisu.class, 12, 1, 1));
		par1.add(new SpawnListEntry(DqmEntityGoremu.class, 12, 1, 1));
		par1.add(new SpawnListEntry(DqmEntityHotatewarabi.class, 12, 1, 1));
		par1.add(new SpawnListEntry(DqmEntityJigokunohasami.class, 12, 1, 1));
		par1.add(new SpawnListEntry(DqmEntityMaporena.class, 12, 1, 1));
		par1.add(new SpawnListEntry(DqmEntityDarkslime.class, 12, 1, 1));
		par1.add(new SpawnListEntry(DqmEntityDqmdragon.class, 12, 1, 1));
		par1.add(new SpawnListEntry(DqmEntityGamegon.class, 12, 1, 1));
		par1.add(new SpawnListEntry(DqmEntityMagemomonja.class, 12, 1, 1));
		par1.add(new SpawnListEntry(DqmEntityPikusi.class, 12, 1, 1));
		par1.add(new SpawnListEntry(DqmEntitySuraimuhaitawa.class, 12, 1, 1));
		par1.add(new SpawnListEntry(DqmEntityBariidodog.class, 12, 1, 1));
		par1.add(new SpawnListEntry(DqmEntityMaounokage.class, 12, 1, 1));
		par1.add(new SpawnListEntry(DqmEntityMegazarurokku.class, 12, 1, 1));
		par1.add(new SpawnListEntry(DqmEntityBurakkubejita.class, 12, 1, 1));
		par1.add(new SpawnListEntry(DqmEntityDragonnaito.class, 12, 1, 1));
		par1.add(new SpawnListEntry(DqmEntityBuraddosodo.class, 12, 1, 1));
		par1.add(new SpawnListEntry(DqmEntityBarakku.class, 12, 1, 1));
		par1.add(new SpawnListEntry(DqmEntityBoureikensi.class, 12, 1, 1));
		par1.add(new SpawnListEntry(DqmEntityGanirasu.class, 12, 1, 1));
		par1.add(new SpawnListEntry(DqmEntityGoldman.class, 12, 1, 1));
		par1.add(new SpawnListEntry(DqmEntityRedsaikuron.class, 12, 1, 1));
		par1.add(new SpawnListEntry(DqmEntitySuraimubehomazun.class, 12, 1, 1));
		par1.add(new SpawnListEntry(DqmEntityGamegonload.class, 12, 1, 1));
		par1.add(new SpawnListEntry(DqmEntityPuyon.class, 12, 1, 1));
		par1.add(new SpawnListEntry(DqmEntityBaburuking.class, 12, 1, 1));
		par1.add(new SpawnListEntry(DqmEntityDgizumo.class, 12, 1, 1));
		par1.add(new SpawnListEntry(DqmEntityDollmaster.class, 12, 1, 1));
		par1.add(new SpawnListEntry(DqmEntityKiramasin.class, 12, 1, 1));
		par1.add(new SpawnListEntry(DqmEntityKisudragon.class, 12, 1, 1));
		par1.add(new SpawnListEntry(DqmEntityKuinsuraimu.class, 12, 1, 1));
		par1.add(new SpawnListEntry(DqmEntityAnkokumajin.class, 12, 1, 1));
		par1.add(new SpawnListEntry(DqmEntityKemunkurusu.class, 12, 1, 1));
		par1.add(new SpawnListEntry(DqmEntityKirakurabu.class, 12, 1, 1));
		par1.add(new SpawnListEntry(DqmEntityMagematango.class, 12, 1, 1));
		par1.add(new SpawnListEntry(DqmEntityTubokku.class, 12, 1, 1));
		par1.add(new SpawnListEntry(DqmEntityMagumaron.class, 12, 1, 1));
		par1.add(new SpawnListEntry(DqmEntityPombom.class, 12, 1, 1));
		par1.add(new SpawnListEntry(DqmEntityStarkimera.class, 12, 1, 1));
		par1.add(new SpawnListEntry(DqmEntitySodofantomu.class, 12, 1, 1));
		par1.add(new SpawnListEntry(DqmEntityDragonraida.class, 12, 1, 1));
		par1.add(new SpawnListEntry(DqmEntitySirubadebiru.class, 12, 1, 1));
		par1.add(new SpawnListEntry(DqmEntitySuraimumadyura.class, 12, 1, 1));
		par1.add(new SpawnListEntry(DqmEntitySaikuropusu.class, 12, 1, 1));
		par1.add(new SpawnListEntry(DqmEntityStonman.class, 12, 1, 1));
		par1.add(new SpawnListEntry(DqmEntityBighanma.class, 12, 1, 1));
		par1.add(new SpawnListEntry(DqmEntityBosutororu.class, 12, 1, 1));
		par1.add(new SpawnListEntry(DqmEntityDoragonsoruja.class, 12, 1, 1));
		par1.add(new SpawnListEntry(DqmEntityFureimu.class, 12, 1, 1));
		par1.add(new SpawnListEntry(DqmEntityKedamon.class, 12, 1, 1));
		par1.add(new SpawnListEntry(DqmEntityKimendousi.class, 12, 1, 1));
		par1.add(new SpawnListEntry(DqmEntityKiraama.class, 12, 1, 1));
		par1.add(new SpawnListEntry(DqmEntityKiramasin2.class, 12, 1, 1));
		par1.add(new SpawnListEntry(DqmEntityPapettoman.class, 12, 1, 1));
		par1.add(new SpawnListEntry(DqmEntitySiryou.class, 12, 1, 1));
		par1.add(new SpawnListEntry(DqmEntityTororuking.class, 12, 1, 1));
		par1.add(new SpawnListEntry(DqmEntityEriminator.class, 12, 1, 1));
		par1.add(new SpawnListEntry(DqmEntityDarkdoriado.class, 12, 1, 1));
		par1.add(new SpawnListEntry(DqmEntityShadopan.class, 12, 1, 1));
		par1.add(new SpawnListEntry(DqmEntityWhitepan2.class, 12, 1, 1));
	}



	public void setSpawnListNether(List par1)
	{
		par1.add(new SpawnListEntry(DqmEntityMimikku.class, 20, 1, 1));
		par1.add(new SpawnListEntry(DqmEntityGorudentotemu.class, 20, 1, 1));
		par1.add(new SpawnListEntry(DqmEntitySiryounokisi.class, 20, 1, 1));
		par1.add(new SpawnListEntry(DqmEntityAroinpu.class, 20, 1, 1));
		par1.add(new SpawnListEntry(DqmEntityMajikaruhatto.class, 20, 1, 1));
		par1.add(new SpawnListEntry(DqmEntityMetaruhanta.class, 20, 1, 1));
		par1.add(new SpawnListEntry(DqmEntityUmibouzu.class, 20, 1, 1));
		par1.add(new SpawnListEntry(DqmEntityDeddopekka.class, 20, 1, 1));
		par1.add(new SpawnListEntry(DqmEntityBehomasuraimu.class, 20, 1, 1));
		par1.add(new SpawnListEntry(DqmEntityBiggufeisu.class, 20, 1, 1));
		par1.add(new SpawnListEntry(DqmEntityGoremu.class, 20, 1, 1));
		par1.add(new SpawnListEntry(DqmEntityHotatewarabi.class, 20, 1, 1));
		par1.add(new SpawnListEntry(DqmEntityJigokunohasami.class, 20, 1, 1));
		par1.add(new SpawnListEntry(DqmEntityMaporena.class, 20, 1, 1));
		par1.add(new SpawnListEntry(DqmEntityDarkslime.class, 20, 1, 1));
		par1.add(new SpawnListEntry(DqmEntityDqmdragon.class, 20, 1, 1));
		par1.add(new SpawnListEntry(DqmEntityGamegon.class, 20, 1, 1));
		par1.add(new SpawnListEntry(DqmEntityMagemomonja.class, 20, 1, 1));
		par1.add(new SpawnListEntry(DqmEntityPikusi.class, 20, 1, 1));
		par1.add(new SpawnListEntry(DqmEntitySuraimuhaitawa.class, 20, 1, 1));
		par1.add(new SpawnListEntry(DqmEntityBariidodog.class, 20, 1, 1));
		par1.add(new SpawnListEntry(DqmEntityMaounokage.class, 20, 1, 1));
		par1.add(new SpawnListEntry(DqmEntityMegazarurokku.class, 20, 1, 1));
		par1.add(new SpawnListEntry(DqmEntityBurakkubejita.class, 20, 1, 1));
		par1.add(new SpawnListEntry(DqmEntityDragonnaito.class, 20, 1, 1));
		par1.add(new SpawnListEntry(DqmEntityBuraddosodo.class, 20, 1, 1));
		par1.add(new SpawnListEntry(DqmEntityBarakku.class, 20, 1, 1));
		par1.add(new SpawnListEntry(DqmEntityBoureikensi.class, 20, 1, 1));
		par1.add(new SpawnListEntry(DqmEntityGanirasu.class, 20, 1, 1));
		par1.add(new SpawnListEntry(DqmEntityGoldman.class, 20, 1, 1));
		par1.add(new SpawnListEntry(DqmEntityRedsaikuron.class, 20, 1, 1));
		par1.add(new SpawnListEntry(DqmEntitySuraimubehomazun.class, 20, 1, 1));
		par1.add(new SpawnListEntry(DqmEntityGamegonload.class, 20, 1, 1));
		par1.add(new SpawnListEntry(DqmEntityPuyon.class, 20, 1, 1));
		par1.add(new SpawnListEntry(DqmEntityBaburuking.class, 20, 1, 1));
		par1.add(new SpawnListEntry(DqmEntityDgizumo.class, 20, 1, 1));
		par1.add(new SpawnListEntry(DqmEntityDollmaster.class, 20, 1, 1));
		par1.add(new SpawnListEntry(DqmEntityKiramasin.class, 20, 1, 1));
		par1.add(new SpawnListEntry(DqmEntityKisudragon.class, 20, 1, 1));
		par1.add(new SpawnListEntry(DqmEntityKuinsuraimu.class, 20, 1, 1));
		par1.add(new SpawnListEntry(DqmEntityAnkokumajin.class, 20, 1, 1));
		par1.add(new SpawnListEntry(DqmEntityKemunkurusu.class, 20, 1, 1));
		par1.add(new SpawnListEntry(DqmEntityKirakurabu.class, 20, 1, 1));
		par1.add(new SpawnListEntry(DqmEntityMagematango.class, 20, 1, 1));
		par1.add(new SpawnListEntry(DqmEntityTubokku.class, 20, 1, 1));
		par1.add(new SpawnListEntry(DqmEntityMagumaron.class, 20, 1, 1));
		par1.add(new SpawnListEntry(DqmEntityPombom.class, 20, 1, 1));
		par1.add(new SpawnListEntry(DqmEntityStarkimera.class, 20, 1, 1));
		par1.add(new SpawnListEntry(DqmEntitySodofantomu.class, 20, 1, 1));
		par1.add(new SpawnListEntry(DqmEntityDragonraida.class, 20, 1, 1));
		par1.add(new SpawnListEntry(DqmEntitySirubadebiru.class, 20, 1, 1));
		par1.add(new SpawnListEntry(DqmEntitySuraimumadyura.class, 20, 1, 1));
		par1.add(new SpawnListEntry(DqmEntitySaikuropusu.class, 20, 1, 1));
		par1.add(new SpawnListEntry(DqmEntityStonman.class, 20, 1, 1));
		par1.add(new SpawnListEntry(DqmEntityBighanma.class, 20, 1, 1));
		par1.add(new SpawnListEntry(DqmEntityBosutororu.class, 20, 1, 1));
		par1.add(new SpawnListEntry(DqmEntityDoragonsoruja.class, 20, 1, 1));
		par1.add(new SpawnListEntry(DqmEntityFureimu.class, 20, 1, 1));
		par1.add(new SpawnListEntry(DqmEntityKedamon.class, 20, 1, 1));
		par1.add(new SpawnListEntry(DqmEntityKimendousi.class, 20, 1, 1));
		par1.add(new SpawnListEntry(DqmEntityKiraama.class, 20, 1, 1));
		par1.add(new SpawnListEntry(DqmEntityKiramasin2.class, 20, 1, 1));
		par1.add(new SpawnListEntry(DqmEntityPapettoman.class, 20, 1, 1));
		par1.add(new SpawnListEntry(DqmEntitySiryou.class, 20, 1, 1));
		par1.add(new SpawnListEntry(DqmEntityTororuking.class, 20, 1, 1));
		par1.add(new SpawnListEntry(DqmEntityEriminator.class, 20, 1, 1));
		par1.add(new SpawnListEntry(DqmEntityDarkdoriado.class, 20, 1, 1));
		par1.add(new SpawnListEntry(DqmEntityShadopan.class, 20, 1, 1));
		par1.add(new SpawnListEntry(DqmEntityWhitepan2.class, 20, 1, 1));

	}


	public void setSpawnListNether2(List par1)
	{
		par1.add(new SpawnListEntry(DqmEntityMimikku.class, 20, 1, 1));
		par1.add(new SpawnListEntry(DqmEntityGorudentotemu.class, 20, 1, 1));
		par1.add(new SpawnListEntry(DqmEntitySiryounokisi.class, 20, 1, 1));
		par1.add(new SpawnListEntry(DqmEntityAroinpu.class, 20, 1, 1));
		par1.add(new SpawnListEntry(DqmEntityMajikaruhatto.class, 20, 1, 1));
		par1.add(new SpawnListEntry(DqmEntityMetaruhanta.class, 20, 1, 1));
		par1.add(new SpawnListEntry(DqmEntityUmibouzu.class, 20, 1, 1));
		par1.add(new SpawnListEntry(DqmEntityDeddopekka.class, 20, 1, 1));
		par1.add(new SpawnListEntry(DqmEntityBehomasuraimu.class, 20, 1, 1));
		par1.add(new SpawnListEntry(DqmEntityBiggufeisu.class, 20, 1, 1));
		par1.add(new SpawnListEntry(DqmEntityGoremu.class, 20, 1, 1));
		par1.add(new SpawnListEntry(DqmEntityHotatewarabi.class, 20, 1, 1));
		par1.add(new SpawnListEntry(DqmEntityJigokunohasami.class, 20, 1, 1));
		par1.add(new SpawnListEntry(DqmEntityMaporena.class, 20, 1, 1));
		par1.add(new SpawnListEntry(DqmEntityDarkslime.class, 20, 1, 1));
		par1.add(new SpawnListEntry(DqmEntityDqmdragon.class, 20, 1, 1));
		par1.add(new SpawnListEntry(DqmEntityGamegon.class, 20, 1, 1));
		par1.add(new SpawnListEntry(DqmEntityMagemomonja.class, 20, 1, 1));
		par1.add(new SpawnListEntry(DqmEntityPikusi.class, 20, 1, 1));
		par1.add(new SpawnListEntry(DqmEntitySuraimuhaitawa.class, 20, 1, 1));
		par1.add(new SpawnListEntry(DqmEntityBariidodog.class, 20, 1, 1));
		par1.add(new SpawnListEntry(DqmEntityMaounokage.class, 20, 1, 1));
		par1.add(new SpawnListEntry(DqmEntityMegazarurokku.class, 20, 1, 1));
		par1.add(new SpawnListEntry(DqmEntityBurakkubejita.class, 20, 1, 1));
		par1.add(new SpawnListEntry(DqmEntityDragonnaito.class, 20, 1, 1));
		par1.add(new SpawnListEntry(DqmEntityBuraddosodo.class, 20, 1, 1));
		par1.add(new SpawnListEntry(DqmEntityBarakku.class, 20, 1, 1));
		par1.add(new SpawnListEntry(DqmEntityBoureikensi.class, 20, 1, 1));
		par1.add(new SpawnListEntry(DqmEntityGanirasu.class, 20, 1, 1));
		par1.add(new SpawnListEntry(DqmEntityGoldman.class, 20, 1, 1));
		par1.add(new SpawnListEntry(DqmEntityRedsaikuron.class, 20, 1, 1));
		par1.add(new SpawnListEntry(DqmEntitySuraimubehomazun.class, 20, 1, 1));
		par1.add(new SpawnListEntry(DqmEntityGamegonload.class, 20, 1, 1));
		par1.add(new SpawnListEntry(DqmEntityPuyon.class, 20, 1, 1));
		par1.add(new SpawnListEntry(DqmEntityBaburuking.class, 20, 1, 1));
		par1.add(new SpawnListEntry(DqmEntityDgizumo.class, 20, 1, 1));
		par1.add(new SpawnListEntry(DqmEntityDollmaster.class, 20, 1, 1));
		par1.add(new SpawnListEntry(DqmEntityKiramasin.class, 20, 1, 1));
		par1.add(new SpawnListEntry(DqmEntityKisudragon.class, 20, 1, 1));
		par1.add(new SpawnListEntry(DqmEntityKuinsuraimu.class, 20, 1, 1));
		par1.add(new SpawnListEntry(DqmEntityAnkokumajin.class, 20, 1, 1));
		par1.add(new SpawnListEntry(DqmEntityKemunkurusu.class, 20, 1, 1));
		par1.add(new SpawnListEntry(DqmEntityKirakurabu.class, 20, 1, 1));
		par1.add(new SpawnListEntry(DqmEntityMagematango.class, 20, 1, 1));
		par1.add(new SpawnListEntry(DqmEntityTubokku.class, 20, 1, 1));
		par1.add(new SpawnListEntry(DqmEntityMagumaron.class, 20, 1, 1));
		par1.add(new SpawnListEntry(DqmEntityPombom.class, 20, 1, 1));
		par1.add(new SpawnListEntry(DqmEntityStarkimera.class, 20, 1, 1));
		par1.add(new SpawnListEntry(DqmEntitySodofantomu.class, 20, 1, 1));
		par1.add(new SpawnListEntry(DqmEntityDragonraida.class, 20, 1, 1));
		par1.add(new SpawnListEntry(DqmEntitySirubadebiru.class, 20, 1, 1));
		par1.add(new SpawnListEntry(DqmEntitySuraimumadyura.class, 20, 1, 1));
		par1.add(new SpawnListEntry(DqmEntitySaikuropusu.class, 20, 1, 1));
		par1.add(new SpawnListEntry(DqmEntityStonman.class, 20, 1, 1));
		par1.add(new SpawnListEntry(DqmEntityBighanma.class, 20, 1, 1));
		par1.add(new SpawnListEntry(DqmEntityBosutororu.class, 20, 1, 1));
		par1.add(new SpawnListEntry(DqmEntityDoragonsoruja.class, 20, 1, 1));
		par1.add(new SpawnListEntry(DqmEntityFureimu.class, 20, 1, 1));
		par1.add(new SpawnListEntry(DqmEntityKedamon.class, 20, 1, 1));
		par1.add(new SpawnListEntry(DqmEntityKimendousi.class, 20, 1, 1));
		par1.add(new SpawnListEntry(DqmEntityKiraama.class, 20, 1, 1));
		par1.add(new SpawnListEntry(DqmEntityKiramasin2.class, 20, 1, 1));
		par1.add(new SpawnListEntry(DqmEntityPapettoman.class, 20, 1, 1));
		par1.add(new SpawnListEntry(DqmEntitySiryou.class, 20, 1, 1));
		par1.add(new SpawnListEntry(DqmEntityTororuking.class, 20, 1, 1));
		par1.add(new SpawnListEntry(DqmEntityEriminator.class, 20, 1, 1));
		par1.add(new SpawnListEntry(DqmEntityDarkdoriado.class, 20, 1, 1));
		par1.add(new SpawnListEntry(DqmEntityShadopan.class, 20, 1, 1));
		par1.add(new SpawnListEntry(DqmEntityWhitepan2.class, 20, 1, 1));

		par1.add(new SpawnListEntry(DqmEntityGorudensuraimu.class, 12, 1, 1));
		par1.add(new SpawnListEntry(DqmEntityPandorabox.class, 12, 1, 1));
		par1.add(new SpawnListEntry(DqmEntityBatorurex.class, 12, 1, 1));
		par1.add(new SpawnListEntry(DqmEntityAkairai.class, 12, 1, 1));
		par1.add(new SpawnListEntry(DqmEntityDasudragon.class, 12, 1, 1));
		par1.add(new SpawnListEntry(DqmEntityDesujakkaru.class, 12, 1, 1));
		par1.add(new SpawnListEntry(DqmEntityRyuiso.class, 12, 1, 1));
		par1.add(new SpawnListEntry(DqmEntityKagenokisi.class, 12, 1, 1));
		par1.add(new SpawnListEntry(DqmEntityDakunaito.class, 12, 1, 1));
		par1.add(new SpawnListEntry(DqmEntityGamegonrejendo.class, 12, 1, 1));
		par1.add(new SpawnListEntry(DqmEntityDenga.class, 12, 1, 1));
		par1.add(new SpawnListEntry(DqmEntityDragondarknaito.class, 12, 1, 1));
		par1.add(new SpawnListEntry(DqmEntityBiggumoai.class, 12, 1, 1));
		par1.add(new SpawnListEntry(DqmEntityGodraida.class, 12, 1, 1));
		par1.add(new SpawnListEntry(DqmEntityGigantesu.class, 12, 1, 1));
		par1.add(new SpawnListEntry(DqmEntityBassaimasin.class, 12, 1, 1));
		par1.add(new SpawnListEntry(DqmEntityBurizado.class, 12, 1, 1));
		par1.add(new SpawnListEntry(DqmEntityDarktororu.class, 12, 1, 1));
		par1.add(new SpawnListEntry(DqmEntityDesunyago.class, 12, 1, 1));
		par1.add(new SpawnListEntry(DqmEntityJigokunoyoroi.class, 12, 1, 1));
		par1.add(new SpawnListEntry(DqmEntityManemane.class, 12, 1, 1));
		par1.add(new SpawnListEntry(DqmEntityTororubonba.class, 12, 1, 1));
		par1.add(new SpawnListEntry(DqmEntityDakuhobitto.class, 12, 1, 1));
		par1.add(new SpawnListEntry(DqmEntityDesusutoka.class, 12, 1, 1));
		par1.add(new SpawnListEntry(DqmEntityShadopan2.class, 12, 1, 1));
	}


	public void setSpawnListEnd(List par1)
	{
		par1.add(new SpawnListEntry(DqmEntityGorudensuraimu.class, 20, 1, 1));
		par1.add(new SpawnListEntry(DqmEntityPandorabox.class, 20, 1, 1));
		par1.add(new SpawnListEntry(DqmEntityBatorurex.class, 20, 1, 1));
		par1.add(new SpawnListEntry(DqmEntityAkairai.class, 20, 1, 1));
		par1.add(new SpawnListEntry(DqmEntityDasudragon.class, 20, 1, 1));
		par1.add(new SpawnListEntry(DqmEntityDesujakkaru.class, 20, 1, 1));
		par1.add(new SpawnListEntry(DqmEntityRyuiso.class, 20, 1, 1));
		par1.add(new SpawnListEntry(DqmEntityKagenokisi.class, 20, 1, 1));
		par1.add(new SpawnListEntry(DqmEntityDakunaito.class, 20, 1, 1));
		par1.add(new SpawnListEntry(DqmEntityGamegonrejendo.class, 20, 1, 1));
		par1.add(new SpawnListEntry(DqmEntityDenga.class, 20, 1, 1));
		par1.add(new SpawnListEntry(DqmEntityDragondarknaito.class, 20, 1, 1));
		par1.add(new SpawnListEntry(DqmEntityBiggumoai.class, 20, 1, 1));
		par1.add(new SpawnListEntry(DqmEntityGodraida.class, 20, 1, 1));
		par1.add(new SpawnListEntry(DqmEntityGigantesu.class, 20, 1, 1));
		par1.add(new SpawnListEntry(DqmEntityBassaimasin.class, 20, 1, 1));
		par1.add(new SpawnListEntry(DqmEntityBurizado.class, 20, 1, 1));
		par1.add(new SpawnListEntry(DqmEntityDarktororu.class, 20, 1, 1));
		par1.add(new SpawnListEntry(DqmEntityDesunyago.class, 20, 1, 1));
		par1.add(new SpawnListEntry(DqmEntityJigokunoyoroi.class, 20, 1, 1));
		par1.add(new SpawnListEntry(DqmEntityManemane.class, 20, 1, 1));
		par1.add(new SpawnListEntry(DqmEntityTororubonba.class, 20, 1, 1));
		par1.add(new SpawnListEntry(DqmEntityDakuhobitto.class, 20, 1, 1));
		par1.add(new SpawnListEntry(DqmEntityDesusutoka.class, 20, 1, 1));
		par1.add(new SpawnListEntry(DqmEntityShadopan2.class, 20, 1, 1));

	}

	public void setSpawnListHell1(List par1)
	{
		par1.add(new SpawnListEntry(DqmEntityGorudensuraimu.class, 30, 1, 1));
		par1.add(new SpawnListEntry(DqmEntityPandorabox.class, 30, 1, 1));
		par1.add(new SpawnListEntry(DqmEntityBatorurex.class, 30, 1, 1));
		par1.add(new SpawnListEntry(DqmEntityAkairai.class, 30, 1, 1));
		par1.add(new SpawnListEntry(DqmEntityDasudragon.class, 30, 1, 1));
		par1.add(new SpawnListEntry(DqmEntityDesujakkaru.class, 30, 1, 1));
		par1.add(new SpawnListEntry(DqmEntityRyuiso.class, 30, 1, 1));
		par1.add(new SpawnListEntry(DqmEntityKagenokisi.class, 30, 1, 1));
		par1.add(new SpawnListEntry(DqmEntityDakunaito.class, 30, 1, 1));
		par1.add(new SpawnListEntry(DqmEntityGamegonrejendo.class, 30, 1, 1));
		par1.add(new SpawnListEntry(DqmEntityDenga.class, 30, 1, 1));
		par1.add(new SpawnListEntry(DqmEntityDragondarknaito.class, 30, 1, 1));
		par1.add(new SpawnListEntry(DqmEntityBiggumoai.class, 30, 1, 1));
		par1.add(new SpawnListEntry(DqmEntityGodraida.class, 30, 1, 1));
		par1.add(new SpawnListEntry(DqmEntityGigantesu.class, 30, 1, 1));
		par1.add(new SpawnListEntry(DqmEntityBassaimasin.class, 30, 1, 1));
		par1.add(new SpawnListEntry(DqmEntityBurizado.class, 30, 1, 1));
		par1.add(new SpawnListEntry(DqmEntityDarktororu.class, 30, 1, 1));
		par1.add(new SpawnListEntry(DqmEntityDesunyago.class, 30, 1, 1));
		par1.add(new SpawnListEntry(DqmEntityJigokunoyoroi.class, 30, 1, 1));
		par1.add(new SpawnListEntry(DqmEntityManemane.class, 30, 1, 1));
		par1.add(new SpawnListEntry(DqmEntityTororubonba.class, 30, 1, 1));
		par1.add(new SpawnListEntry(DqmEntityDakuhobitto.class, 30, 1, 1));
		par1.add(new SpawnListEntry(DqmEntityDesusutoka.class, 30, 1, 1));
		par1.add(new SpawnListEntry(DqmEntitySeigin.class, 12, 1, 1));
		par1.add(new SpawnListEntry(DqmEntityDebirurodo.class, 12, 1, 1));
		par1.add(new SpawnListEntry(DqmEntityMaaburun.class, 12, 1, 1));
		par1.add(new SpawnListEntry(DqmEntityArukemisuton.class, 12, 1, 1));
		par1.add(new SpawnListEntry(DqmEntityGorudenkon.class, 12, 1, 1));
		par1.add(new SpawnListEntry(DqmEntityKuinmomon.class, 12, 1, 1));
		par1.add(new SpawnListEntry(DqmEntityMoonkimera.class, 12, 1, 1));
		par1.add(new SpawnListEntry(DqmEntityTyokonuba.class, 12, 1, 1));
		par1.add(new SpawnListEntry(DqmEntityReddoatya.class, 12, 1, 1));
		par1.add(new SpawnListEntry(DqmEntityKirapike.class, 12, 1, 1));
		par1.add(new SpawnListEntry(DqmEntityTogekonbou.class, 12, 1, 1));
		par1.add(new SpawnListEntry(DqmEntityTaipug.class, 12, 1, 1));
		par1.add(new SpawnListEntry(DqmEntityBebingosatan.class, 12, 1, 1));
		par1.add(new SpawnListEntry(DqmEntityGoldmanto.class, 12, 1, 1));
		par1.add(new SpawnListEntry(DqmEntityHatonaito.class, 12, 1, 1));
		par1.add(new SpawnListEntry(DqmEntityMadrainbow.class, 12, 1, 1));
		par1.add(new SpawnListEntry(DqmEntityMetaruhoimin.class, 12, 1, 1));
		par1.add(new SpawnListEntry(DqmEntityMomoirosansimai.class, 12, 1, 1));
		par1.add(new SpawnListEntry(DqmEntityNoroinoiwa.class, 12, 1, 1));
		par1.add(new SpawnListEntry(DqmEntityPinkbonbon.class, 12, 1, 1));
		par1.add(new SpawnListEntry(DqmEntitySabotengold.class, 12, 1, 1));
		par1.add(new SpawnListEntry(DqmEntityShuvaluts.class, 12, 1, 1));
		par1.add(new SpawnListEntry(DqmEntitySirudoaniki.class, 12, 1, 1));
		par1.add(new SpawnListEntry(DqmEntitySweetbag.class, 12, 1, 1));
		par1.add(new SpawnListEntry(DqmEntityTumurinmama.class, 12, 1, 1));

	}


	public void setSpawnListHell2(List par1)
	{
		par1.add(new SpawnListEntry(DqmEntitySeigin.class, 30, 1, 1));
		par1.add(new SpawnListEntry(DqmEntityDebirurodo.class, 30, 1, 1));
		par1.add(new SpawnListEntry(DqmEntityMaaburun.class, 30, 1, 1));
		par1.add(new SpawnListEntry(DqmEntityArukemisuton.class, 30, 1, 1));
		par1.add(new SpawnListEntry(DqmEntityGorudenkon.class, 30, 1, 1));
		par1.add(new SpawnListEntry(DqmEntityKuinmomon.class, 30, 1, 1));
		par1.add(new SpawnListEntry(DqmEntityMoonkimera.class, 30, 1, 1));
		par1.add(new SpawnListEntry(DqmEntityTyokonuba.class, 30, 1, 1));
		par1.add(new SpawnListEntry(DqmEntityReddoatya.class, 30, 1, 1));
		par1.add(new SpawnListEntry(DqmEntityKirapike.class, 30, 1, 1));
		par1.add(new SpawnListEntry(DqmEntityTogekonbou.class, 30, 1, 1));
		par1.add(new SpawnListEntry(DqmEntityTaipug.class, 30, 1, 1));
		par1.add(new SpawnListEntry(DqmEntityBebingosatan.class, 30, 1, 1));
		par1.add(new SpawnListEntry(DqmEntityGoldmanto.class, 30, 1, 1));
		par1.add(new SpawnListEntry(DqmEntityHatonaito.class, 30, 1, 1));
		par1.add(new SpawnListEntry(DqmEntityMadrainbow.class, 30, 1, 1));
		par1.add(new SpawnListEntry(DqmEntityMetaruhoimin.class, 30, 1, 1));
		par1.add(new SpawnListEntry(DqmEntityMomoirosansimai.class, 30, 1, 1));
		par1.add(new SpawnListEntry(DqmEntityNoroinoiwa.class, 30, 1, 1));
		par1.add(new SpawnListEntry(DqmEntityPinkbonbon.class, 30, 1, 1));
		par1.add(new SpawnListEntry(DqmEntitySabotengold.class, 30, 1, 1));
		par1.add(new SpawnListEntry(DqmEntityShuvaluts.class, 30, 1, 1));
		par1.add(new SpawnListEntry(DqmEntitySirudoaniki.class, 30, 1, 1));
		par1.add(new SpawnListEntry(DqmEntitySweetbag.class, 30, 1, 1));
		par1.add(new SpawnListEntry(DqmEntityTumurinmama.class, 30, 1, 1));
		par1.add(new SpawnListEntry(DqmEntityKandata.class, 12, 1, 1));
		par1.add(new SpawnListEntry(DqmEntityBlackchack.class, 12, 1, 1));
		par1.add(new SpawnListEntry(DqmEntitySuraimuemperor.class, 12, 1, 1));
		par1.add(new SpawnListEntry(DqmEntityWanpakusatan.class, 12, 1, 1));
		par1.add(new SpawnListEntry(DqmEntityKiratoti.class, 12, 1, 1));
		par1.add(new SpawnListEntry(DqmEntityMashougumo.class, 12, 1, 1));
		par1.add(new SpawnListEntry(DqmEntitySirubamanto.class, 12, 1, 1));
		par1.add(new SpawnListEntry(DqmEntityDarkRamia.class, 12, 1, 1));
		par1.add(new SpawnListEntry(DqmEntityGodonheddo.class, 12, 1, 1));
		par1.add(new SpawnListEntry(DqmEntityAtorasu.class, 12, 1, 1));
		par1.add(new SpawnListEntry(DqmEntityYamatanooroti.class, 12, 1, 1));
		par1.add(new SpawnListEntry(DqmEntityBazuzu.class, 12, 1, 1));
		par1.add(new SpawnListEntry(DqmEntityKiramajinga.class, 12, 1, 1));
		par1.add(new SpawnListEntry(DqmEntitySuraimujeneraru.class, 12, 1, 1));
		par1.add(new SpawnListEntry(DqmEntityBurasu.class, 12, 1, 1));
		par1.add(new SpawnListEntry(DqmEntityKandatakobun.class, 12, 1, 1));
		par1.add(new SpawnListEntry(DqmEntityKinghidora.class, 12, 1, 1));
		par1.add(new SpawnListEntry(DqmEntityMasso.class, 12, 1, 1));
		par1.add(new SpawnListEntry(DqmEntityPisaronaito.class, 12, 1, 1));
		par1.add(new SpawnListEntry(DqmEntityPuremiasuraimu.class, 12, 1, 1));
		par1.add(new SpawnListEntry(DqmEntityTattyan.class, 12, 1, 1));
		par1.add(new SpawnListEntry(DqmEntityTororubakkosu.class, 12, 1, 1));
		par1.add(new SpawnListEntry(DqmEntityUragirikozou.class, 12, 1, 1));
		par1.add(new SpawnListEntry(DqmEntityFureizado.class, 12, 1, 1));
		par1.add(new SpawnListEntry(DqmEntityDesupisaro1.class, 1, 1, 1));
		par1.add(new SpawnListEntry(DqmEntityRyuuou.class, 1, 1, 1));
		par1.add(new SpawnListEntry(DqmEntityEsterk.class, 1, 1, 1));
		par1.add(new SpawnListEntry(DqmEntityZoma.class, 1, 1, 1));
		par1.add(new SpawnListEntry(DqmEntityMasterdoragon.class, 1, 1, 1));
	}


	public void setLabyrinthMonster(TFFeature par1)
	{

		par1.addMonster(DqmEntityMimikku.class, 19, 1, 1);
		par1.addMonster(DqmEntityGorudentotemu.class, 19, 1, 1);
		par1.addMonster(DqmEntitySiryounokisi.class, 19, 1, 1);
		par1.addMonster(DqmEntityAroinpu.class, 19, 1, 1);
		par1.addMonster(DqmEntityMajikaruhatto.class, 19, 1, 1);
		par1.addMonster(DqmEntityMetaruhanta.class, 19, 1, 1);
		par1.addMonster(DqmEntityUmibouzu.class, 19, 1, 1);
		par1.addMonster(DqmEntityDeddopekka.class, 19, 1, 1);
		par1.addMonster(DqmEntityBehomasuraimu.class, 19, 1, 1);
		par1.addMonster(DqmEntityBiggufeisu.class, 19, 1, 1);
		par1.addMonster(DqmEntityGoremu.class, 19, 1, 1);
		par1.addMonster(DqmEntityHotatewarabi.class, 19, 1, 1);
		par1.addMonster(DqmEntityJigokunohasami.class, 19, 1, 1);
		par1.addMonster(DqmEntityMaporena.class, 19, 1, 1);
		par1.addMonster(DqmEntityDarkslime.class, 19, 1, 1);
		par1.addMonster(DqmEntityDqmdragon.class, 19, 1, 1);
		par1.addMonster(DqmEntityGamegon.class, 19, 1, 1);
		par1.addMonster(DqmEntityMagemomonja.class, 19, 1, 1);
		par1.addMonster(DqmEntityPikusi.class, 19, 1, 1);
		par1.addMonster(DqmEntitySuraimuhaitawa.class, 19, 1, 1);
		par1.addMonster(DqmEntityBariidodog.class, 19, 1, 1);
		par1.addMonster(DqmEntityMaounokage.class, 19, 1, 1);
		par1.addMonster(DqmEntityMegazarurokku.class, 19, 1, 1);
		par1.addMonster(DqmEntityBurakkubejita.class, 19, 1, 1);
		par1.addMonster(DqmEntityDragonnaito.class, 19, 1, 1);
		par1.addMonster(DqmEntityBuraddosodo.class, 19, 1, 1);
		par1.addMonster(DqmEntityBarakku.class, 19, 1, 1);
		par1.addMonster(DqmEntityBoureikensi.class, 19, 1, 1);
		par1.addMonster(DqmEntityGanirasu.class, 19, 1, 1);
		par1.addMonster(DqmEntityGoldman.class, 19, 1, 1);
		par1.addMonster(DqmEntityRedsaikuron.class, 19, 1, 1);
		par1.addMonster(DqmEntitySuraimubehomazun.class, 19, 1, 1);
		par1.addMonster(DqmEntityGamegonload.class, 19, 1, 1);
		par1.addMonster(DqmEntityPuyon.class, 19, 1, 1);
		par1.addMonster(DqmEntityBaburuking.class, 19, 1, 1);
		par1.addMonster(DqmEntityDgizumo.class, 19, 1, 1);
		par1.addMonster(DqmEntityDollmaster.class, 19, 1, 1);
		par1.addMonster(DqmEntityKiramasin.class, 19, 1, 1);
		par1.addMonster(DqmEntityKisudragon.class, 19, 1, 1);
		par1.addMonster(DqmEntityKuinsuraimu.class, 19, 1, 1);
		par1.addMonster(DqmEntityAnkokumajin.class, 19, 1, 1);
		par1.addMonster(DqmEntityKemunkurusu.class, 19, 1, 1);
		par1.addMonster(DqmEntityKirakurabu.class, 19, 1, 1);
		par1.addMonster(DqmEntityMagematango.class, 19, 1, 1);
		par1.addMonster(DqmEntityTubokku.class, 19, 1, 1);
		par1.addMonster(DqmEntityMagumaron.class, 19, 1, 1);
		par1.addMonster(DqmEntityPombom.class, 19, 1, 1);
		par1.addMonster(DqmEntityStarkimera.class, 19, 1, 1);
		par1.addMonster(DqmEntitySodofantomu.class, 19, 1, 1);
		par1.addMonster(DqmEntityDragonraida.class, 19, 1, 1);
		par1.addMonster(DqmEntitySirubadebiru.class, 19, 1, 1);
		par1.addMonster(DqmEntitySuraimumadyura.class, 19, 1, 1);
		par1.addMonster(DqmEntitySaikuropusu.class, 19, 1, 1);
		par1.addMonster(DqmEntityStonman.class, 19, 1, 1);
		par1.addMonster(DqmEntityBighanma.class, 19, 1, 1);
		par1.addMonster(DqmEntityBosutororu.class, 19, 1, 1);
		par1.addMonster(DqmEntityDoragonsoruja.class, 19, 1, 1);
		par1.addMonster(DqmEntityFureimu.class, 19, 1, 1);
		par1.addMonster(DqmEntityKedamon.class, 19, 1, 1);
		par1.addMonster(DqmEntityKimendousi.class, 19, 1, 1);
		par1.addMonster(DqmEntityKiraama.class, 19, 1, 1);
		par1.addMonster(DqmEntityKiramasin2.class, 19, 1, 1);
		par1.addMonster(DqmEntityPapettoman.class, 19, 1, 1);
		par1.addMonster(DqmEntitySiryou.class, 19, 1, 1);
		par1.addMonster(DqmEntityTororuking.class, 19, 1, 1);
		par1.addMonster(DqmEntityEriminator.class, 19, 1, 1);
		par1.addMonster(DqmEntityDarkdoriado.class, 19, 1, 1);
		par1.addMonster(DqmEntityShadopan.class, 19, 1, 1);
		par1.addMonster(DqmEntityWhitepan2.class, 19, 1, 1);

	}


	public void setTFStrongHoldMonster(TFFeature par1)
	{
		par1.addMonster(DqmEntityMimikku.class, 19, 1, 1);
		par1.addMonster(DqmEntityGorudentotemu.class, 19, 1, 1);
		par1.addMonster(DqmEntitySiryounokisi.class, 19, 1, 1);
		par1.addMonster(DqmEntityAroinpu.class, 19, 1, 1);
		par1.addMonster(DqmEntityMajikaruhatto.class, 19, 1, 1);
		par1.addMonster(DqmEntityMetaruhanta.class, 19, 1, 1);
		par1.addMonster(DqmEntityUmibouzu.class, 19, 1, 1);
		par1.addMonster(DqmEntityDeddopekka.class, 19, 1, 1);
		par1.addMonster(DqmEntityBehomasuraimu.class, 19, 1, 1);
		par1.addMonster(DqmEntityBiggufeisu.class, 19, 1, 1);
		par1.addMonster(DqmEntityGoremu.class, 19, 1, 1);
		par1.addMonster(DqmEntityHotatewarabi.class, 19, 1, 1);
		par1.addMonster(DqmEntityJigokunohasami.class, 19, 1, 1);
		par1.addMonster(DqmEntityMaporena.class, 19, 1, 1);
		par1.addMonster(DqmEntityDarkslime.class, 19, 1, 1);
		par1.addMonster(DqmEntityDqmdragon.class, 19, 1, 1);
		par1.addMonster(DqmEntityGamegon.class, 19, 1, 1);
		par1.addMonster(DqmEntityMagemomonja.class, 19, 1, 1);
		par1.addMonster(DqmEntityPikusi.class, 19, 1, 1);
		par1.addMonster(DqmEntitySuraimuhaitawa.class, 19, 1, 1);
		par1.addMonster(DqmEntityBariidodog.class, 19, 1, 1);
		par1.addMonster(DqmEntityMaounokage.class, 19, 1, 1);
		par1.addMonster(DqmEntityMegazarurokku.class, 19, 1, 1);
		par1.addMonster(DqmEntityBurakkubejita.class, 19, 1, 1);
		par1.addMonster(DqmEntityDragonnaito.class, 19, 1, 1);
		par1.addMonster(DqmEntityBuraddosodo.class, 19, 1, 1);
		par1.addMonster(DqmEntityBarakku.class, 19, 1, 1);
		par1.addMonster(DqmEntityBoureikensi.class, 19, 1, 1);
		par1.addMonster(DqmEntityGanirasu.class, 19, 1, 1);
		par1.addMonster(DqmEntityGoldman.class, 19, 1, 1);
		par1.addMonster(DqmEntityRedsaikuron.class, 19, 1, 1);
		par1.addMonster(DqmEntitySuraimubehomazun.class, 19, 1, 1);
		par1.addMonster(DqmEntityGamegonload.class, 19, 1, 1);
		par1.addMonster(DqmEntityPuyon.class, 19, 1, 1);
		par1.addMonster(DqmEntityBaburuking.class, 19, 1, 1);
		par1.addMonster(DqmEntityDgizumo.class, 19, 1, 1);
		par1.addMonster(DqmEntityDollmaster.class, 19, 1, 1);
		par1.addMonster(DqmEntityKiramasin.class, 19, 1, 1);
		par1.addMonster(DqmEntityKisudragon.class, 19, 1, 1);
		par1.addMonster(DqmEntityKuinsuraimu.class, 19, 1, 1);
		par1.addMonster(DqmEntityAnkokumajin.class, 19, 1, 1);
		par1.addMonster(DqmEntityKemunkurusu.class, 19, 1, 1);
		par1.addMonster(DqmEntityKirakurabu.class, 19, 1, 1);
		par1.addMonster(DqmEntityMagematango.class, 19, 1, 1);
		par1.addMonster(DqmEntityTubokku.class, 19, 1, 1);
		par1.addMonster(DqmEntityMagumaron.class, 19, 1, 1);
		par1.addMonster(DqmEntityPombom.class, 19, 1, 1);
		par1.addMonster(DqmEntityStarkimera.class, 19, 1, 1);
		par1.addMonster(DqmEntitySodofantomu.class, 19, 1, 1);
		par1.addMonster(DqmEntityDragonraida.class, 19, 1, 1);
		par1.addMonster(DqmEntitySirubadebiru.class, 19, 1, 1);
		par1.addMonster(DqmEntitySuraimumadyura.class, 19, 1, 1);
		par1.addMonster(DqmEntitySaikuropusu.class, 19, 1, 1);
		par1.addMonster(DqmEntityStonman.class, 19, 1, 1);
		par1.addMonster(DqmEntityBighanma.class, 19, 1, 1);
		par1.addMonster(DqmEntityBosutororu.class, 19, 1, 1);
		par1.addMonster(DqmEntityDoragonsoruja.class, 19, 1, 1);
		par1.addMonster(DqmEntityFureimu.class, 19, 1, 1);
		par1.addMonster(DqmEntityKedamon.class, 19, 1, 1);
		par1.addMonster(DqmEntityKimendousi.class, 19, 1, 1);
		par1.addMonster(DqmEntityKiraama.class, 19, 1, 1);
		par1.addMonster(DqmEntityKiramasin2.class, 19, 1, 1);
		par1.addMonster(DqmEntityPapettoman.class, 19, 1, 1);
		par1.addMonster(DqmEntitySiryou.class, 19, 1, 1);
		par1.addMonster(DqmEntityTororuking.class, 19, 1, 1);
		par1.addMonster(DqmEntityEriminator.class, 19, 1, 1);
		par1.addMonster(DqmEntityDarkdoriado.class, 19, 1, 1);
		par1.addMonster(DqmEntityShadopan.class, 19, 1, 1);
		par1.addMonster(DqmEntityWhitepan2.class, 19, 1, 1);

		par1.addMonster(DqmEntityGorudensuraimu.class, 7, 1, 1);
		par1.addMonster(DqmEntityPandorabox.class, 7, 1, 1);
		par1.addMonster(DqmEntityBatorurex.class, 7, 1, 1);
		par1.addMonster(DqmEntityAkairai.class, 7, 1, 1);
		par1.addMonster(DqmEntityDasudragon.class, 7, 1, 1);
		par1.addMonster(DqmEntityDesujakkaru.class, 7, 1, 1);
		par1.addMonster(DqmEntityRyuiso.class, 7, 1, 1);
		par1.addMonster(DqmEntityKagenokisi.class, 7, 1, 1);
		par1.addMonster(DqmEntityDakunaito.class, 7, 1, 1);
		par1.addMonster(DqmEntityGamegonrejendo.class, 7, 1, 1);
		par1.addMonster(DqmEntityDenga.class, 7, 1, 1);
		par1.addMonster(DqmEntityDragondarknaito.class, 7, 1, 1);
		par1.addMonster(DqmEntityBiggumoai.class, 7, 1, 1);
		par1.addMonster(DqmEntityGodraida.class, 7, 1, 1);
		par1.addMonster(DqmEntityGigantesu.class, 7, 1, 1);
		par1.addMonster(DqmEntityBassaimasin.class, 7, 1, 1);
		par1.addMonster(DqmEntityBurizado.class, 7, 1, 1);
		par1.addMonster(DqmEntityDarktororu.class, 7, 1, 1);
		par1.addMonster(DqmEntityDesunyago.class, 7, 1, 1);
		par1.addMonster(DqmEntityJigokunoyoroi.class, 7, 1, 1);
		par1.addMonster(DqmEntityManemane.class, 7, 1, 1);
		par1.addMonster(DqmEntityTororubonba.class, 7, 1, 1);
		par1.addMonster(DqmEntityDakuhobitto.class, 7, 1, 1);
		par1.addMonster(DqmEntityDesusutoka.class, 7, 1, 1);
		par1.addMonster(DqmEntityShadopan2.class, 7, 1, 1);
	}

	public void setSpawnListDragon(List par1)
	{
		par1.add(new SpawnListEntry(DqmEntityBatorurex.class, 2, 1, 1));
		par1.add(new SpawnListEntry(DqmEntityDasudragon.class, 2, 1, 1));
		par1.add(new SpawnListEntry(DqmEntityGamegonrejendo.class, 2, 1, 1));
		par1.add(new SpawnListEntry(DqmEntityDragondarknaito.class, 2, 1, 1));
		par1.add(new SpawnListEntry(DqmEntityDqmdragon.class, 10, 1, 1));
		par1.add(new SpawnListEntry(DqmEntityGamegon.class, 10, 1, 1));
		par1.add(new SpawnListEntry(DqmEntityDragonnaito.class, 10, 1, 1));
		par1.add(new SpawnListEntry(DqmEntityGamegonload.class, 10, 1, 1));
		par1.add(new SpawnListEntry(DqmEntityKisudragon.class, 10, 1, 1));
		par1.add(new SpawnListEntry(DqmEntityDragonraida.class, 10, 1, 1));
		par1.add(new SpawnListEntry(DqmEntityDoragonsoruja.class, 10, 1, 1));
		par1.add(new SpawnListEntry(DqmEntityAxedoragon.class, 12, 1, 1));

	}
}
