package dqr;

import java.io.File;

import net.minecraftforge.common.config.Configuration;

public class DQRconfigs2 {

	public static Configuration cfg_mobspawn;

    public static int spawn_resist_overworld_day = 0;
    public static int spawn_resist_overworld_night = 0;
    public static int spawn_resist_nether = 0;
    public static int spawn_resist_end = 0;
    public static int spawn_resist_metal = 0;
    public static int spawn_resist_etc = 1;

    public static int weightSetModeDay = 0;
    public static int weightSetModeNight = 0;
    public static int weightSetModeNether = 0;
    public static int weightSetModeEnd = 0;
    public static int weightSetModeMetal = 0;
    public static int weightSetModeETC = 0;

    public static int groupSpawnWeightDay = 20;
    public static int groupSpawnWeightNight = 20;
    public static int groupSpawnWeightNether = 20;
    public static int groupSpawnWeightEnd = 20;
    public static int groupSpawnWeightMetal = 4;
    public static int groupSpawnWeightETC = 20;

    public static double spawnTimeDelay = 0;
    //
    public int DqmEntityGorotuki = 20;
    public int DqmEntityDokuroarai = 20;
    public int DqmEntityDorozara = 20;
    public int DqmEntityMadohando = 20;
    public int DqmEntityObakeumiusi = 20;
    public int DqmEntitySirudokozou = 20;
    public int DqmEntityUzusioking = 20;
    public int DqmEntityDucksbill = 20;
    public int DqmEntityMomonja = 20;
    public int DqmEntityPurizunyan = 20;
    public int DqmEntitySibirekurage = 20;
    public int DqmEntitySunomon = 20;
    public int DqmEntitySuraimutumuri = 20;
    public int DqmEntityAyasiikage = 20;
    public int DqmEntityBigCrow = 20;
    public int DqmEntityBigguhatto = 20;
    public int DqmEntityBubsura = 20;
    public int DqmEntityDoruido = 20;
    public int DqmEntityDragosuraimu = 20;

    public int DqmEntityEbiruapple = 20;
    public int DqmEntityFaratto = 20;
    public int DqmEntityGaikotu = 20;
    public int DqmEntityGizumoAZ = 20;
    public int DqmEntityGuntaigani = 20;
    public int DqmEntityHitokuisaberu = 20;
    public int DqmEntityIkkakuusagi = 20;
    public int DqmEntityItamogu = 20;
    public int DqmEntityMomon = 20;
    public int DqmEntityOnikozou = 20;
    public int DqmEntityOokiduti = 20;
    public int DqmEntityOonamekuji = 20;
    public int DqmEntityRemonsuraimu = 20;
    public int DqmEntityRippusu = 20;
    public int DqmEntitySabotenboru = 20;
    public int DqmEntitySimasimacat = 20;
    public int DqmEntitySupini = 20;
    public int DqmEntitySura = 20;
    public int DqmEntitySuraimubesu = 20;
    public int DqmEntityTogebouzu = 20;
    public int DqmEntityTukaima = 20;
    public int DqmEntityZinmentyou = 20;
    public int DqmEntityZukkinya = 20;
    public int DqmEntityBurauni = 20;

    public int DqmEntityButisuraimu = 20;
    public int DqmEntityDoronuba = 20;
    public int DqmEntityHoimisura = 20;
    public int DqmEntityKimera = 20;
    public int DqmEntityKirapan = 20;
    public int DqmEntityKirikabuobake = 20;
    public int DqmEntityObakekinoko = 20;
    public int DqmEntityOokutibasi = 20;
    public int DqmEntityOomedama = 20;
    public int DqmEntityPapetkozou = 20;
    public int DqmEntityRiripat = 20;
    public int DqmEntitySukippaa = 20;
    public int DqmEntitySuraimunaito = 20;
    public int DqmEntitySuraimutawa = 20;
    public int DqmEntityWaraibukuro = 20;




    public int DqmEntityBakudaniwa = 20;
    public int DqmEntityBehoimusuraimu = 20;
    public int DqmEntityBeronyaago = 20;
    public int DqmEntityHgizumo = 20;
    public int DqmEntityMeijikimera = 20;
    public int DqmEntityMetaruraida = 20;
    public int DqmEntityOdoruhouseki = 20;
    public int DqmEntitySibiredanbira = 20;
    public int DqmEntityYouganmajin = 20;
    public int DqmEntityAkumanosyo = 20;
    public int DqmEntityArumiraji = 20;
    public int DqmEntityBuraddihando = 20;
    public int DqmEntityFgizumo = 20;
    public int DqmEntityHoroghost = 20;
    public int DqmEntityHyouganmajin = 20;
    public int DqmEntityJeriman = 20;
    public int DqmEntityMarinsuraimu = 20;
    public int DqmEntitySumairurokku = 20;
    public int DqmEntityTahodoraki = 20;
    public int DqmEntityTomosibikozou = 20;
    public int DqmEntityMetaruhantaken = 20;

    public int DqmEntityAxedoragon = 20;
    public int DqmEntityBaburin = 20;
    public int DqmEntityBerobero = 20;
    public int DqmEntityBesuking = 20;
    public int DqmEntityDansunidoru = 20;
    public int DqmEntityDoraki = 20;
    public int DqmEntityDoroningyou = 20;
    public int DqmEntityGaikotukensi = 20;
    public int DqmEntityGappurin = 20;
    public int DqmEntityGenjutusi = 20;
    public int DqmEntityGhost = 20;
    public int DqmEntityHerughost = 20;
    public int DqmEntityKingsura = 20;
    public int DqmEntityKirapan2 = 20;
    public int DqmEntityMapetman = 20;
    public int DqmEntityMeragosuto = 20;
    public int DqmEntityMetoroghost = 20;
    public int DqmEntityMinidemon = 20;
    public int DqmEntityMokomokojuu = 20;
    public int DqmEntityMrippusu = 20;
    public int DqmEntityObakekyandoru = 20;
    public int DqmEntityRaimusuraimu = 20;
    public int DqmEntitySamayoutamasii = 20;
    public int DqmEntitySamayouyoroi = 20;
    public int DqmEntitySkullgaroo = 20;
    public int DqmEntitySumoruguru = 20;
    public int DqmEntitySuraimubogu = 20;
    public int DqmEntitySuraimuburesu = 20;
    public int DqmEntitySyado = 20;
    public int DqmEntityTororu = 20;
    public int DqmEntityTutiwarasi = 20;
    public int DqmEntityAnimaruzonbi = 20;
    public int DqmEntityBakudanbebi = 20;
    public int DqmEntityBebisatan = 20;
    public int DqmEntityBehoimisuraimu = 20;
    public int DqmEntityBuchunpa = 20;
    public int DqmEntityButtizukinya = 20;
    public int DqmEntityDesufuratta = 20;
    public int DqmEntityDokuyazukin = 20;
    public int DqmEntityDorakima = 20;
    public int DqmEntityEnzeruslime = 20;
    public int DqmEntityHitokuiga = 20;
    public int DqmEntityKirasuko = 20;
    public int DqmEntityMatango = 20;
    public int DqmEntityMeijidoraki = 20;
    public int DqmEntityNightwalker = 20;
    public int DqmEntityPinkmomon = 20;
    public int DqmEntitySibireageha = 20;
    public int DqmEntitySupekutetto = 20;
    public int DqmEntitySura2 = 20;
    public int DqmEntityTonburero = 20;
    public int DqmEntityUmiusi = 20;





    public int DqmEntityMetaruburazazu  = 4;
    public int DqmEntityMetasura  = 4;
    public int DqmEntityHagumeta  = 4;
    public int DqmEntityDragometaru  = 4;
    public int DqmEntityMetaking  = 4;
    public int DqmEntityDaiyamondosuraimu  = 4;
    public int DqmEntityPuratinaking  = 4;
    public int DqmEntityHaguremetaruking  = 4;




    public int DqmEntityAnkokumajin = 20;
    public int DqmEntityAroinpu = 20;
    public int DqmEntityBaburuking = 20;
    public int DqmEntityBarakku = 20;
    public int DqmEntityBariidodog = 20;
    public int DqmEntityBehomasuraimu = 20;
    public int DqmEntityBiggufeisu = 20;
    public int DqmEntityBighanma = 20;
    public int DqmEntityBosutororu = 20;
    public int DqmEntityBoureikensi = 20;
    public int DqmEntityBuraddosodo = 20;
    public int DqmEntityBurakkubejita = 20;
    public int DqmEntityDarkslime = 20;
    public int DqmEntityDeddopekka = 20;
    public int DqmEntityDgizumo = 20;
    public int DqmEntityDollmaster = 20;
    public int DqmEntityDoragonsoruja = 20;
    public int DqmEntityDqmdragon = 20;
    public int DqmEntityDragonnaito = 20;
    public int DqmEntityDragonraida = 20;
    public int DqmEntityFureimu = 20;
    public int DqmEntityGamegon = 20;
    public int DqmEntityGamegonload = 20;
    public int DqmEntityGanirasu = 20;
    public int DqmEntityGoldman = 20;
    public int DqmEntityGoremu = 20;
    public int DqmEntityGorudentotemu = 20;
    public int DqmEntityHotatewarabi = 20;
    public int DqmEntityJigokunohasami = 20;
    public int DqmEntityKedamon = 20;
    public int DqmEntityKemunkurusu = 20;
    public int DqmEntityKimendousi = 20;
    public int DqmEntityKiraama = 20;
    public int DqmEntityKirakurabu = 20;
    public int DqmEntityKiramasin = 20;
    public int DqmEntityKiramasin2 = 20;
    public int DqmEntityKisudragon = 20;
    public int DqmEntityKuinsuraimu = 20;
    public int DqmEntityMagematango = 20;
    public int DqmEntityMagemomonja = 20;
    public int DqmEntityMagumaron = 20;
    public int DqmEntityMajikaruhatto = 20;
    public int DqmEntityMaounokage = 20;
    public int DqmEntityMaporena = 20;
    public int DqmEntityMegazarurokku = 20;
    public int DqmEntityMimikku = 20;
    public int DqmEntityPapettoman = 20;
    public int DqmEntityPikusi = 20;
    public int DqmEntityPombom = 20;
    public int DqmEntityPuyon = 20;
    public int DqmEntityRedsaikuron = 20;
    public int DqmEntitySaikuropusu = 20;
    public int DqmEntitySirubadebiru = 20;
    public int DqmEntitySiryou = 20;
    public int DqmEntitySiryounokisi = 20;
    public int DqmEntitySodofantomu = 20;
    public int DqmEntityStarkimera = 20;
    public int DqmEntityStonman = 20;
    public int DqmEntitySuraimubehomazun = 20;
    public int DqmEntitySuraimuhaitawa = 20;
    public int DqmEntitySuraimumadyura = 20;
    public int DqmEntityTororuking = 20;
    //public int //DqmEntityTubokku = 20;

    public int DqmEntityUmibouzu = 20;
    public int DqmEntityEriminator = 20;
    public int DqmEntityDarkdoriado = 20;
    public int DqmEntityShadopan = 20;
    public int DqmEntityWhitepan2 = 20;




    public int DqmEntityAkairai = 20;
    public int DqmEntityBassaimasin = 20;
    public int DqmEntityBatorurex = 20;
    public int DqmEntityBiggumoai = 20;
    public int DqmEntityBurizado = 20;
    public int DqmEntityDakunaito = 20;
    public int DqmEntityDarktororu = 20;

    public int DqmEntityDasudragon = 20;
    public int DqmEntityDenga = 20;
    public int DqmEntityDesujakkaru = 20;
    public int DqmEntityDesunyago = 20;
    public int DqmEntityDragondarknaito = 20;
    public int DqmEntityGamegonrejendo = 20;
    public int DqmEntityGigantesu = 20;
    public int DqmEntityGodraida = 20;
    public int DqmEntityGorudensuraimu = 20;
    public int DqmEntityJigokunoyoroi = 20;
    public int DqmEntityKagenokisi = 20;
    public int DqmEntityManemane = 20;
    public int DqmEntityPandorabox = 20;
    public int DqmEntityRyuiso = 20;
    public int DqmEntityTororubonba = 20;
    public int DqmEntityDesusutoka = 20;
    public int DqmEntityShadopan2 = 20;




    public int DqmEntityPandorakibako = 20;
    public int DqmEntityMimikkukibako = 20;
    public int DqmEntityHitokuibako = 20;
    public int DqmEntityFurosutogizumo = 20;
    public int DqmEntityHiitogizumo = 20;
    public int DqmEntitySuraimuking = 20;
    public int DqmEntityKingbesu = 20;
    public int DqmEntityHitokuikibako = 20;
    public int DqmEntityGizumo = 20;
    public int DqmEntityTubo = 20;

    public DQRconfigs2()
	{
    	cfg_mobspawn = new Configuration(new File(DQR.proxy.getDir(), "config/DQMIIINext/DQMIIINext_MobSpawn.cfg"));

    	this.getConfigMobSpawn(cfg_mobspawn);

    	if(DQR.easyMode == 1 && DQR.conf.cfgEasyMode == 1)
    	{
    		spawnTimeDelay = 48000;
    	}
	}

	public void getConfigMobSpawn(Configuration config)
	{
		config.load();
		config.setCategoryComment("0_Spawn core settings", "this setting is mob spawn core setting");
		spawnTimeDelay = config.get("0_Spawn core settings","1.Safety time until first spawn", spawnTimeDelay).getDouble();

		config.setCategoryComment("1_Spawn resister", "this setting is mob spawn regist resister\nspawn resist (0:disable  1:enable)");
		spawn_resist_overworld_day = config.get("1_Spawn resister","1.Overworld(Day)", spawn_resist_overworld_day).getInt();
		spawn_resist_overworld_night = config.get("1_Spawn resister","2.Overworld(Night)", spawn_resist_overworld_night).getInt();
		spawn_resist_nether = config.get("1_Spawn resister","3.Nether", spawn_resist_nether).getInt();
		spawn_resist_end = config.get("1_Spawn resister","4.End", spawn_resist_end).getInt();
		spawn_resist_metal = config.get("1_Spawn resister","5.Metal", spawn_resist_metal).getInt();
		spawn_resist_etc = config.get("1_Spawn resister","6.ETC", spawn_resist_etc).getInt();


		config.setCategoryComment("2_Spawn weight set mode", "this setting is mob spawn weight setting mode\n0:default 1:group set 2:individual set");
		weightSetModeDay = config.get("2_Spawn weight set mode","1.Overworld(Day)", weightSetModeDay).getInt();
		weightSetModeNight = config.get("2_Spawn weight set mode","2.Overworld(Night)", weightSetModeNight).getInt();
		weightSetModeNether = config.get("2_Spawn weight set mode","3.Nether", weightSetModeNether).getInt();
		weightSetModeEnd = config.get("2_Spawn weight set mode","4.End", weightSetModeEnd).getInt();
		weightSetModeMetal = config.get("2_Spawn weight set mode","5.Metal", weightSetModeMetal).getInt();
		weightSetModeETC = config.get("2_Spawn weight set mode","6.ETC", weightSetModeETC).getInt();

		config.setCategoryComment("3_Spawn weight set mob group", "this setting is mob spawn weight set for group set mode.\nspawn rate : Low 1 <-  20(Middle) -> High");
	    groupSpawnWeightDay = config.get("3_Spawn weight set mob group","1.Overworld(Day)", groupSpawnWeightDay).getInt();
	    groupSpawnWeightNight = config.get("3_Spawn weight set mob group","2.Overworld(Night)", groupSpawnWeightNight).getInt();
	    groupSpawnWeightNether = config.get("3_Spawn weight set mob group","3.Nether", groupSpawnWeightNether).getInt();
	    groupSpawnWeightEnd = config.get("3_Spawn weight set mob group","4.End", groupSpawnWeightEnd).getInt();
	    groupSpawnWeightMetal = config.get("3_Spawn weight set mob group","5.Metal", groupSpawnWeightMetal).getInt();
	    groupSpawnWeightETC = config.get("3_Spawn weight set mob group","6.ETC", groupSpawnWeightETC).getInt();

/*
		config.setCategoryComment("4_Spawn weight set individual(Day)", "this setting is mob spawn weight set for individual set mode");
		DqmEntityGorotuki = config.get("4_Spawn weight set individual(Day)","Gorotuki", DqmEntityGorotuki, "spawn rate : Low 1 <-  20(Middle) -> High").getInt();
		DqmEntityDokuroarai = config.get("4_Spawn weight set individual(Day)","Dokuroarai", DqmEntityDokuroarai, "spawn rate : Low 1 <-  20(Middle) -> High").getInt();
		DqmEntityDorozara = config.get("4_Spawn weight set individual(Day)","Dorozara", DqmEntityDorozara, "spawn rate : Low 1 <-  20(Middle) -> High").getInt();
		DqmEntityMadohando = config.get("4_Spawn weight set individual(Day)","Madohando", DqmEntityMadohando, "spawn rate : Low 1 <-  20(Middle) -> High").getInt();
		DqmEntityObakeumiusi = config.get("4_Spawn weight set individual(Day)","Obakeumiusi", DqmEntityObakeumiusi, "spawn rate : Low 1 <-  20(Middle) -> High").getInt();
		DqmEntitySirudokozou = config.get("4_Spawn weight set individual(Day)","Sirudokozou", DqmEntitySirudokozou, "spawn rate : Low 1 <-  20(Middle) -> High").getInt();
		DqmEntityUzusioking = config.get("4_Spawn weight set individual(Day)","Uzusioking", DqmEntityUzusioking, "spawn rate : Low 1 <-  20(Middle) -> High").getInt();
		DqmEntityDucksbill = config.get("4_Spawn weight set individual(Day)","Ducksbill", DqmEntityDucksbill, "spawn rate : Low 1 <-  20(Middle) -> High").getInt();
		DqmEntityMomonja = config.get("4_Spawn weight set individual(Day)","Momonja", DqmEntityMomonja, "spawn rate : Low 1 <-  20(Middle) -> High").getInt();
		DqmEntityPurizunyan = config.get("4_Spawn weight set individual(Day)","Purizunyan", DqmEntityPurizunyan, "spawn rate : Low 1 <-  20(Middle) -> High").getInt();
		DqmEntitySibirekurage = config.get("4_Spawn weight set individual(Day)","Sibirekurage", DqmEntitySibirekurage, "spawn rate : Low 1 <-  20(Middle) -> High").getInt();
		DqmEntitySunomon = config.get("4_Spawn weight set individual(Day)","Sunomon", DqmEntitySunomon, "spawn rate : Low 1 <-  20(Middle) -> High").getInt();
		DqmEntitySuraimutumuri = config.get("4_Spawn weight set individual(Day)","Suraimutumuri", DqmEntitySuraimutumuri, "spawn rate : Low 1 <-  20(Middle) -> High").getInt();
		DqmEntityAyasiikage = config.get("4_Spawn weight set individual(Day)","Ayasiikage", DqmEntityAyasiikage, "spawn rate : Low 1 <-  20(Middle) -> High").getInt();
		DqmEntityBigCrow = config.get("4_Spawn weight set individual(Day)","BigCrow", DqmEntityBigCrow, "spawn rate : Low 1 <-  20(Middle) -> High").getInt();
		DqmEntityBigguhatto = config.get("4_Spawn weight set individual(Day)","Bigguhatto", DqmEntityBigguhatto, "spawn rate : Low 1 <-  20(Middle) -> High").getInt();
		DqmEntityBubsura = config.get("4_Spawn weight set individual(Day)","Bubsura", DqmEntityBubsura, "spawn rate : Low 1 <-  20(Middle) -> High").getInt();
		DqmEntityDoruido = config.get("4_Spawn weight set individual(Day)","Doruido", DqmEntityDoruido, "spawn rate : Low 1 <-  20(Middle) -> High").getInt();
		DqmEntityDragosuraimu = config.get("4_Spawn weight set individual(Day)","Dragosuraimu", DqmEntityDragosuraimu, "spawn rate : Low 1 <-  20(Middle) -> High").getInt();

		DqmEntityEbiruapple = config.get("4_Spawn weight set individual(Day)","Ebiruapple", DqmEntityEbiruapple, "spawn rate : Low 1 <-  20(Middle) -> High").getInt();
		DqmEntityFaratto = config.get("4_Spawn weight set individual(Day)","Faratto", DqmEntityFaratto, "spawn rate : Low 1 <-  20(Middle) -> High").getInt();
		DqmEntityGaikotu = config.get("4_Spawn weight set individual(Day)","Gaikotu", DqmEntityGaikotu, "spawn rate : Low 1 <-  20(Middle) -> High").getInt();
		//DqmEntityGizumo = config.get("4_Spawn weight set individual(Day)","//Gizumo", //DqmEntityGizumo, "spawn rate : Low 1 <-  20(Middle) -> High").getInt();
		DqmEntityGizumoAZ = config.get("4_Spawn weight set individual(Day)","GizumoAZ", DqmEntityGizumoAZ, "spawn rate : Low 1 <-  20(Middle) -> High").getInt();
		DqmEntityGuntaigani = config.get("4_Spawn weight set individual(Day)","Guntaigani", DqmEntityGuntaigani, "spawn rate : Low 1 <-  20(Middle) -> High").getInt();
		//DqmEntityHitokuikibako = config.get("4_Spawn weight set individual(Day)","//Hitokuikibako", //DqmEntityHitokuikibako, "spawn rate : Low 1 <-  20(Middle) -> High").getInt();
		DqmEntityHitokuisaberu = config.get("4_Spawn weight set individual(Day)","Hitokuisaberu", DqmEntityHitokuisaberu, "spawn rate : Low 1 <-  20(Middle) -> High").getInt();
		DqmEntityIkkakuusagi = config.get("4_Spawn weight set individual(Day)","Ikkakuusagi", DqmEntityIkkakuusagi, "spawn rate : Low 1 <-  20(Middle) -> High").getInt();
		DqmEntityItamogu = config.get("4_Spawn weight set individual(Day)","Itamogu", DqmEntityItamogu, "spawn rate : Low 1 <-  20(Middle) -> High").getInt();
		//DqmEntityKingbesu = config.get("4_Spawn weight set individual(Day)","//Kingbesu", //DqmEntityKingbesu, "spawn rate : Low 1 <-  20(Middle) -> High").getInt();
		DqmEntityMomon = config.get("4_Spawn weight set individual(Day)","Momon", DqmEntityMomon, "spawn rate : Low 1 <-  20(Middle) -> High").getInt();
		DqmEntityOnikozou = config.get("4_Spawn weight set individual(Day)","Onikozou", DqmEntityOnikozou, "spawn rate : Low 1 <-  20(Middle) -> High").getInt();
		DqmEntityOokiduti = config.get("4_Spawn weight set individual(Day)","Ookiduti", DqmEntityOokiduti, "spawn rate : Low 1 <-  20(Middle) -> High").getInt();
		DqmEntityOonamekuji = config.get("4_Spawn weight set individual(Day)","Oonamekuji", DqmEntityOonamekuji, "spawn rate : Low 1 <-  20(Middle) -> High").getInt();
		DqmEntityRemonsuraimu = config.get("4_Spawn weight set individual(Day)","Remonsuraimu", DqmEntityRemonsuraimu, "spawn rate : Low 1 <-  20(Middle) -> High").getInt();
		DqmEntityRippusu = config.get("4_Spawn weight set individual(Day)","Rippusu", DqmEntityRippusu, "spawn rate : Low 1 <-  20(Middle) -> High").getInt();
		DqmEntitySabotenboru = config.get("4_Spawn weight set individual(Day)","Sabotenboru", DqmEntitySabotenboru, "spawn rate : Low 1 <-  20(Middle) -> High").getInt();
		DqmEntitySimasimacat = config.get("4_Spawn weight set individual(Day)","Simasimacat", DqmEntitySimasimacat, "spawn rate : Low 1 <-  20(Middle) -> High").getInt();
		DqmEntitySupini = config.get("4_Spawn weight set individual(Day)","Supini", DqmEntitySupini, "spawn rate : Low 1 <-  20(Middle) -> High").getInt();
		DqmEntitySura = config.get("4_Spawn weight set individual(Day)","Sura", DqmEntitySura, "spawn rate : Low 1 <-  20(Middle) -> High").getInt();
		DqmEntitySuraimubesu = config.get("4_Spawn weight set individual(Day)","Suraimubesu", DqmEntitySuraimubesu, "spawn rate : Low 1 <-  20(Middle) -> High").getInt();
		DqmEntityTogebouzu = config.get("4_Spawn weight set individual(Day)","Togebouzu", DqmEntityTogebouzu, "spawn rate : Low 1 <-  20(Middle) -> High").getInt();
		//DqmEntityTubo = config.get("4_Spawn weight set individual(Day)","//Tubo", //DqmEntityTubo, "spawn rate : Low 1 <-  20(Middle) -> High").getInt();
		DqmEntityTukaima = config.get("4_Spawn weight set individual(Day)","Tukaima", DqmEntityTukaima, "spawn rate : Low 1 <-  20(Middle) -> High").getInt();
		DqmEntityZinmentyou = config.get("4_Spawn weight set individual(Day)","Zinmentyou", DqmEntityZinmentyou, "spawn rate : Low 1 <-  20(Middle) -> High").getInt();
		DqmEntityZukkinya = config.get("4_Spawn weight set individual(Day)","Zukkinya", DqmEntityZukkinya, "spawn rate : Low 1 <-  20(Middle) -> High").getInt();
		DqmEntityBurauni = config.get("4_Spawn weight set individual(Day)","Burauni", DqmEntityBurauni, "spawn rate : Low 1 <-  20(Middle) -> High").getInt();

		DqmEntityButisuraimu = config.get("4_Spawn weight set individual(Day)","Butisuraimu", DqmEntityButisuraimu, "spawn rate : Low 1 <-  20(Middle) -> High").getInt();
		DqmEntityDoronuba = config.get("4_Spawn weight set individual(Day)","Doronuba", DqmEntityDoronuba, "spawn rate : Low 1 <-  20(Middle) -> High").getInt();
		DqmEntityHoimisura = config.get("4_Spawn weight set individual(Day)","Hoimisura", DqmEntityHoimisura, "spawn rate : Low 1 <-  20(Middle) -> High").getInt();
		DqmEntityKimera = config.get("4_Spawn weight set individual(Day)","Kimera", DqmEntityKimera, "spawn rate : Low 1 <-  20(Middle) -> High").getInt();
		DqmEntityKirapan = config.get("4_Spawn weight set individual(Day)","Kirapan", DqmEntityKirapan, "spawn rate : Low 1 <-  20(Middle) -> High").getInt();
		DqmEntityKirikabuobake = config.get("4_Spawn weight set individual(Day)","Kirikabuobake", DqmEntityKirikabuobake, "spawn rate : Low 1 <-  20(Middle) -> High").getInt();
		DqmEntityObakekinoko = config.get("4_Spawn weight set individual(Day)","Obakekinoko", DqmEntityObakekinoko, "spawn rate : Low 1 <-  20(Middle) -> High").getInt();
		DqmEntityOokutibasi = config.get("4_Spawn weight set individual(Day)","Ookutibasi", DqmEntityOokutibasi, "spawn rate : Low 1 <-  20(Middle) -> High").getInt();
		DqmEntityOomedama = config.get("4_Spawn weight set individual(Day)","Oomedama", DqmEntityOomedama, "spawn rate : Low 1 <-  20(Middle) -> High").getInt();
		DqmEntityPapetkozou = config.get("4_Spawn weight set individual(Day)","Papetkozou", DqmEntityPapetkozou, "spawn rate : Low 1 <-  20(Middle) -> High").getInt();
		DqmEntityRiripat = config.get("4_Spawn weight set individual(Day)","Riripat", DqmEntityRiripat, "spawn rate : Low 1 <-  20(Middle) -> High").getInt();
		DqmEntitySukippaa = config.get("4_Spawn weight set individual(Day)","Sukippaa", DqmEntitySukippaa, "spawn rate : Low 1 <-  20(Middle) -> High").getInt();
		//DqmEntitySuraimuking = config.get("4_Spawn weight set individual(Day)","//Suraimuking", //DqmEntitySuraimuking, "spawn rate : Low 1 <-  20(Middle) -> High").getInt();
		DqmEntitySuraimunaito = config.get("4_Spawn weight set individual(Day)","Suraimunaito", DqmEntitySuraimunaito, "spawn rate : Low 1 <-  20(Middle) -> High").getInt();
		DqmEntitySuraimutawa = config.get("4_Spawn weight set individual(Day)","Suraimutawa", DqmEntitySuraimutawa, "spawn rate : Low 1 <-  20(Middle) -> High").getInt();
		DqmEntityWaraibukuro = config.get("4_Spawn weight set individual(Day)","Waraibukuro", DqmEntityWaraibukuro, "spawn rate : Low 1 <-  20(Middle) -> High").getInt();

		config.setCategoryComment("5_Spawn weight set individual(Night)", "this setting is mob spawn weight set for individual set mode");
		DqmEntityBakudaniwa = config.get("5_Spawn weight set individual(Night)","Bakudaniwa", DqmEntityBakudaniwa, "spawn rate : Low 1 <-  20(Middle) -> High").getInt();
		DqmEntityBehoimusuraimu = config.get("5_Spawn weight set individual(Night)","Behoimusuraimu", DqmEntityBehoimusuraimu, "spawn rate : Low 1 <-  20(Middle) -> High").getInt();
		DqmEntityBeronyaago = config.get("5_Spawn weight set individual(Night)","Beronyaago", DqmEntityBeronyaago, "spawn rate : Low 1 <-  20(Middle) -> High").getInt();
		DqmEntityHgizumo = config.get("5_Spawn weight set individual(Night)","Hgizumo", DqmEntityHgizumo, "spawn rate : Low 1 <-  20(Middle) -> High").getInt();
		//DqmEntityHiitogizumo = config.get("5_Spawn weight set individual(Night)","//Hiitogizumo", //DqmEntityHiitogizumo, "spawn rate : Low 1 <-  20(Middle) -> High").getInt();
		DqmEntityMeijikimera = config.get("5_Spawn weight set individual(Night)","Meijikimera", DqmEntityMeijikimera, "spawn rate : Low 1 <-  20(Middle) -> High").getInt();
		DqmEntityMetaruraida = config.get("5_Spawn weight set individual(Night)","Metaruraida", DqmEntityMetaruraida, "spawn rate : Low 1 <-  20(Middle) -> High").getInt();
		DqmEntityOdoruhouseki = config.get("5_Spawn weight set individual(Night)","Odoruhouseki", DqmEntityOdoruhouseki, "spawn rate : Low 1 <-  20(Middle) -> High").getInt();
		DqmEntitySibiredanbira = config.get("5_Spawn weight set individual(Night)","Sibiredanbira", DqmEntitySibiredanbira, "spawn rate : Low 1 <-  20(Middle) -> High").getInt();
		DqmEntityYouganmajin = config.get("5_Spawn weight set individual(Night)","Youganmajin", DqmEntityYouganmajin, "spawn rate : Low 1 <-  20(Middle) -> High").getInt();
		DqmEntityAkumanosyo = config.get("5_Spawn weight set individual(Night)","Akumanosyo", DqmEntityAkumanosyo, "spawn rate : Low 1 <-  20(Middle) -> High").getInt();
		DqmEntityArumiraji = config.get("5_Spawn weight set individual(Night)","Arumiraji", DqmEntityArumiraji, "spawn rate : Low 1 <-  20(Middle) -> High").getInt();
		DqmEntityBuraddihando = config.get("5_Spawn weight set individual(Night)","Buraddihando", DqmEntityBuraddihando, "spawn rate : Low 1 <-  20(Middle) -> High").getInt();
		DqmEntityFgizumo = config.get("5_Spawn weight set individual(Night)","Fgizumo", DqmEntityFgizumo, "spawn rate : Low 1 <-  20(Middle) -> High").getInt();
		//DqmEntityFurosutogizumo = config.get("5_Spawn weight set individual(Night)","//Furosutogizumo", //DqmEntityFurosutogizumo, "spawn rate : Low 1 <-  20(Middle) -> High").getInt();
		DqmEntityHoroghost = config.get("5_Spawn weight set individual(Night)","Horoghost", DqmEntityHoroghost, "spawn rate : Low 1 <-  20(Middle) -> High").getInt();
		DqmEntityHyouganmajin = config.get("5_Spawn weight set individual(Night)","Hyouganmajin", DqmEntityHyouganmajin, "spawn rate : Low 1 <-  20(Middle) -> High").getInt();
		DqmEntityJeriman = config.get("5_Spawn weight set individual(Night)","Jeriman", DqmEntityJeriman, "spawn rate : Low 1 <-  20(Middle) -> High").getInt();
		DqmEntityMarinsuraimu = config.get("5_Spawn weight set individual(Night)","Marinsuraimu", DqmEntityMarinsuraimu, "spawn rate : Low 1 <-  20(Middle) -> High").getInt();
		DqmEntitySumairurokku = config.get("5_Spawn weight set individual(Night)","Sumairurokku", DqmEntitySumairurokku, "spawn rate : Low 1 <-  20(Middle) -> High").getInt();
		DqmEntityTahodoraki = config.get("5_Spawn weight set individual(Night)","Tahodoraki", DqmEntityTahodoraki, "spawn rate : Low 1 <-  20(Middle) -> High").getInt();
		DqmEntityTomosibikozou = config.get("5_Spawn weight set individual(Night)","Tomosibikozou", DqmEntityTomosibikozou, "spawn rate : Low 1 <-  20(Middle) -> High").getInt();
		DqmEntityMetaruhantaken = config.get("5_Spawn weight set individual(Night)","Metaruhantaken", DqmEntityMetaruhantaken, "spawn rate : Low 1 <-  20(Middle) -> High").getInt();
		//DqmEntityAkumanotubo = config.get("5_Spawn weight set individual(Night)","//Akumanotubo", //DqmEntityAkumanotubo, "spawn rate : Low 1 <-  20(Middle) -> High").getInt();

		DqmEntityAxedoragon = config.get("5_Spawn weight set individual(Night)","Axedoragon", DqmEntityAxedoragon, "spawn rate : Low 1 <-  20(Middle) -> High").getInt();
		DqmEntityBaburin = config.get("5_Spawn weight set individual(Night)","Baburin", DqmEntityBaburin, "spawn rate : Low 1 <-  20(Middle) -> High").getInt();
		DqmEntityBerobero = config.get("5_Spawn weight set individual(Night)","Berobero", DqmEntityBerobero, "spawn rate : Low 1 <-  20(Middle) -> High").getInt();
		DqmEntityBesuking = config.get("5_Spawn weight set individual(Night)","Besuking", DqmEntityBesuking, "spawn rate : Low 1 <-  20(Middle) -> High").getInt();
		DqmEntityDansunidoru = config.get("5_Spawn weight set individual(Night)","Dansunidoru", DqmEntityDansunidoru, "spawn rate : Low 1 <-  20(Middle) -> High").getInt();
		DqmEntityDoraki = config.get("5_Spawn weight set individual(Night)","Doraki", DqmEntityDoraki, "spawn rate : Low 1 <-  20(Middle) -> High").getInt();
		DqmEntityDoroningyou = config.get("5_Spawn weight set individual(Night)","Doroningyou", DqmEntityDoroningyou, "spawn rate : Low 1 <-  20(Middle) -> High").getInt();
		DqmEntityGaikotukensi = config.get("5_Spawn weight set individual(Night)","Gaikotukensi", DqmEntityGaikotukensi, "spawn rate : Low 1 <-  20(Middle) -> High").getInt();
		DqmEntityGappurin = config.get("5_Spawn weight set individual(Night)","Gappurin", DqmEntityGappurin, "spawn rate : Low 1 <-  20(Middle) -> High").getInt();
		DqmEntityGenjutusi = config.get("5_Spawn weight set individual(Night)","Genjutusi", DqmEntityGenjutusi, "spawn rate : Low 1 <-  20(Middle) -> High").getInt();
		DqmEntityGhost = config.get("5_Spawn weight set individual(Night)","Ghost", DqmEntityGhost, "spawn rate : Low 1 <-  20(Middle) -> High").getInt();
		DqmEntityHerughost = config.get("5_Spawn weight set individual(Night)","Herughost", DqmEntityHerughost, "spawn rate : Low 1 <-  20(Middle) -> High").getInt();
		DqmEntityHitokuibako = config.get("5_Spawn weight set individual(Night)","Hitokuibako", DqmEntityHitokuibako, "spawn rate : Low 1 <-  20(Middle) -> High").getInt();
		DqmEntityKingsura = config.get("5_Spawn weight set individual(Night)","Kingsura", DqmEntityKingsura, "spawn rate : Low 1 <-  20(Middle) -> High").getInt();
		DqmEntityKirapan2 = config.get("5_Spawn weight set individual(Night)","Kirapan2", DqmEntityKirapan2, "spawn rate : Low 1 <-  20(Middle) -> High").getInt();
		DqmEntityMapetman = config.get("5_Spawn weight set individual(Night)","Mapetman", DqmEntityMapetman, "spawn rate : Low 1 <-  20(Middle) -> High").getInt();
		DqmEntityMeragosuto = config.get("5_Spawn weight set individual(Night)","Meragosuto", DqmEntityMeragosuto, "spawn rate : Low 1 <-  20(Middle) -> High").getInt();
		DqmEntityMetoroghost = config.get("5_Spawn weight set individual(Night)","Metoroghost", DqmEntityMetoroghost, "spawn rate : Low 1 <-  20(Middle) -> High").getInt();
		//DqmEntityMimikkukibako = config.get("5_Spawn weight set individual(Night)","//Mimikkukibako", //DqmEntityMimikkukibako, "spawn rate : Low 1 <-  20(Middle) -> High").getInt();
		DqmEntityMinidemon = config.get("5_Spawn weight set individual(Night)","Minidemon", DqmEntityMinidemon, "spawn rate : Low 1 <-  20(Middle) -> High").getInt();
		DqmEntityMokomokojuu = config.get("5_Spawn weight set individual(Night)","Mokomokojuu", DqmEntityMokomokojuu, "spawn rate : Low 1 <-  20(Middle) -> High").getInt();
		DqmEntityMrippusu = config.get("5_Spawn weight set individual(Night)","Mrippusu", DqmEntityMrippusu, "spawn rate : Low 1 <-  20(Middle) -> High").getInt();
		DqmEntityObakekyandoru = config.get("5_Spawn weight set individual(Night)","Obakekyandoru", DqmEntityObakekyandoru, "spawn rate : Low 1 <-  20(Middle) -> High").getInt();
		DqmEntityRaimusuraimu = config.get("5_Spawn weight set individual(Night)","Raimusuraimu", DqmEntityRaimusuraimu, "spawn rate : Low 1 <-  20(Middle) -> High").getInt();
		DqmEntitySamayoutamasii = config.get("5_Spawn weight set individual(Night)","Samayoutamasii", DqmEntitySamayoutamasii, "spawn rate : Low 1 <-  20(Middle) -> High").getInt();
		DqmEntitySamayouyoroi = config.get("5_Spawn weight set individual(Night)","Samayouyoroi", DqmEntitySamayouyoroi, "spawn rate : Low 1 <-  20(Middle) -> High").getInt();
		DqmEntitySkullgaroo = config.get("5_Spawn weight set individual(Night)","Skullgaroo", DqmEntitySkullgaroo, "spawn rate : Low 1 <-  20(Middle) -> High").getInt();
		DqmEntitySumoruguru = config.get("5_Spawn weight set individual(Night)","Sumoruguru", DqmEntitySumoruguru, "spawn rate : Low 1 <-  20(Middle) -> High").getInt();
		DqmEntitySuraimubogu = config.get("5_Spawn weight set individual(Night)","Suraimubogu", DqmEntitySuraimubogu, "spawn rate : Low 1 <-  20(Middle) -> High").getInt();
		DqmEntitySuraimuburesu = config.get("5_Spawn weight set individual(Night)","Suraimuburesu", DqmEntitySuraimuburesu, "spawn rate : Low 1 <-  20(Middle) -> High").getInt();
		DqmEntitySyado = config.get("5_Spawn weight set individual(Night)","Syado", DqmEntitySyado, "spawn rate : Low 1 <-  20(Middle) -> High").getInt();
		DqmEntityTororu = config.get("5_Spawn weight set individual(Night)","Tororu", DqmEntityTororu, "spawn rate : Low 1 <-  20(Middle) -> High").getInt();
		DqmEntityTutiwarasi = config.get("5_Spawn weight set individual(Night)","Tutiwarasi", DqmEntityTutiwarasi, "spawn rate : Low 1 <-  20(Middle) -> High").getInt();
		DqmEntityAnimaruzonbi = config.get("5_Spawn weight set individual(Night)","Animaruzonbi", DqmEntityAnimaruzonbi, "spawn rate : Low 1 <-  20(Middle) -> High").getInt();
		DqmEntityBakudanbebi = config.get("5_Spawn weight set individual(Night)","Bakudanbebi", DqmEntityBakudanbebi, "spawn rate : Low 1 <-  20(Middle) -> High").getInt();
		DqmEntityBebisatan = config.get("5_Spawn weight set individual(Night)","Bebisatan", DqmEntityBebisatan, "spawn rate : Low 1 <-  20(Middle) -> High").getInt();
		DqmEntityBehoimisuraimu = config.get("5_Spawn weight set individual(Night)","Behoimisuraimu", DqmEntityBehoimisuraimu, "spawn rate : Low 1 <-  20(Middle) -> High").getInt();
		DqmEntityBuchunpa = config.get("5_Spawn weight set individual(Night)","Buchunpa", DqmEntityBuchunpa, "spawn rate : Low 1 <-  20(Middle) -> High").getInt();
		DqmEntityButtizukinya = config.get("5_Spawn weight set individual(Night)","Buttizukinya", DqmEntityButtizukinya, "spawn rate : Low 1 <-  20(Middle) -> High").getInt();
		DqmEntityDesufuratta = config.get("5_Spawn weight set individual(Night)","Desufuratta", DqmEntityDesufuratta, "spawn rate : Low 1 <-  20(Middle) -> High").getInt();
		DqmEntityDokuyazukin = config.get("5_Spawn weight set individual(Night)","Dokuyazukin", DqmEntityDokuyazukin, "spawn rate : Low 1 <-  20(Middle) -> High").getInt();
		DqmEntityDorakima = config.get("5_Spawn weight set individual(Night)","Dorakima", DqmEntityDorakima, "spawn rate : Low 1 <-  20(Middle) -> High").getInt();
		DqmEntityEnzeruslime = config.get("5_Spawn weight set individual(Night)","Enzeruslime", DqmEntityEnzeruslime, "spawn rate : Low 1 <-  20(Middle) -> High").getInt();
		DqmEntityHitokuiga = config.get("5_Spawn weight set individual(Night)","Hitokuiga", DqmEntityHitokuiga, "spawn rate : Low 1 <-  20(Middle) -> High").getInt();
		DqmEntityKirasuko = config.get("5_Spawn weight set individual(Night)","Kirasuko", DqmEntityKirasuko, "spawn rate : Low 1 <-  20(Middle) -> High").getInt();
		DqmEntityMatango = config.get("5_Spawn weight set individual(Night)","Matango", DqmEntityMatango, "spawn rate : Low 1 <-  20(Middle) -> High").getInt();
		DqmEntityMeijidoraki = config.get("5_Spawn weight set individual(Night)","Meijidoraki", DqmEntityMeijidoraki, "spawn rate : Low 1 <-  20(Middle) -> High").getInt();
		DqmEntityNightwalker = config.get("5_Spawn weight set individual(Night)","Nightwalker", DqmEntityNightwalker, "spawn rate : Low 1 <-  20(Middle) -> High").getInt();
		DqmEntityPinkmomon = config.get("5_Spawn weight set individual(Night)","Pinkmomon", DqmEntityPinkmomon, "spawn rate : Low 1 <-  20(Middle) -> High").getInt();
		DqmEntitySibireageha = config.get("5_Spawn weight set individual(Night)","Sibireageha", DqmEntitySibireageha, "spawn rate : Low 1 <-  20(Middle) -> High").getInt();
		DqmEntitySupekutetto = config.get("5_Spawn weight set individual(Night)","Supekutetto", DqmEntitySupekutetto, "spawn rate : Low 1 <-  20(Middle) -> High").getInt();
		DqmEntitySura2 = config.get("5_Spawn weight set individual(Night)","Sura2", DqmEntitySura2, "spawn rate : Low 1 <-  20(Middle) -> High").getInt();
		DqmEntityTonburero = config.get("5_Spawn weight set individual(Night)","Tonburero", DqmEntityTonburero, "spawn rate : Low 1 <-  20(Middle) -> High").getInt();
		DqmEntityUmiusi = config.get("5_Spawn weight set individual(Night)","Umiusi", DqmEntityUmiusi, "spawn rate : Low 1 <-  20(Middle) -> High").getInt();


		config.setCategoryComment("6_Spawn weight set individual(Nether)", "this setting is mob spawn weight set for individual set mode");
		DqmEntityAnkokumajin = config.get("6_Spawn weight set individual(Nether)","Ankokumajin", DqmEntityAnkokumajin, "spawn rate : Low 1 <-  20(Middle) -> High").getInt();
		DqmEntityAroinpu = config.get("6_Spawn weight set individual(Nether)","Aroinpu", DqmEntityAroinpu, "spawn rate : Low 1 <-  20(Middle) -> High").getInt();
		DqmEntityBaburuking = config.get("6_Spawn weight set individual(Nether)","Baburuking", DqmEntityBaburuking, "spawn rate : Low 1 <-  20(Middle) -> High").getInt();
		DqmEntityBarakku = config.get("6_Spawn weight set individual(Nether)","Barakku", DqmEntityBarakku, "spawn rate : Low 1 <-  20(Middle) -> High").getInt();
		DqmEntityBariidodog = config.get("6_Spawn weight set individual(Nether)","Bariidodog", DqmEntityBariidodog, "spawn rate : Low 1 <-  20(Middle) -> High").getInt();
		DqmEntityBehomasuraimu = config.get("6_Spawn weight set individual(Nether)","Behomasuraimu", DqmEntityBehomasuraimu, "spawn rate : Low 1 <-  20(Middle) -> High").getInt();
		DqmEntityBiggufeisu = config.get("6_Spawn weight set individual(Nether)","Biggufeisu", DqmEntityBiggufeisu, "spawn rate : Low 1 <-  20(Middle) -> High").getInt();
		DqmEntityBighanma = config.get("6_Spawn weight set individual(Nether)","Bighanma", DqmEntityBighanma, "spawn rate : Low 1 <-  20(Middle) -> High").getInt();
		DqmEntityBosutororu = config.get("6_Spawn weight set individual(Nether)","Bosutororu", DqmEntityBosutororu, "spawn rate : Low 1 <-  20(Middle) -> High").getInt();
		DqmEntityBoureikensi = config.get("6_Spawn weight set individual(Nether)","Boureikensi", DqmEntityBoureikensi, "spawn rate : Low 1 <-  20(Middle) -> High").getInt();
		DqmEntityBuraddosodo = config.get("6_Spawn weight set individual(Nether)","Buraddosodo", DqmEntityBuraddosodo, "spawn rate : Low 1 <-  20(Middle) -> High").getInt();
		DqmEntityBurakkubejita = config.get("6_Spawn weight set individual(Nether)","Burakkubejita", DqmEntityBurakkubejita, "spawn rate : Low 1 <-  20(Middle) -> High").getInt();
		DqmEntityDarkslime = config.get("6_Spawn weight set individual(Nether)","Darkslime", DqmEntityDarkslime, "spawn rate : Low 1 <-  20(Middle) -> High").getInt();
		DqmEntityDeddopekka = config.get("6_Spawn weight set individual(Nether)","Deddopekka", DqmEntityDeddopekka, "spawn rate : Low 1 <-  20(Middle) -> High").getInt();
		DqmEntityDgizumo = config.get("6_Spawn weight set individual(Nether)","Dgizumo", DqmEntityDgizumo, "spawn rate : Low 1 <-  20(Middle) -> High").getInt();
		DqmEntityDollmaster = config.get("6_Spawn weight set individual(Nether)","Dollmaster", DqmEntityDollmaster, "spawn rate : Low 1 <-  20(Middle) -> High").getInt();
		DqmEntityDoragonsoruja = config.get("6_Spawn weight set individual(Nether)","Doragonsoruja", DqmEntityDoragonsoruja, "spawn rate : Low 1 <-  20(Middle) -> High").getInt();
		DqmEntityDqmdragon = config.get("6_Spawn weight set individual(Nether)","Dqmdragon", DqmEntityDqmdragon, "spawn rate : Low 1 <-  20(Middle) -> High").getInt();
		DqmEntityDragonnaito = config.get("6_Spawn weight set individual(Nether)","Dragonnaito", DqmEntityDragonnaito, "spawn rate : Low 1 <-  20(Middle) -> High").getInt();
		DqmEntityDragonraida = config.get("6_Spawn weight set individual(Nether)","Dragonraida", DqmEntityDragonraida, "spawn rate : Low 1 <-  20(Middle) -> High").getInt();
		DqmEntityFureimu = config.get("6_Spawn weight set individual(Nether)","Fureimu", DqmEntityFureimu, "spawn rate : Low 1 <-  20(Middle) -> High").getInt();
		DqmEntityGamegon = config.get("6_Spawn weight set individual(Nether)","Gamegon", DqmEntityGamegon, "spawn rate : Low 1 <-  20(Middle) -> High").getInt();
		DqmEntityGamegonload = config.get("6_Spawn weight set individual(Nether)","Gamegonload", DqmEntityGamegonload, "spawn rate : Low 1 <-  20(Middle) -> High").getInt();
		DqmEntityGanirasu = config.get("6_Spawn weight set individual(Nether)","Ganirasu", DqmEntityGanirasu, "spawn rate : Low 1 <-  20(Middle) -> High").getInt();
		DqmEntityGoldman = config.get("6_Spawn weight set individual(Nether)","Goldman", DqmEntityGoldman, "spawn rate : Low 1 <-  20(Middle) -> High").getInt();
		DqmEntityGoremu = config.get("6_Spawn weight set individual(Nether)","Goremu", DqmEntityGoremu, "spawn rate : Low 1 <-  20(Middle) -> High").getInt();
		DqmEntityGorudentotemu = config.get("6_Spawn weight set individual(Nether)","Gorudentotemu", DqmEntityGorudentotemu, "spawn rate : Low 1 <-  20(Middle) -> High").getInt();
		DqmEntityHotatewarabi = config.get("6_Spawn weight set individual(Nether)","Hotatewarabi", DqmEntityHotatewarabi, "spawn rate : Low 1 <-  20(Middle) -> High").getInt();
		DqmEntityJigokunohasami = config.get("6_Spawn weight set individual(Nether)","Jigokunohasami", DqmEntityJigokunohasami, "spawn rate : Low 1 <-  20(Middle) -> High").getInt();
		DqmEntityKedamon = config.get("6_Spawn weight set individual(Nether)","Kedamon", DqmEntityKedamon, "spawn rate : Low 1 <-  20(Middle) -> High").getInt();
		DqmEntityKemunkurusu = config.get("6_Spawn weight set individual(Nether)","Kemunkurusu", DqmEntityKemunkurusu, "spawn rate : Low 1 <-  20(Middle) -> High").getInt();
		DqmEntityKimendousi = config.get("6_Spawn weight set individual(Nether)","Kimendousi", DqmEntityKimendousi, "spawn rate : Low 1 <-  20(Middle) -> High").getInt();
		DqmEntityKiraama = config.get("6_Spawn weight set individual(Nether)","Kiraama", DqmEntityKiraama, "spawn rate : Low 1 <-  20(Middle) -> High").getInt();
		DqmEntityKirakurabu = config.get("6_Spawn weight set individual(Nether)","Kirakurabu", DqmEntityKirakurabu, "spawn rate : Low 1 <-  20(Middle) -> High").getInt();
		DqmEntityKiramasin = config.get("6_Spawn weight set individual(Nether)","Kiramasin", DqmEntityKiramasin, "spawn rate : Low 1 <-  20(Middle) -> High").getInt();
		DqmEntityKiramasin2 = config.get("6_Spawn weight set individual(Nether)","Kiramasin2", DqmEntityKiramasin2, "spawn rate : Low 1 <-  20(Middle) -> High").getInt();
		DqmEntityKisudragon = config.get("6_Spawn weight set individual(Nether)","Kisudragon", DqmEntityKisudragon, "spawn rate : Low 1 <-  20(Middle) -> High").getInt();
		DqmEntityKuinsuraimu = config.get("6_Spawn weight set individual(Nether)","Kuinsuraimu", DqmEntityKuinsuraimu, "spawn rate : Low 1 <-  20(Middle) -> High").getInt();
		DqmEntityMagematango = config.get("6_Spawn weight set individual(Nether)","Magematango", DqmEntityMagematango, "spawn rate : Low 1 <-  20(Middle) -> High").getInt();
		DqmEntityMagemomonja = config.get("6_Spawn weight set individual(Nether)","Magemomonja", DqmEntityMagemomonja, "spawn rate : Low 1 <-  20(Middle) -> High").getInt();
		DqmEntityMagumaron = config.get("6_Spawn weight set individual(Nether)","Magumaron", DqmEntityMagumaron, "spawn rate : Low 1 <-  20(Middle) -> High").getInt();
		DqmEntityMajikaruhatto = config.get("6_Spawn weight set individual(Nether)","Majikaruhatto", DqmEntityMajikaruhatto, "spawn rate : Low 1 <-  20(Middle) -> High").getInt();
		DqmEntityMaounokage = config.get("6_Spawn weight set individual(Nether)","Maounokage", DqmEntityMaounokage, "spawn rate : Low 1 <-  20(Middle) -> High").getInt();
		DqmEntityMaporena = config.get("6_Spawn weight set individual(Nether)","Maporena", DqmEntityMaporena, "spawn rate : Low 1 <-  20(Middle) -> High").getInt();
		DqmEntityMegazarurokku = config.get("6_Spawn weight set individual(Nether)","Megazarurokku", DqmEntityMegazarurokku, "spawn rate : Low 1 <-  20(Middle) -> High").getInt();
		//DqmEntityMetaruhanta = config.get("6_Spawn weight set individual(Nether)","//Metaruhanta", //DqmEntityMetaruhanta, "spawn rate : Low 1 <-  20(Middle) -> High").getInt();
		DqmEntityMimikku = config.get("6_Spawn weight set individual(Nether)","Mimikku", DqmEntityMimikku, "spawn rate : Low 1 <-  20(Middle) -> High").getInt();
		//DqmEntityPandorakibako = config.get("6_Spawn weight set individual(Nether)","//Pandorakibako", //DqmEntityPandorakibako, "spawn rate : Low 1 <-  20(Middle) -> High").getInt();
		DqmEntityPapettoman = config.get("6_Spawn weight set individual(Nether)","Papettoman", DqmEntityPapettoman, "spawn rate : Low 1 <-  20(Middle) -> High").getInt();
		DqmEntityPikusi = config.get("6_Spawn weight set individual(Nether)","Pikusi", DqmEntityPikusi, "spawn rate : Low 1 <-  20(Middle) -> High").getInt();
		DqmEntityPombom = config.get("6_Spawn weight set individual(Nether)","Pombom", DqmEntityPombom, "spawn rate : Low 1 <-  20(Middle) -> High").getInt();
		DqmEntityPuyon = config.get("6_Spawn weight set individual(Nether)","Puyon", DqmEntityPuyon, "spawn rate : Low 1 <-  20(Middle) -> High").getInt();
		DqmEntityRedsaikuron = config.get("6_Spawn weight set individual(Nether)","Redsaikuron", DqmEntityRedsaikuron, "spawn rate : Low 1 <-  20(Middle) -> High").getInt();
		DqmEntitySaikuropusu = config.get("6_Spawn weight set individual(Nether)","Saikuropusu", DqmEntitySaikuropusu, "spawn rate : Low 1 <-  20(Middle) -> High").getInt();
		DqmEntitySirubadebiru = config.get("6_Spawn weight set individual(Nether)","Sirubadebiru", DqmEntitySirubadebiru, "spawn rate : Low 1 <-  20(Middle) -> High").getInt();
		DqmEntitySiryou = config.get("6_Spawn weight set individual(Nether)","Siryou", DqmEntitySiryou, "spawn rate : Low 1 <-  20(Middle) -> High").getInt();
		DqmEntitySiryounokisi = config.get("6_Spawn weight set individual(Nether)","Siryounokisi", DqmEntitySiryounokisi, "spawn rate : Low 1 <-  20(Middle) -> High").getInt();
		DqmEntitySodofantomu = config.get("6_Spawn weight set individual(Nether)","Sodofantomu", DqmEntitySodofantomu, "spawn rate : Low 1 <-  20(Middle) -> High").getInt();
		DqmEntityStarkimera = config.get("6_Spawn weight set individual(Nether)","Starkimera", DqmEntityStarkimera, "spawn rate : Low 1 <-  20(Middle) -> High").getInt();
		DqmEntityStonman = config.get("6_Spawn weight set individual(Nether)","Stonman", DqmEntityStonman, "spawn rate : Low 1 <-  20(Middle) -> High").getInt();
		DqmEntitySuraimubehomazun = config.get("6_Spawn weight set individual(Nether)","Suraimubehomazun", DqmEntitySuraimubehomazun, "spawn rate : Low 1 <-  20(Middle) -> High").getInt();
		DqmEntitySuraimuhaitawa = config.get("6_Spawn weight set individual(Nether)","Suraimuhaitawa", DqmEntitySuraimuhaitawa, "spawn rate : Low 1 <-  20(Middle) -> High").getInt();
		DqmEntitySuraimumadyura = config.get("6_Spawn weight set individual(Nether)","Suraimumadyura", DqmEntitySuraimumadyura, "spawn rate : Low 1 <-  20(Middle) -> High").getInt();
		DqmEntityTororuking = config.get("6_Spawn weight set individual(Nether)","Tororuking", DqmEntityTororuking, "spawn rate : Low 1 <-  20(Middle) -> High").getInt();
		//DqmEntityTubokku = config.get("6_Spawn weight set individual(Nether)","//Tubokku", //DqmEntityTubokku, "spawn rate : Low 1 <-  20(Middle) -> High").getInt();
		DqmEntityUmibouzu = config.get("6_Spawn weight set individual(Nether)","Umibouzu", DqmEntityUmibouzu, "spawn rate : Low 1 <-  20(Middle) -> High").getInt();
		DqmEntityEriminator = config.get("6_Spawn weight set individual(Nether)","Eriminator", DqmEntityEriminator, "spawn rate : Low 1 <-  20(Middle) -> High").getInt();
		DqmEntityDarkdoriado = config.get("6_Spawn weight set individual(Nether)","Darkdoriado", DqmEntityDarkdoriado, "spawn rate : Low 1 <-  20(Middle) -> High").getInt();
		DqmEntityShadopan = config.get("6_Spawn weight set individual(Nether)","Shadopan", DqmEntityShadopan, "spawn rate : Low 1 <-  20(Middle) -> High").getInt();
		DqmEntityWhitepan2 = config.get("6_Spawn weight set individual(Nether)","Whitepan2", DqmEntityWhitepan2, "spawn rate : Low 1 <-  20(Middle) -> High").getInt();


		config.setCategoryComment("7_Spawn weight set individual(End)", "this setting is mob spawn weight set for individual set mode");
		DqmEntityAkairai = config.get("7_Spawn weight set individual(End)","Akairai", DqmEntityAkairai, "spawn rate : Low 1 <-  20(Middle) -> High").getInt();
		DqmEntityBassaimasin = config.get("7_Spawn weight set individual(End)","Bassaimasin", DqmEntityBassaimasin, "spawn rate : Low 1 <-  20(Middle) -> High").getInt();
		DqmEntityBatorurex = config.get("7_Spawn weight set individual(End)","Batorurex", DqmEntityBatorurex, "spawn rate : Low 1 <-  20(Middle) -> High").getInt();
		DqmEntityBiggumoai = config.get("7_Spawn weight set individual(End)","Biggumoai", DqmEntityBiggumoai, "spawn rate : Low 1 <-  20(Middle) -> High").getInt();
		DqmEntityBurizado = config.get("7_Spawn weight set individual(End)","Burizado", DqmEntityBurizado, "spawn rate : Low 1 <-  20(Middle) -> High").getInt();
		DqmEntityDakunaito = config.get("7_Spawn weight set individual(End)","Dakunaito", DqmEntityDakunaito, "spawn rate : Low 1 <-  20(Middle) -> High").getInt();
		DqmEntityDarktororu = config.get("7_Spawn weight set individual(End)","Darktororu", DqmEntityDarktororu, "spawn rate : Low 1 <-  20(Middle) -> High").getInt();

		DqmEntityDasudragon = config.get("7_Spawn weight set individual(End)","Dasudragon", DqmEntityDasudragon, "spawn rate : Low 1 <-  20(Middle) -> High").getInt();
		DqmEntityDenga = config.get("7_Spawn weight set individual(End)","Denga", DqmEntityDenga, "spawn rate : Low 1 <-  20(Middle) -> High").getInt();
		DqmEntityDesujakkaru = config.get("7_Spawn weight set individual(End)","Desujakkaru", DqmEntityDesujakkaru, "spawn rate : Low 1 <-  20(Middle) -> High").getInt();
		DqmEntityDesunyago = config.get("7_Spawn weight set individual(End)","Desunyago", DqmEntityDesunyago, "spawn rate : Low 1 <-  20(Middle) -> High").getInt();
		DqmEntityDragondarknaito = config.get("7_Spawn weight set individual(End)","Dragondarknaito", DqmEntityDragondarknaito, "spawn rate : Low 1 <-  20(Middle) -> High").getInt();
		DqmEntityGamegonrejendo = config.get("7_Spawn weight set individual(End)","Gamegonrejendo", DqmEntityGamegonrejendo, "spawn rate : Low 1 <-  20(Middle) -> High").getInt();
		DqmEntityGigantesu = config.get("7_Spawn weight set individual(End)","Gigantesu", DqmEntityGigantesu, "spawn rate : Low 1 <-  20(Middle) -> High").getInt();
		DqmEntityGodraida = config.get("7_Spawn weight set individual(End)","Godraida", DqmEntityGodraida, "spawn rate : Low 1 <-  20(Middle) -> High").getInt();
		DqmEntityGorudensuraimu = config.get("7_Spawn weight set individual(End)","Gorudensuraimu", DqmEntityGorudensuraimu, "spawn rate : Low 1 <-  20(Middle) -> High").getInt();
		DqmEntityJigokunoyoroi = config.get("7_Spawn weight set individual(End)","Jigokunoyoroi", DqmEntityJigokunoyoroi, "spawn rate : Low 1 <-  20(Middle) -> High").getInt();
		DqmEntityKagenokisi = config.get("7_Spawn weight set individual(End)","Kagenokisi", DqmEntityKagenokisi, "spawn rate : Low 1 <-  20(Middle) -> High").getInt();
		DqmEntityManemane = config.get("7_Spawn weight set individual(End)","Manemane", DqmEntityManemane, "spawn rate : Low 1 <-  20(Middle) -> High").getInt();
		DqmEntityPandorabox = config.get("7_Spawn weight set individual(End)","Pandorabox", DqmEntityPandorabox, "spawn rate : Low 1 <-  20(Middle) -> High").getInt();
		DqmEntityRyuiso = config.get("7_Spawn weight set individual(End)","Ryuiso", DqmEntityRyuiso, "spawn rate : Low 1 <-  20(Middle) -> High").getInt();
		DqmEntityTororubonba = config.get("7_Spawn weight set individual(End)","Tororubonba", DqmEntityTororubonba, "spawn rate : Low 1 <-  20(Middle) -> High").getInt();
		DqmEntityDesusutoka = config.get("7_Spawn weight set individual(End)","Desusutoka", DqmEntityDesusutoka, "spawn rate : Low 1 <-  20(Middle) -> High").getInt();
		DqmEntityShadopan2 = config.get("7_Spawn weight set individual(End)","Shadopan2", DqmEntityShadopan2, "spawn rate : Low 1 <-  20(Middle) -> High").getInt();


		config.setCategoryComment("8_Spawn weight set individual(Metal)", "this setting is mob spawn weight set for individual set mode");
		DqmEntityMetaruburazazu  = config.get("8_Spawn weight set individual(Metal)","Metaruburazazu", DqmEntityMetaruburazazu , "spawn rate : Low 1 <-  20(Middle) -> High").getInt();
		DqmEntityMetasura = config.get("8_Spawn weight set individual(Metal)","Metasura", DqmEntityMetasura , "spawn rate : Low 1 <-  20(Middle) -> High").getInt();
		DqmEntityHagumeta = config.get("8_Spawn weight set individual(Metal)","Hagumeta", DqmEntityHagumeta , "spawn rate : Low 1 <-  20(Middle) -> High").getInt();
		DqmEntityDragometaru = config.get("8_Spawn weight set individual(Metal)","Dragometaru", DqmEntityDragometaru , "spawn rate : Low 1 <-  20(Middle) -> High").getInt();
		DqmEntityMetaking = config.get("8_Spawn weight set individual(Metal)","Metaking", DqmEntityMetaking , "spawn rate : Low 1 <-  20(Middle) -> High").getInt();
		DqmEntityDaiyamondosuraimu  = config.get("8_Spawn weight set individual(Metal)","Daiyamondosuraimu", DqmEntityDaiyamondosuraimu , "spawn rate : Low 1 <-  20(Middle) -> High").getInt();
		DqmEntityPuratinaking = config.get("8_Spawn weight set individual(Metal)","Puratinaking", DqmEntityPuratinaking , "spawn rate : Low 1 <-  20(Middle) -> High").getInt();
		//DqmEntityGoldenmetalslime  = config.get("8_Spawn weight set individual(Metal)","//Goldenmetalslime", //DqmEntityGoldenmetalslime , "spawn rate : Low 1 <-  20(Middle) -> High").getInt();
		DqmEntityHaguremetaruking = config.get("8_Spawn weight set individual(Metal)","Haguremetaruking", DqmEntityHaguremetaruking , "spawn rate : Low 1 <-  20(Middle) -> High").getInt();


		config.setCategoryComment("9_Spawn weight set individual(ETC)", "this setting is mob spawn weight set for individual set mode");
		DqmEntityPandorakibako = config.get("9_Spawn weight set individual(ETC)","Pandorakibako", DqmEntityPandorakibako, "spawn rate : Low 1 <-  20(Middle) -> High").getInt();
		DqmEntityMimikkukibako = config.get("9_Spawn weight set individual(ETC)","Mimikkukibako", DqmEntityMimikkukibako, "spawn rate : Low 1 <-  20(Middle) -> High").getInt();
		DqmEntityHitokuibako = config.get("9_Spawn weight set individual(ETC)","Hitokuibako", DqmEntityHitokuibako, "spawn rate : Low 1 <-  20(Middle) -> High").getInt();
		DqmEntityFurosutogizumo = config.get("9_Spawn weight set individual(ETC)","Furosutogizumo", DqmEntityFurosutogizumo, "spawn rate : Low 1 <-  20(Middle) -> High").getInt();
		DqmEntityHiitogizumo = config.get("9_Spawn weight set individual(ETC)","Hiitogizumo", DqmEntityHiitogizumo, "spawn rate : Low 1 <-  20(Middle) -> High").getInt();
		DqmEntitySuraimuking = config.get("9_Spawn weight set individual(ETC)","Suraimuking", DqmEntitySuraimuking, "spawn rate : Low 1 <-  20(Middle) -> High").getInt();
		DqmEntityKingbesu = config.get("9_Spawn weight set individual(ETC)","Kingbesu", DqmEntityKingbesu, "spawn rate : Low 1 <-  20(Middle) -> High").getInt();
		DqmEntityGizumo = config.get("9_Spawn weight set individual(ETC)","Gizumo", DqmEntityGizumo, "spawn rate : Low 1 <-  20(Middle) -> High").getInt();
		DqmEntityTubo = config.get("9_Spawn weight set individual(ETC)","Tubo", DqmEntityTubo, "spawn rate : Low 1 <-  20(Middle) -> High").getInt();
*/
		config.setCategoryComment("4_Spawn weight set individual(Day)", "this setting is mob spawn weight set for individual set mode.\nspawn rate : Low 1 <-  20(Middle) -> High");
		DqmEntityGorotuki = config.get("4_Spawn weight set individual(Day)","Gorotuki", DqmEntityGorotuki).getInt();
		DqmEntityDokuroarai = config.get("4_Spawn weight set individual(Day)","Dokuroarai", DqmEntityDokuroarai).getInt();
		DqmEntityDorozara = config.get("4_Spawn weight set individual(Day)","Dorozara", DqmEntityDorozara).getInt();
		DqmEntityMadohando = config.get("4_Spawn weight set individual(Day)","Madohando", DqmEntityMadohando).getInt();
		DqmEntityObakeumiusi = config.get("4_Spawn weight set individual(Day)","Obakeumiusi", DqmEntityObakeumiusi).getInt();
		DqmEntitySirudokozou = config.get("4_Spawn weight set individual(Day)","Sirudokozou", DqmEntitySirudokozou).getInt();
		DqmEntityUzusioking = config.get("4_Spawn weight set individual(Day)","Uzusioking", DqmEntityUzusioking).getInt();
		DqmEntityDucksbill = config.get("4_Spawn weight set individual(Day)","Ducksbill", DqmEntityDucksbill).getInt();
		DqmEntityMomonja = config.get("4_Spawn weight set individual(Day)","Momonja", DqmEntityMomonja).getInt();
		DqmEntityPurizunyan = config.get("4_Spawn weight set individual(Day)","Purizunyan", DqmEntityPurizunyan).getInt();
		DqmEntitySibirekurage = config.get("4_Spawn weight set individual(Day)","Sibirekurage", DqmEntitySibirekurage).getInt();
		DqmEntitySunomon = config.get("4_Spawn weight set individual(Day)","Sunomon", DqmEntitySunomon).getInt();
		DqmEntitySuraimutumuri = config.get("4_Spawn weight set individual(Day)","Suraimutumuri", DqmEntitySuraimutumuri).getInt();
		DqmEntityAyasiikage = config.get("4_Spawn weight set individual(Day)","Ayasiikage", DqmEntityAyasiikage).getInt();
		DqmEntityBigCrow = config.get("4_Spawn weight set individual(Day)","BigCrow", DqmEntityBigCrow).getInt();
		DqmEntityBigguhatto = config.get("4_Spawn weight set individual(Day)","Bigguhatto", DqmEntityBigguhatto).getInt();
		DqmEntityBubsura = config.get("4_Spawn weight set individual(Day)","Bubsura", DqmEntityBubsura).getInt();
		DqmEntityDoruido = config.get("4_Spawn weight set individual(Day)","Doruido", DqmEntityDoruido).getInt();
		DqmEntityDragosuraimu = config.get("4_Spawn weight set individual(Day)","Dragosuraimu", DqmEntityDragosuraimu).getInt();

		DqmEntityEbiruapple = config.get("4_Spawn weight set individual(Day)","Ebiruapple", DqmEntityEbiruapple).getInt();
		DqmEntityFaratto = config.get("4_Spawn weight set individual(Day)","Faratto", DqmEntityFaratto).getInt();
		DqmEntityGaikotu = config.get("4_Spawn weight set individual(Day)","Gaikotu", DqmEntityGaikotu).getInt();
		//DqmEntityGizumo = config.get("4_Spawn weight set individual(Day)","//Gizumo", //DqmEntityGizumo).getInt();
		DqmEntityGizumoAZ = config.get("4_Spawn weight set individual(Day)","GizumoAZ", DqmEntityGizumoAZ).getInt();
		DqmEntityGuntaigani = config.get("4_Spawn weight set individual(Day)","Guntaigani", DqmEntityGuntaigani).getInt();
		//DqmEntityHitokuikibako = config.get("4_Spawn weight set individual(Day)","//Hitokuikibako", //DqmEntityHitokuikibako).getInt();
		DqmEntityHitokuisaberu = config.get("4_Spawn weight set individual(Day)","Hitokuisaberu", DqmEntityHitokuisaberu).getInt();
		DqmEntityIkkakuusagi = config.get("4_Spawn weight set individual(Day)","Ikkakuusagi", DqmEntityIkkakuusagi).getInt();
		DqmEntityItamogu = config.get("4_Spawn weight set individual(Day)","Itamogu", DqmEntityItamogu).getInt();
		//DqmEntityKingbesu = config.get("4_Spawn weight set individual(Day)","//Kingbesu", //DqmEntityKingbesu).getInt();
		DqmEntityMomon = config.get("4_Spawn weight set individual(Day)","Momon", DqmEntityMomon).getInt();
		DqmEntityOnikozou = config.get("4_Spawn weight set individual(Day)","Onikozou", DqmEntityOnikozou).getInt();
		DqmEntityOokiduti = config.get("4_Spawn weight set individual(Day)","Ookiduti", DqmEntityOokiduti).getInt();
		DqmEntityOonamekuji = config.get("4_Spawn weight set individual(Day)","Oonamekuji", DqmEntityOonamekuji).getInt();
		DqmEntityRemonsuraimu = config.get("4_Spawn weight set individual(Day)","Remonsuraimu", DqmEntityRemonsuraimu).getInt();
		DqmEntityRippusu = config.get("4_Spawn weight set individual(Day)","Rippusu", DqmEntityRippusu).getInt();
		DqmEntitySabotenboru = config.get("4_Spawn weight set individual(Day)","Sabotenboru", DqmEntitySabotenboru).getInt();
		DqmEntitySimasimacat = config.get("4_Spawn weight set individual(Day)","Simasimacat", DqmEntitySimasimacat).getInt();
		DqmEntitySupini = config.get("4_Spawn weight set individual(Day)","Supini", DqmEntitySupini).getInt();
		DqmEntitySura = config.get("4_Spawn weight set individual(Day)","Sura", DqmEntitySura).getInt();
		DqmEntitySuraimubesu = config.get("4_Spawn weight set individual(Day)","Suraimubesu", DqmEntitySuraimubesu).getInt();
		DqmEntityTogebouzu = config.get("4_Spawn weight set individual(Day)","Togebouzu", DqmEntityTogebouzu).getInt();
		//DqmEntityTubo = config.get("4_Spawn weight set individual(Day)","//Tubo", //DqmEntityTubo).getInt();
		DqmEntityTukaima = config.get("4_Spawn weight set individual(Day)","Tukaima", DqmEntityTukaima).getInt();
		DqmEntityZinmentyou = config.get("4_Spawn weight set individual(Day)","Zinmentyou", DqmEntityZinmentyou).getInt();
		DqmEntityZukkinya = config.get("4_Spawn weight set individual(Day)","Zukkinya", DqmEntityZukkinya).getInt();
		DqmEntityBurauni = config.get("4_Spawn weight set individual(Day)","Burauni", DqmEntityBurauni).getInt();

		DqmEntityButisuraimu = config.get("4_Spawn weight set individual(Day)","Butisuraimu", DqmEntityButisuraimu).getInt();
		DqmEntityDoronuba = config.get("4_Spawn weight set individual(Day)","Doronuba", DqmEntityDoronuba).getInt();
		DqmEntityHoimisura = config.get("4_Spawn weight set individual(Day)","Hoimisura", DqmEntityHoimisura).getInt();
		DqmEntityKimera = config.get("4_Spawn weight set individual(Day)","Kimera", DqmEntityKimera).getInt();
		DqmEntityKirapan = config.get("4_Spawn weight set individual(Day)","Kirapan", DqmEntityKirapan).getInt();
		DqmEntityKirikabuobake = config.get("4_Spawn weight set individual(Day)","Kirikabuobake", DqmEntityKirikabuobake).getInt();
		DqmEntityObakekinoko = config.get("4_Spawn weight set individual(Day)","Obakekinoko", DqmEntityObakekinoko).getInt();
		DqmEntityOokutibasi = config.get("4_Spawn weight set individual(Day)","Ookutibasi", DqmEntityOokutibasi).getInt();
		DqmEntityOomedama = config.get("4_Spawn weight set individual(Day)","Oomedama", DqmEntityOomedama).getInt();
		DqmEntityPapetkozou = config.get("4_Spawn weight set individual(Day)","Papetkozou", DqmEntityPapetkozou).getInt();
		DqmEntityRiripat = config.get("4_Spawn weight set individual(Day)","Riripat", DqmEntityRiripat).getInt();
		DqmEntitySukippaa = config.get("4_Spawn weight set individual(Day)","Sukippaa", DqmEntitySukippaa).getInt();
		//DqmEntitySuraimuking = config.get("4_Spawn weight set individual(Day)","//Suraimuking", //DqmEntitySuraimuking).getInt();
		DqmEntitySuraimunaito = config.get("4_Spawn weight set individual(Day)","Suraimunaito", DqmEntitySuraimunaito).getInt();
		DqmEntitySuraimutawa = config.get("4_Spawn weight set individual(Day)","Suraimutawa", DqmEntitySuraimutawa).getInt();
		DqmEntityWaraibukuro = config.get("4_Spawn weight set individual(Day)","Waraibukuro", DqmEntityWaraibukuro).getInt();

		config.setCategoryComment("5_Spawn weight set individual(Night)", "this setting is mob spawn weight set for individual set mode.\nspawn rate : Low 1 <-  20(Middle) -> High");
		DqmEntityBakudaniwa = config.get("5_Spawn weight set individual(Night)","Bakudaniwa", DqmEntityBakudaniwa).getInt();
		DqmEntityBehoimusuraimu = config.get("5_Spawn weight set individual(Night)","Behoimusuraimu", DqmEntityBehoimusuraimu).getInt();
		DqmEntityBeronyaago = config.get("5_Spawn weight set individual(Night)","Beronyaago", DqmEntityBeronyaago).getInt();
		DqmEntityHgizumo = config.get("5_Spawn weight set individual(Night)","Hgizumo", DqmEntityHgizumo).getInt();
		//DqmEntityHiitogizumo = config.get("5_Spawn weight set individual(Night)","//Hiitogizumo", //DqmEntityHiitogizumo).getInt();
		DqmEntityMeijikimera = config.get("5_Spawn weight set individual(Night)","Meijikimera", DqmEntityMeijikimera).getInt();
		DqmEntityMetaruraida = config.get("5_Spawn weight set individual(Night)","Metaruraida", DqmEntityMetaruraida).getInt();
		DqmEntityOdoruhouseki = config.get("5_Spawn weight set individual(Night)","Odoruhouseki", DqmEntityOdoruhouseki).getInt();
		DqmEntitySibiredanbira = config.get("5_Spawn weight set individual(Night)","Sibiredanbira", DqmEntitySibiredanbira).getInt();
		DqmEntityYouganmajin = config.get("5_Spawn weight set individual(Night)","Youganmajin", DqmEntityYouganmajin).getInt();
		DqmEntityAkumanosyo = config.get("5_Spawn weight set individual(Night)","Akumanosyo", DqmEntityAkumanosyo).getInt();
		DqmEntityArumiraji = config.get("5_Spawn weight set individual(Night)","Arumiraji", DqmEntityArumiraji).getInt();
		DqmEntityBuraddihando = config.get("5_Spawn weight set individual(Night)","Buraddihando", DqmEntityBuraddihando).getInt();
		DqmEntityFgizumo = config.get("5_Spawn weight set individual(Night)","Fgizumo", DqmEntityFgizumo).getInt();
		//DqmEntityFurosutogizumo = config.get("5_Spawn weight set individual(Night)","//Furosutogizumo", //DqmEntityFurosutogizumo).getInt();
		DqmEntityHoroghost = config.get("5_Spawn weight set individual(Night)","Horoghost", DqmEntityHoroghost).getInt();
		DqmEntityHyouganmajin = config.get("5_Spawn weight set individual(Night)","Hyouganmajin", DqmEntityHyouganmajin).getInt();
		DqmEntityJeriman = config.get("5_Spawn weight set individual(Night)","Jeriman", DqmEntityJeriman).getInt();
		DqmEntityMarinsuraimu = config.get("5_Spawn weight set individual(Night)","Marinsuraimu", DqmEntityMarinsuraimu).getInt();
		DqmEntitySumairurokku = config.get("5_Spawn weight set individual(Night)","Sumairurokku", DqmEntitySumairurokku).getInt();
		DqmEntityTahodoraki = config.get("5_Spawn weight set individual(Night)","Tahodoraki", DqmEntityTahodoraki).getInt();
		DqmEntityTomosibikozou = config.get("5_Spawn weight set individual(Night)","Tomosibikozou", DqmEntityTomosibikozou).getInt();
		DqmEntityMetaruhantaken = config.get("5_Spawn weight set individual(Night)","Metaruhantaken", DqmEntityMetaruhantaken).getInt();
		//DqmEntityAkumanotubo = config.get("5_Spawn weight set individual(Night)","//Akumanotubo", //DqmEntityAkumanotubo).getInt();

		DqmEntityAxedoragon = config.get("5_Spawn weight set individual(Night)","Axedoragon", DqmEntityAxedoragon).getInt();
		DqmEntityBaburin = config.get("5_Spawn weight set individual(Night)","Baburin", DqmEntityBaburin).getInt();
		DqmEntityBerobero = config.get("5_Spawn weight set individual(Night)","Berobero", DqmEntityBerobero).getInt();
		DqmEntityBesuking = config.get("5_Spawn weight set individual(Night)","Besuking", DqmEntityBesuking).getInt();
		DqmEntityDansunidoru = config.get("5_Spawn weight set individual(Night)","Dansunidoru", DqmEntityDansunidoru).getInt();
		DqmEntityDoraki = config.get("5_Spawn weight set individual(Night)","Doraki", DqmEntityDoraki).getInt();
		DqmEntityDoroningyou = config.get("5_Spawn weight set individual(Night)","Doroningyou", DqmEntityDoroningyou).getInt();
		DqmEntityGaikotukensi = config.get("5_Spawn weight set individual(Night)","Gaikotukensi", DqmEntityGaikotukensi).getInt();
		DqmEntityGappurin = config.get("5_Spawn weight set individual(Night)","Gappurin", DqmEntityGappurin).getInt();
		DqmEntityGenjutusi = config.get("5_Spawn weight set individual(Night)","Genjutusi", DqmEntityGenjutusi).getInt();
		DqmEntityGhost = config.get("5_Spawn weight set individual(Night)","Ghost", DqmEntityGhost).getInt();
		DqmEntityHerughost = config.get("5_Spawn weight set individual(Night)","Herughost", DqmEntityHerughost).getInt();
		DqmEntityHitokuibako = config.get("5_Spawn weight set individual(Night)","Hitokuibako", DqmEntityHitokuibako).getInt();
		DqmEntityKingsura = config.get("5_Spawn weight set individual(Night)","Kingsura", DqmEntityKingsura).getInt();
		DqmEntityKirapan2 = config.get("5_Spawn weight set individual(Night)","Kirapan2", DqmEntityKirapan2).getInt();
		DqmEntityMapetman = config.get("5_Spawn weight set individual(Night)","Mapetman", DqmEntityMapetman).getInt();
		DqmEntityMeragosuto = config.get("5_Spawn weight set individual(Night)","Meragosuto", DqmEntityMeragosuto).getInt();
		DqmEntityMetoroghost = config.get("5_Spawn weight set individual(Night)","Metoroghost", DqmEntityMetoroghost).getInt();
		//DqmEntityMimikkukibako = config.get("5_Spawn weight set individual(Night)","//Mimikkukibako", //DqmEntityMimikkukibako).getInt();
		DqmEntityMinidemon = config.get("5_Spawn weight set individual(Night)","Minidemon", DqmEntityMinidemon).getInt();
		DqmEntityMokomokojuu = config.get("5_Spawn weight set individual(Night)","Mokomokojuu", DqmEntityMokomokojuu).getInt();
		DqmEntityMrippusu = config.get("5_Spawn weight set individual(Night)","Mrippusu", DqmEntityMrippusu).getInt();
		DqmEntityObakekyandoru = config.get("5_Spawn weight set individual(Night)","Obakekyandoru", DqmEntityObakekyandoru).getInt();
		DqmEntityRaimusuraimu = config.get("5_Spawn weight set individual(Night)","Raimusuraimu", DqmEntityRaimusuraimu).getInt();
		DqmEntitySamayoutamasii = config.get("5_Spawn weight set individual(Night)","Samayoutamasii", DqmEntitySamayoutamasii).getInt();
		DqmEntitySamayouyoroi = config.get("5_Spawn weight set individual(Night)","Samayouyoroi", DqmEntitySamayouyoroi).getInt();
		DqmEntitySkullgaroo = config.get("5_Spawn weight set individual(Night)","Skullgaroo", DqmEntitySkullgaroo).getInt();
		DqmEntitySumoruguru = config.get("5_Spawn weight set individual(Night)","Sumoruguru", DqmEntitySumoruguru).getInt();
		DqmEntitySuraimubogu = config.get("5_Spawn weight set individual(Night)","Suraimubogu", DqmEntitySuraimubogu).getInt();
		DqmEntitySuraimuburesu = config.get("5_Spawn weight set individual(Night)","Suraimuburesu", DqmEntitySuraimuburesu).getInt();
		DqmEntitySyado = config.get("5_Spawn weight set individual(Night)","Syado", DqmEntitySyado).getInt();
		DqmEntityTororu = config.get("5_Spawn weight set individual(Night)","Tororu", DqmEntityTororu).getInt();
		DqmEntityTutiwarasi = config.get("5_Spawn weight set individual(Night)","Tutiwarasi", DqmEntityTutiwarasi).getInt();
		DqmEntityAnimaruzonbi = config.get("5_Spawn weight set individual(Night)","Animaruzonbi", DqmEntityAnimaruzonbi).getInt();
		DqmEntityBakudanbebi = config.get("5_Spawn weight set individual(Night)","Bakudanbebi", DqmEntityBakudanbebi).getInt();
		DqmEntityBebisatan = config.get("5_Spawn weight set individual(Night)","Bebisatan", DqmEntityBebisatan).getInt();
		DqmEntityBehoimisuraimu = config.get("5_Spawn weight set individual(Night)","Behoimisuraimu", DqmEntityBehoimisuraimu).getInt();
		DqmEntityBuchunpa = config.get("5_Spawn weight set individual(Night)","Buchunpa", DqmEntityBuchunpa).getInt();
		DqmEntityButtizukinya = config.get("5_Spawn weight set individual(Night)","Buttizukinya", DqmEntityButtizukinya).getInt();
		DqmEntityDesufuratta = config.get("5_Spawn weight set individual(Night)","Desufuratta", DqmEntityDesufuratta).getInt();
		DqmEntityDokuyazukin = config.get("5_Spawn weight set individual(Night)","Dokuyazukin", DqmEntityDokuyazukin).getInt();
		DqmEntityDorakima = config.get("5_Spawn weight set individual(Night)","Dorakima", DqmEntityDorakima).getInt();
		DqmEntityEnzeruslime = config.get("5_Spawn weight set individual(Night)","Enzeruslime", DqmEntityEnzeruslime).getInt();
		DqmEntityHitokuiga = config.get("5_Spawn weight set individual(Night)","Hitokuiga", DqmEntityHitokuiga).getInt();
		DqmEntityKirasuko = config.get("5_Spawn weight set individual(Night)","Kirasuko", DqmEntityKirasuko).getInt();
		DqmEntityMatango = config.get("5_Spawn weight set individual(Night)","Matango", DqmEntityMatango).getInt();
		DqmEntityMeijidoraki = config.get("5_Spawn weight set individual(Night)","Meijidoraki", DqmEntityMeijidoraki).getInt();
		DqmEntityNightwalker = config.get("5_Spawn weight set individual(Night)","Nightwalker", DqmEntityNightwalker).getInt();
		DqmEntityPinkmomon = config.get("5_Spawn weight set individual(Night)","Pinkmomon", DqmEntityPinkmomon).getInt();
		DqmEntitySibireageha = config.get("5_Spawn weight set individual(Night)","Sibireageha", DqmEntitySibireageha).getInt();
		DqmEntitySupekutetto = config.get("5_Spawn weight set individual(Night)","Supekutetto", DqmEntitySupekutetto).getInt();
		DqmEntitySura2 = config.get("5_Spawn weight set individual(Night)","Sura2", DqmEntitySura2).getInt();
		DqmEntityTonburero = config.get("5_Spawn weight set individual(Night)","Tonburero", DqmEntityTonburero).getInt();
		DqmEntityUmiusi = config.get("5_Spawn weight set individual(Night)","Umiusi", DqmEntityUmiusi).getInt();


		config.setCategoryComment("6_Spawn weight set individual(Nether)", "this setting is mob spawn weight set for individual set mode.\nspawn rate : Low 1 <-  20(Middle) -> High");
		DqmEntityAnkokumajin = config.get("6_Spawn weight set individual(Nether)","Ankokumajin", DqmEntityAnkokumajin).getInt();
		DqmEntityAroinpu = config.get("6_Spawn weight set individual(Nether)","Aroinpu", DqmEntityAroinpu).getInt();
		DqmEntityBaburuking = config.get("6_Spawn weight set individual(Nether)","Baburuking", DqmEntityBaburuking).getInt();
		DqmEntityBarakku = config.get("6_Spawn weight set individual(Nether)","Barakku", DqmEntityBarakku).getInt();
		DqmEntityBariidodog = config.get("6_Spawn weight set individual(Nether)","Bariidodog", DqmEntityBariidodog).getInt();
		DqmEntityBehomasuraimu = config.get("6_Spawn weight set individual(Nether)","Behomasuraimu", DqmEntityBehomasuraimu).getInt();
		DqmEntityBiggufeisu = config.get("6_Spawn weight set individual(Nether)","Biggufeisu", DqmEntityBiggufeisu).getInt();
		DqmEntityBighanma = config.get("6_Spawn weight set individual(Nether)","Bighanma", DqmEntityBighanma).getInt();
		DqmEntityBosutororu = config.get("6_Spawn weight set individual(Nether)","Bosutororu", DqmEntityBosutororu).getInt();
		DqmEntityBoureikensi = config.get("6_Spawn weight set individual(Nether)","Boureikensi", DqmEntityBoureikensi).getInt();
		DqmEntityBuraddosodo = config.get("6_Spawn weight set individual(Nether)","Buraddosodo", DqmEntityBuraddosodo).getInt();
		DqmEntityBurakkubejita = config.get("6_Spawn weight set individual(Nether)","Burakkubejita", DqmEntityBurakkubejita).getInt();
		DqmEntityDarkslime = config.get("6_Spawn weight set individual(Nether)","Darkslime", DqmEntityDarkslime).getInt();
		DqmEntityDeddopekka = config.get("6_Spawn weight set individual(Nether)","Deddopekka", DqmEntityDeddopekka).getInt();
		DqmEntityDgizumo = config.get("6_Spawn weight set individual(Nether)","Dgizumo", DqmEntityDgizumo).getInt();
		DqmEntityDollmaster = config.get("6_Spawn weight set individual(Nether)","Dollmaster", DqmEntityDollmaster).getInt();
		DqmEntityDoragonsoruja = config.get("6_Spawn weight set individual(Nether)","Doragonsoruja", DqmEntityDoragonsoruja).getInt();
		DqmEntityDqmdragon = config.get("6_Spawn weight set individual(Nether)","Dqmdragon", DqmEntityDqmdragon).getInt();
		DqmEntityDragonnaito = config.get("6_Spawn weight set individual(Nether)","Dragonnaito", DqmEntityDragonnaito).getInt();
		DqmEntityDragonraida = config.get("6_Spawn weight set individual(Nether)","Dragonraida", DqmEntityDragonraida).getInt();
		DqmEntityFureimu = config.get("6_Spawn weight set individual(Nether)","Fureimu", DqmEntityFureimu).getInt();
		DqmEntityGamegon = config.get("6_Spawn weight set individual(Nether)","Gamegon", DqmEntityGamegon).getInt();
		DqmEntityGamegonload = config.get("6_Spawn weight set individual(Nether)","Gamegonload", DqmEntityGamegonload).getInt();
		DqmEntityGanirasu = config.get("6_Spawn weight set individual(Nether)","Ganirasu", DqmEntityGanirasu).getInt();
		DqmEntityGoldman = config.get("6_Spawn weight set individual(Nether)","Goldman", DqmEntityGoldman).getInt();
		DqmEntityGoremu = config.get("6_Spawn weight set individual(Nether)","Goremu", DqmEntityGoremu).getInt();
		DqmEntityGorudentotemu = config.get("6_Spawn weight set individual(Nether)","Gorudentotemu", DqmEntityGorudentotemu).getInt();
		DqmEntityHotatewarabi = config.get("6_Spawn weight set individual(Nether)","Hotatewarabi", DqmEntityHotatewarabi).getInt();
		DqmEntityJigokunohasami = config.get("6_Spawn weight set individual(Nether)","Jigokunohasami", DqmEntityJigokunohasami).getInt();
		DqmEntityKedamon = config.get("6_Spawn weight set individual(Nether)","Kedamon", DqmEntityKedamon).getInt();
		DqmEntityKemunkurusu = config.get("6_Spawn weight set individual(Nether)","Kemunkurusu", DqmEntityKemunkurusu).getInt();
		DqmEntityKimendousi = config.get("6_Spawn weight set individual(Nether)","Kimendousi", DqmEntityKimendousi).getInt();
		DqmEntityKiraama = config.get("6_Spawn weight set individual(Nether)","Kiraama", DqmEntityKiraama).getInt();
		DqmEntityKirakurabu = config.get("6_Spawn weight set individual(Nether)","Kirakurabu", DqmEntityKirakurabu).getInt();
		DqmEntityKiramasin = config.get("6_Spawn weight set individual(Nether)","Kiramasin", DqmEntityKiramasin).getInt();
		DqmEntityKiramasin2 = config.get("6_Spawn weight set individual(Nether)","Kiramasin2", DqmEntityKiramasin2).getInt();
		DqmEntityKisudragon = config.get("6_Spawn weight set individual(Nether)","Kisudragon", DqmEntityKisudragon).getInt();
		DqmEntityKuinsuraimu = config.get("6_Spawn weight set individual(Nether)","Kuinsuraimu", DqmEntityKuinsuraimu).getInt();
		DqmEntityMagematango = config.get("6_Spawn weight set individual(Nether)","Magematango", DqmEntityMagematango).getInt();
		DqmEntityMagemomonja = config.get("6_Spawn weight set individual(Nether)","Magemomonja", DqmEntityMagemomonja).getInt();
		DqmEntityMagumaron = config.get("6_Spawn weight set individual(Nether)","Magumaron", DqmEntityMagumaron).getInt();
		DqmEntityMajikaruhatto = config.get("6_Spawn weight set individual(Nether)","Majikaruhatto", DqmEntityMajikaruhatto).getInt();
		DqmEntityMaounokage = config.get("6_Spawn weight set individual(Nether)","Maounokage", DqmEntityMaounokage).getInt();
		DqmEntityMaporena = config.get("6_Spawn weight set individual(Nether)","Maporena", DqmEntityMaporena).getInt();
		DqmEntityMegazarurokku = config.get("6_Spawn weight set individual(Nether)","Megazarurokku", DqmEntityMegazarurokku).getInt();
		//DqmEntityMetaruhanta = config.get("6_Spawn weight set individual(Nether)","//Metaruhanta", //DqmEntityMetaruhanta).getInt();
		DqmEntityMimikku = config.get("6_Spawn weight set individual(Nether)","Mimikku", DqmEntityMimikku).getInt();
		//DqmEntityPandorakibako = config.get("6_Spawn weight set individual(Nether)","//Pandorakibako", //DqmEntityPandorakibako).getInt();
		DqmEntityPapettoman = config.get("6_Spawn weight set individual(Nether)","Papettoman", DqmEntityPapettoman).getInt();
		DqmEntityPikusi = config.get("6_Spawn weight set individual(Nether)","Pikusi", DqmEntityPikusi).getInt();
		DqmEntityPombom = config.get("6_Spawn weight set individual(Nether)","Pombom", DqmEntityPombom).getInt();
		DqmEntityPuyon = config.get("6_Spawn weight set individual(Nether)","Puyon", DqmEntityPuyon).getInt();
		DqmEntityRedsaikuron = config.get("6_Spawn weight set individual(Nether)","Redsaikuron", DqmEntityRedsaikuron).getInt();
		DqmEntitySaikuropusu = config.get("6_Spawn weight set individual(Nether)","Saikuropusu", DqmEntitySaikuropusu).getInt();
		DqmEntitySirubadebiru = config.get("6_Spawn weight set individual(Nether)","Sirubadebiru", DqmEntitySirubadebiru).getInt();
		DqmEntitySiryou = config.get("6_Spawn weight set individual(Nether)","Siryou", DqmEntitySiryou).getInt();
		DqmEntitySiryounokisi = config.get("6_Spawn weight set individual(Nether)","Siryounokisi", DqmEntitySiryounokisi).getInt();
		DqmEntitySodofantomu = config.get("6_Spawn weight set individual(Nether)","Sodofantomu", DqmEntitySodofantomu).getInt();
		DqmEntityStarkimera = config.get("6_Spawn weight set individual(Nether)","Starkimera", DqmEntityStarkimera).getInt();
		DqmEntityStonman = config.get("6_Spawn weight set individual(Nether)","Stonman", DqmEntityStonman).getInt();
		DqmEntitySuraimubehomazun = config.get("6_Spawn weight set individual(Nether)","Suraimubehomazun", DqmEntitySuraimubehomazun).getInt();
		DqmEntitySuraimuhaitawa = config.get("6_Spawn weight set individual(Nether)","Suraimuhaitawa", DqmEntitySuraimuhaitawa).getInt();
		DqmEntitySuraimumadyura = config.get("6_Spawn weight set individual(Nether)","Suraimumadyura", DqmEntitySuraimumadyura).getInt();
		DqmEntityTororuking = config.get("6_Spawn weight set individual(Nether)","Tororuking", DqmEntityTororuking).getInt();
		//DqmEntityTubokku = config.get("6_Spawn weight set individual(Nether)","//Tubokku", //DqmEntityTubokku).getInt();
		DqmEntityUmibouzu = config.get("6_Spawn weight set individual(Nether)","Umibouzu", DqmEntityUmibouzu).getInt();
		DqmEntityEriminator = config.get("6_Spawn weight set individual(Nether)","Eriminator", DqmEntityEriminator).getInt();
		DqmEntityDarkdoriado = config.get("6_Spawn weight set individual(Nether)","Darkdoriado", DqmEntityDarkdoriado).getInt();
		DqmEntityShadopan = config.get("6_Spawn weight set individual(Nether)","Shadopan", DqmEntityShadopan).getInt();
		DqmEntityWhitepan2 = config.get("6_Spawn weight set individual(Nether)","Whitepan2", DqmEntityWhitepan2).getInt();


		config.setCategoryComment("7_Spawn weight set individual(End)", "this setting is mob spawn weight set for individual set mode.\nspawn rate : Low 1 <-  20(Middle) -> High");
		DqmEntityAkairai = config.get("7_Spawn weight set individual(End)","Akairai", DqmEntityAkairai).getInt();
		DqmEntityBassaimasin = config.get("7_Spawn weight set individual(End)","Bassaimasin", DqmEntityBassaimasin).getInt();
		DqmEntityBatorurex = config.get("7_Spawn weight set individual(End)","Batorurex", DqmEntityBatorurex).getInt();
		DqmEntityBiggumoai = config.get("7_Spawn weight set individual(End)","Biggumoai", DqmEntityBiggumoai).getInt();
		DqmEntityBurizado = config.get("7_Spawn weight set individual(End)","Burizado", DqmEntityBurizado).getInt();
		DqmEntityDakunaito = config.get("7_Spawn weight set individual(End)","Dakunaito", DqmEntityDakunaito).getInt();
		DqmEntityDarktororu = config.get("7_Spawn weight set individual(End)","Darktororu", DqmEntityDarktororu).getInt();

		DqmEntityDasudragon = config.get("7_Spawn weight set individual(End)","Dasudragon", DqmEntityDasudragon).getInt();
		DqmEntityDenga = config.get("7_Spawn weight set individual(End)","Denga", DqmEntityDenga).getInt();
		DqmEntityDesujakkaru = config.get("7_Spawn weight set individual(End)","Desujakkaru", DqmEntityDesujakkaru).getInt();
		DqmEntityDesunyago = config.get("7_Spawn weight set individual(End)","Desunyago", DqmEntityDesunyago).getInt();
		DqmEntityDragondarknaito = config.get("7_Spawn weight set individual(End)","Dragondarknaito", DqmEntityDragondarknaito).getInt();
		DqmEntityGamegonrejendo = config.get("7_Spawn weight set individual(End)","Gamegonrejendo", DqmEntityGamegonrejendo).getInt();
		DqmEntityGigantesu = config.get("7_Spawn weight set individual(End)","Gigantesu", DqmEntityGigantesu).getInt();
		DqmEntityGodraida = config.get("7_Spawn weight set individual(End)","Godraida", DqmEntityGodraida).getInt();
		DqmEntityGorudensuraimu = config.get("7_Spawn weight set individual(End)","Gorudensuraimu", DqmEntityGorudensuraimu).getInt();
		DqmEntityJigokunoyoroi = config.get("7_Spawn weight set individual(End)","Jigokunoyoroi", DqmEntityJigokunoyoroi).getInt();
		DqmEntityKagenokisi = config.get("7_Spawn weight set individual(End)","Kagenokisi", DqmEntityKagenokisi).getInt();
		DqmEntityManemane = config.get("7_Spawn weight set individual(End)","Manemane", DqmEntityManemane).getInt();
		DqmEntityPandorabox = config.get("7_Spawn weight set individual(End)","Pandorabox", DqmEntityPandorabox).getInt();
		DqmEntityRyuiso = config.get("7_Spawn weight set individual(End)","Ryuiso", DqmEntityRyuiso).getInt();
		DqmEntityTororubonba = config.get("7_Spawn weight set individual(End)","Tororubonba", DqmEntityTororubonba).getInt();
		DqmEntityDesusutoka = config.get("7_Spawn weight set individual(End)","Desusutoka", DqmEntityDesusutoka).getInt();
		DqmEntityShadopan2 = config.get("7_Spawn weight set individual(End)","Shadopan2", DqmEntityShadopan2).getInt();


		config.setCategoryComment("8_Spawn weight set individual(Metal)", "this setting is mob spawn weight set for individual set mode.\nspawn rate : Low 1 <-  20(Middle) -> High");
		DqmEntityMetaruburazazu  = config.get("8_Spawn weight set individual(Metal)","Metaruburazazu", DqmEntityMetaruburazazu ).getInt();
		DqmEntityMetasura = config.get("8_Spawn weight set individual(Metal)","Metasura", DqmEntityMetasura ).getInt();
		DqmEntityHagumeta = config.get("8_Spawn weight set individual(Metal)","Hagumeta", DqmEntityHagumeta ).getInt();
		DqmEntityDragometaru = config.get("8_Spawn weight set individual(Metal)","Dragometaru", DqmEntityDragometaru ).getInt();
		DqmEntityMetaking = config.get("8_Spawn weight set individual(Metal)","Metaking", DqmEntityMetaking ).getInt();
		DqmEntityDaiyamondosuraimu  = config.get("8_Spawn weight set individual(Metal)","Daiyamondosuraimu", DqmEntityDaiyamondosuraimu ).getInt();
		DqmEntityPuratinaking = config.get("8_Spawn weight set individual(Metal)","Puratinaking", DqmEntityPuratinaking ).getInt();
		//DqmEntityGoldenmetalslime  = config.get("8_Spawn weight set individual(Metal)","//Goldenmetalslime", //DqmEntityGoldenmetalslime ).getInt();
		DqmEntityHaguremetaruking = config.get("8_Spawn weight set individual(Metal)","Haguremetaruking", DqmEntityHaguremetaruking ).getInt();


		config.setCategoryComment("9_Spawn weight set individual(ETC)", "this setting is mob spawn weight set for individual set mode.\nspawn rate : Low 1 <-  20(Middle) -> High");
		DqmEntityPandorakibako = config.get("9_Spawn weight set individual(ETC)","Pandorakibako", DqmEntityPandorakibako).getInt();
		DqmEntityMimikkukibako = config.get("9_Spawn weight set individual(ETC)","Mimikkukibako", DqmEntityMimikkukibako).getInt();
		DqmEntityHitokuibako = config.get("9_Spawn weight set individual(ETC)","Hitokuibako", DqmEntityHitokuibako).getInt();
		DqmEntityFurosutogizumo = config.get("9_Spawn weight set individual(ETC)","Furosutogizumo", DqmEntityFurosutogizumo).getInt();
		DqmEntityHiitogizumo = config.get("9_Spawn weight set individual(ETC)","Hiitogizumo", DqmEntityHiitogizumo).getInt();
		DqmEntitySuraimuking = config.get("9_Spawn weight set individual(ETC)","Suraimuking", DqmEntitySuraimuking).getInt();
		DqmEntityKingbesu = config.get("9_Spawn weight set individual(ETC)","Kingbesu", DqmEntityKingbesu).getInt();
		DqmEntityGizumo = config.get("9_Spawn weight set individual(ETC)","Gizumo", DqmEntityGizumo).getInt();
		DqmEntityTubo = config.get("9_Spawn weight set individual(ETC)","Tubo", DqmEntityTubo).getInt();
		config.save();
	}
}
