package dqr.entity.petEntity;

import cpw.mods.fml.common.registry.EntityRegistry;
import dqr.DQR;
import dqr.entity.petEntity.petBoss.DqmPetEntityDesupisaro1;
import dqr.entity.petEntity.petBoss.DqmPetEntityDesupisaro2;
import dqr.entity.petEntity.petBoss.DqmPetEntityDesupisaro3;
import dqr.entity.petEntity.petBoss.DqmPetEntityEsterk;
import dqr.entity.petEntity.petBoss.DqmPetEntityGod;
import dqr.entity.petEntity.petBoss.DqmPetEntityMasterdoragon;
import dqr.entity.petEntity.petBoss.DqmPetEntityRyuuou;
import dqr.entity.petEntity.petBoss.DqmPetEntityRyuuou2;
import dqr.entity.petEntity.petBoss.DqmPetEntityZoma;
import dqr.entity.petEntity.petDay.DqmPetEntityAyasiikage;
import dqr.entity.petEntity.petDay.DqmPetEntityBigCrow;
import dqr.entity.petEntity.petDay.DqmPetEntityBigguhatto;
import dqr.entity.petEntity.petDay.DqmPetEntityBubsura;
import dqr.entity.petEntity.petDay.DqmPetEntityBurauni;
import dqr.entity.petEntity.petDay.DqmPetEntityButisuraimu;
import dqr.entity.petEntity.petDay.DqmPetEntityDokuroarai;
import dqr.entity.petEntity.petDay.DqmPetEntityDoronuba;
import dqr.entity.petEntity.petDay.DqmPetEntityDorozara;
import dqr.entity.petEntity.petDay.DqmPetEntityDoruido;
import dqr.entity.petEntity.petDay.DqmPetEntityDragosuraimu;
import dqr.entity.petEntity.petDay.DqmPetEntityDucksbill;
import dqr.entity.petEntity.petDay.DqmPetEntityEbiruapple;
import dqr.entity.petEntity.petDay.DqmPetEntityFaratto;
import dqr.entity.petEntity.petDay.DqmPetEntityGaikotu;
import dqr.entity.petEntity.petDay.DqmPetEntityGizumoAZ;
import dqr.entity.petEntity.petDay.DqmPetEntityGuntaigani;
import dqr.entity.petEntity.petDay.DqmPetEntityHitokuikibako;
import dqr.entity.petEntity.petDay.DqmPetEntityHitokuisaberu;
import dqr.entity.petEntity.petDay.DqmPetEntityHoimisura;
import dqr.entity.petEntity.petDay.DqmPetEntityIkkakuusagi;
import dqr.entity.petEntity.petDay.DqmPetEntityItamogu;
import dqr.entity.petEntity.petDay.DqmPetEntityKimera;
import dqr.entity.petEntity.petDay.DqmPetEntityKirapan;
import dqr.entity.petEntity.petDay.DqmPetEntityKirikabuobake;
import dqr.entity.petEntity.petDay.DqmPetEntityMadohando;
import dqr.entity.petEntity.petDay.DqmPetEntityMomon;
import dqr.entity.petEntity.petDay.DqmPetEntityMomonja;
import dqr.entity.petEntity.petDay.DqmPetEntityObakekinoko;
import dqr.entity.petEntity.petDay.DqmPetEntityObakeumiusi;
import dqr.entity.petEntity.petDay.DqmPetEntityOnikozou;
import dqr.entity.petEntity.petDay.DqmPetEntityOokiduti;
import dqr.entity.petEntity.petDay.DqmPetEntityOokutibasi;
import dqr.entity.petEntity.petDay.DqmPetEntityOomedama;
import dqr.entity.petEntity.petDay.DqmPetEntityOonamekuji;
import dqr.entity.petEntity.petDay.DqmPetEntityPapetkozou;
import dqr.entity.petEntity.petDay.DqmPetEntityPurizunyan;
import dqr.entity.petEntity.petDay.DqmPetEntityRemonsuraimu;
import dqr.entity.petEntity.petDay.DqmPetEntityRippusu;
import dqr.entity.petEntity.petDay.DqmPetEntityRiripat;
import dqr.entity.petEntity.petDay.DqmPetEntitySabotenboru;
import dqr.entity.petEntity.petDay.DqmPetEntitySibirekurage;
import dqr.entity.petEntity.petDay.DqmPetEntitySimasimacat;
import dqr.entity.petEntity.petDay.DqmPetEntitySirudokozou;
import dqr.entity.petEntity.petDay.DqmPetEntitySukippaa;
import dqr.entity.petEntity.petDay.DqmPetEntitySunomon;
import dqr.entity.petEntity.petDay.DqmPetEntitySupini;
import dqr.entity.petEntity.petDay.DqmPetEntitySura;
import dqr.entity.petEntity.petDay.DqmPetEntitySuraimubesu;
import dqr.entity.petEntity.petDay.DqmPetEntitySuraimunaito;
import dqr.entity.petEntity.petDay.DqmPetEntitySuraimutawa;
import dqr.entity.petEntity.petDay.DqmPetEntitySuraimutumuri;
import dqr.entity.petEntity.petDay.DqmPetEntityTogebouzu;
import dqr.entity.petEntity.petDay.DqmPetEntityTukaima;
import dqr.entity.petEntity.petDay.DqmPetEntityUzusioking;
import dqr.entity.petEntity.petDay.DqmPetEntityWaraibukuro;
import dqr.entity.petEntity.petDay.DqmPetEntityZinmentyou;
import dqr.entity.petEntity.petDay.DqmPetEntityZukkinya;
import dqr.entity.petEntity.petEnd.DqmPetEntityAkairai;
import dqr.entity.petEntity.petEnd.DqmPetEntityBassaimasin;
import dqr.entity.petEntity.petEnd.DqmPetEntityBatorurex;
import dqr.entity.petEntity.petEnd.DqmPetEntityBiggumoai;
import dqr.entity.petEntity.petEnd.DqmPetEntityBurizado;
import dqr.entity.petEntity.petEnd.DqmPetEntityDakuhobitto;
import dqr.entity.petEntity.petEnd.DqmPetEntityDakunaito;
import dqr.entity.petEntity.petEnd.DqmPetEntityDarktororu;
import dqr.entity.petEntity.petEnd.DqmPetEntityDasudragon;
import dqr.entity.petEntity.petEnd.DqmPetEntityDenga;
import dqr.entity.petEntity.petEnd.DqmPetEntityDesujakkaru;
import dqr.entity.petEntity.petEnd.DqmPetEntityDesunyago;
import dqr.entity.petEntity.petEnd.DqmPetEntityDesusutoka;
import dqr.entity.petEntity.petEnd.DqmPetEntityDragondarknaito;
import dqr.entity.petEntity.petEnd.DqmPetEntityGamegonrejendo;
import dqr.entity.petEntity.petEnd.DqmPetEntityGigantesu;
import dqr.entity.petEntity.petEnd.DqmPetEntityGodraida;
import dqr.entity.petEntity.petEnd.DqmPetEntityGorudensuraimu;
import dqr.entity.petEntity.petEnd.DqmPetEntityJigokunoyoroi;
import dqr.entity.petEntity.petEnd.DqmPetEntityKagenokisi;
import dqr.entity.petEntity.petEnd.DqmPetEntityManemane;
import dqr.entity.petEntity.petEnd.DqmPetEntityPandorabox;
import dqr.entity.petEntity.petEnd.DqmPetEntityRyuiso;
import dqr.entity.petEntity.petEnd.DqmPetEntityShadopan2;
import dqr.entity.petEntity.petEnd.DqmPetEntityTororubonba;
import dqr.entity.petEntity.petEtc.DqmPetEntityFurosutogizumo;
import dqr.entity.petEntity.petEtc.DqmPetEntityGizumo;
import dqr.entity.petEntity.petEtc.DqmPetEntityHiitogizumo;
import dqr.entity.petEntity.petEtc.DqmPetEntityHitokuibako;
import dqr.entity.petEntity.petEtc.DqmPetEntityKingbesu;
import dqr.entity.petEntity.petEtc.DqmPetEntityMimikkukibako;
import dqr.entity.petEntity.petEtc.DqmPetEntityNorowaretaturugi;
import dqr.entity.petEntity.petEtc.DqmPetEntityPandorakibako;
import dqr.entity.petEntity.petEtc.DqmPetEntitySuraimuking;
import dqr.entity.petEntity.petEtc.DqmPetEntityTubo;
import dqr.entity.petEntity.petHell.DqmPetEntityAnkokumajin;
import dqr.entity.petEntity.petHell.DqmPetEntityAroinpu;
import dqr.entity.petEntity.petHell.DqmPetEntityBaburuking;
import dqr.entity.petEntity.petHell.DqmPetEntityBarakku;
import dqr.entity.petEntity.petHell.DqmPetEntityBariidodog;
import dqr.entity.petEntity.petHell.DqmPetEntityBehomasuraimu;
import dqr.entity.petEntity.petHell.DqmPetEntityBiggufeisu;
import dqr.entity.petEntity.petHell.DqmPetEntityBighanma;
import dqr.entity.petEntity.petHell.DqmPetEntityBosutororu;
import dqr.entity.petEntity.petHell.DqmPetEntityBoureikensi;
import dqr.entity.petEntity.petHell.DqmPetEntityBuraddosodo;
import dqr.entity.petEntity.petHell.DqmPetEntityBurakkubejita;
import dqr.entity.petEntity.petHell.DqmPetEntityDarkdoriado;
import dqr.entity.petEntity.petHell.DqmPetEntityDarkslime;
import dqr.entity.petEntity.petHell.DqmPetEntityDeddopekka;
import dqr.entity.petEntity.petHell.DqmPetEntityDgizumo;
import dqr.entity.petEntity.petHell.DqmPetEntityDollmaster;
import dqr.entity.petEntity.petHell.DqmPetEntityDoragonsoruja;
import dqr.entity.petEntity.petHell.DqmPetEntityDqmdragon;
import dqr.entity.petEntity.petHell.DqmPetEntityDragonnaito;
import dqr.entity.petEntity.petHell.DqmPetEntityDragonraida;
import dqr.entity.petEntity.petHell.DqmPetEntityEriminator;
import dqr.entity.petEntity.petHell.DqmPetEntityFureimu;
import dqr.entity.petEntity.petHell.DqmPetEntityGamegon;
import dqr.entity.petEntity.petHell.DqmPetEntityGamegonload;
import dqr.entity.petEntity.petHell.DqmPetEntityGanirasu;
import dqr.entity.petEntity.petHell.DqmPetEntityGoldman;
import dqr.entity.petEntity.petHell.DqmPetEntityGoremu;
import dqr.entity.petEntity.petHell.DqmPetEntityGorudentotemu;
import dqr.entity.petEntity.petHell.DqmPetEntityHotatewarabi;
import dqr.entity.petEntity.petHell.DqmPetEntityJigokunohasami;
import dqr.entity.petEntity.petHell.DqmPetEntityKedamon;
import dqr.entity.petEntity.petHell.DqmPetEntityKemunkurusu;
import dqr.entity.petEntity.petHell.DqmPetEntityKimendousi;
import dqr.entity.petEntity.petHell.DqmPetEntityKiraama;
import dqr.entity.petEntity.petHell.DqmPetEntityKirakurabu;
import dqr.entity.petEntity.petHell.DqmPetEntityKiramasin;
import dqr.entity.petEntity.petHell.DqmPetEntityKiramasin2;
import dqr.entity.petEntity.petHell.DqmPetEntityKisudragon;
import dqr.entity.petEntity.petHell.DqmPetEntityKuinsuraimu;
import dqr.entity.petEntity.petHell.DqmPetEntityMagematango;
import dqr.entity.petEntity.petHell.DqmPetEntityMagemomonja;
import dqr.entity.petEntity.petHell.DqmPetEntityMagumaron;
import dqr.entity.petEntity.petHell.DqmPetEntityMajikaruhatto;
import dqr.entity.petEntity.petHell.DqmPetEntityMaounokage;
import dqr.entity.petEntity.petHell.DqmPetEntityMaporena;
import dqr.entity.petEntity.petHell.DqmPetEntityMegazarurokku;
import dqr.entity.petEntity.petHell.DqmPetEntityMetaruhanta;
import dqr.entity.petEntity.petHell.DqmPetEntityMimikku;
import dqr.entity.petEntity.petHell.DqmPetEntityPapettoman;
import dqr.entity.petEntity.petHell.DqmPetEntityPikusi;
import dqr.entity.petEntity.petHell.DqmPetEntityPombom;
import dqr.entity.petEntity.petHell.DqmPetEntityPuyon;
import dqr.entity.petEntity.petHell.DqmPetEntityRedsaikuron;
import dqr.entity.petEntity.petHell.DqmPetEntitySaikuropusu;
import dqr.entity.petEntity.petHell.DqmPetEntityShadopan;
import dqr.entity.petEntity.petHell.DqmPetEntitySirubadebiru;
import dqr.entity.petEntity.petHell.DqmPetEntitySiryou;
import dqr.entity.petEntity.petHell.DqmPetEntitySiryounokisi;
import dqr.entity.petEntity.petHell.DqmPetEntitySodofantomu;
import dqr.entity.petEntity.petHell.DqmPetEntityStarkimera;
import dqr.entity.petEntity.petHell.DqmPetEntityStonman;
import dqr.entity.petEntity.petHell.DqmPetEntitySuraimubehomazun;
import dqr.entity.petEntity.petHell.DqmPetEntitySuraimuhaitawa;
import dqr.entity.petEntity.petHell.DqmPetEntitySuraimumadyura;
import dqr.entity.petEntity.petHell.DqmPetEntityTororuking;
import dqr.entity.petEntity.petHell.DqmPetEntityTubokku;
import dqr.entity.petEntity.petHell.DqmPetEntityUmibouzu;
import dqr.entity.petEntity.petMetaru.DqmPetEntityDaiyamondosuraimu;
import dqr.entity.petEntity.petMetaru.DqmPetEntityDragometaru;
import dqr.entity.petEntity.petMetaru.DqmPetEntityGoldenmetalslime;
import dqr.entity.petEntity.petMetaru.DqmPetEntityHagumeta;
import dqr.entity.petEntity.petMetaru.DqmPetEntityHaguremetaruking;
import dqr.entity.petEntity.petMetaru.DqmPetEntityMetaking;
import dqr.entity.petEntity.petMetaru.DqmPetEntityMetaruburazazu;
import dqr.entity.petEntity.petMetaru.DqmPetEntityMetasura;
import dqr.entity.petEntity.petMetaru.DqmPetEntityPuratinaking;
import dqr.entity.petEntity.petNight.DqmPetEntityAkumanosyo;
import dqr.entity.petEntity.petNight.DqmPetEntityAkumanotubo;
import dqr.entity.petEntity.petNight.DqmPetEntityAnimaruzonbi;
import dqr.entity.petEntity.petNight.DqmPetEntityArumiraji;
import dqr.entity.petEntity.petNight.DqmPetEntityAxedoragon;
import dqr.entity.petEntity.petNight.DqmPetEntityBaburin;
import dqr.entity.petEntity.petNight.DqmPetEntityBakudanbebi;
import dqr.entity.petEntity.petNight.DqmPetEntityBakudaniwa;
import dqr.entity.petEntity.petNight.DqmPetEntityBebisatan;
import dqr.entity.petEntity.petNight.DqmPetEntityBehoimisuraimu;
import dqr.entity.petEntity.petNight.DqmPetEntityBehoimusuraimu;
import dqr.entity.petEntity.petNight.DqmPetEntityBerobero;
import dqr.entity.petEntity.petNight.DqmPetEntityBeronyaago;
import dqr.entity.petEntity.petNight.DqmPetEntityBesuking;
import dqr.entity.petEntity.petNight.DqmPetEntityBuchunpa;
import dqr.entity.petEntity.petNight.DqmPetEntityBuraddihando;
import dqr.entity.petEntity.petNight.DqmPetEntityButtizukinya;
import dqr.entity.petEntity.petNight.DqmPetEntityDansunidoru;
import dqr.entity.petEntity.petNight.DqmPetEntityDesufuratta;
import dqr.entity.petEntity.petNight.DqmPetEntityDokuyazukin;
import dqr.entity.petEntity.petNight.DqmPetEntityDoraki;
import dqr.entity.petEntity.petNight.DqmPetEntityDorakima;
import dqr.entity.petEntity.petNight.DqmPetEntityDoroningyou;
import dqr.entity.petEntity.petNight.DqmPetEntityEnzeruslime;
import dqr.entity.petEntity.petNight.DqmPetEntityFgizumo;
import dqr.entity.petEntity.petNight.DqmPetEntityGaikotukensi;
import dqr.entity.petEntity.petNight.DqmPetEntityGappurin;
import dqr.entity.petEntity.petNight.DqmPetEntityGenjutusi;
import dqr.entity.petEntity.petNight.DqmPetEntityGhost;
import dqr.entity.petEntity.petNight.DqmPetEntityGorotuki;
import dqr.entity.petEntity.petNight.DqmPetEntityHerughost;
import dqr.entity.petEntity.petNight.DqmPetEntityHgizumo;
import dqr.entity.petEntity.petNight.DqmPetEntityHitokuiga;
import dqr.entity.petEntity.petNight.DqmPetEntityHoroghost;
import dqr.entity.petEntity.petNight.DqmPetEntityHyouganmajin;
import dqr.entity.petEntity.petNight.DqmPetEntityJeriman;
import dqr.entity.petEntity.petNight.DqmPetEntityKingsura;
import dqr.entity.petEntity.petNight.DqmPetEntityKirapan2;
import dqr.entity.petEntity.petNight.DqmPetEntityKirasuko;
import dqr.entity.petEntity.petNight.DqmPetEntityMapetman;
import dqr.entity.petEntity.petNight.DqmPetEntityMarinsuraimu;
import dqr.entity.petEntity.petNight.DqmPetEntityMatango;
import dqr.entity.petEntity.petNight.DqmPetEntityMeijidoraki;
import dqr.entity.petEntity.petNight.DqmPetEntityMeijikimera;
import dqr.entity.petEntity.petNight.DqmPetEntityMeragosuto;
import dqr.entity.petEntity.petNight.DqmPetEntityMetaruhantaken;
import dqr.entity.petEntity.petNight.DqmPetEntityMetaruraida;
import dqr.entity.petEntity.petNight.DqmPetEntityMetoroghost;
import dqr.entity.petEntity.petNight.DqmPetEntityMinidemon;
import dqr.entity.petEntity.petNight.DqmPetEntityMokomokojuu;
import dqr.entity.petEntity.petNight.DqmPetEntityMrippusu;
import dqr.entity.petEntity.petNight.DqmPetEntityNightwalker;
import dqr.entity.petEntity.petNight.DqmPetEntityObakekyandoru;
import dqr.entity.petEntity.petNight.DqmPetEntityOdoruhouseki;
import dqr.entity.petEntity.petNight.DqmPetEntityPinkmomon;
import dqr.entity.petEntity.petNight.DqmPetEntityRaimusuraimu;
import dqr.entity.petEntity.petNight.DqmPetEntitySamayoutamasii;
import dqr.entity.petEntity.petNight.DqmPetEntitySamayouyoroi;
import dqr.entity.petEntity.petNight.DqmPetEntitySibireageha;
import dqr.entity.petEntity.petNight.DqmPetEntitySibiredanbira;
import dqr.entity.petEntity.petNight.DqmPetEntitySkullgaroo;
import dqr.entity.petEntity.petNight.DqmPetEntitySumairurokku;
import dqr.entity.petEntity.petNight.DqmPetEntitySumoruguru;
import dqr.entity.petEntity.petNight.DqmPetEntitySupekutetto;
import dqr.entity.petEntity.petNight.DqmPetEntitySura2;
import dqr.entity.petEntity.petNight.DqmPetEntitySuraimubogu;
import dqr.entity.petEntity.petNight.DqmPetEntitySuraimuburesu;
import dqr.entity.petEntity.petNight.DqmPetEntitySyado;
import dqr.entity.petEntity.petNight.DqmPetEntityTahodoraki;
import dqr.entity.petEntity.petNight.DqmPetEntityTomosibikozou;
import dqr.entity.petEntity.petNight.DqmPetEntityTonburero;
import dqr.entity.petEntity.petNight.DqmPetEntityTororu;
import dqr.entity.petEntity.petNight.DqmPetEntityTutiwarasi;
import dqr.entity.petEntity.petNight.DqmPetEntityUmiusi;
import dqr.entity.petEntity.petNight.DqmPetEntityYouganmajin;
import dqr.entity.petEntity.petSP.DqmPetEntityAtorasu;
import dqr.entity.petEntity.petSP.DqmPetEntityBazuzu;
import dqr.entity.petEntity.petSP.DqmPetEntityBlackchack;
import dqr.entity.petEntity.petSP.DqmPetEntityBurasu;
import dqr.entity.petEntity.petSP.DqmPetEntityDarkRamia;
import dqr.entity.petEntity.petSP.DqmPetEntityFureizado;
import dqr.entity.petEntity.petSP.DqmPetEntityGodonheddo;
import dqr.entity.petEntity.petSP.DqmPetEntityKandata;
import dqr.entity.petEntity.petSP.DqmPetEntityKandatakobun;
import dqr.entity.petEntity.petSP.DqmPetEntityKinghidora;
import dqr.entity.petEntity.petSP.DqmPetEntityKiramajinga;
import dqr.entity.petEntity.petSP.DqmPetEntityKiratoti;
import dqr.entity.petEntity.petSP.DqmPetEntityMashougumo;
import dqr.entity.petEntity.petSP.DqmPetEntityMasso;
import dqr.entity.petEntity.petSP.DqmPetEntityOrutega;
import dqr.entity.petEntity.petSP.DqmPetEntityPisaronaito;
import dqr.entity.petEntity.petSP.DqmPetEntityPuremiasuraimu;
import dqr.entity.petEntity.petSP.DqmPetEntitySirubamanto;
import dqr.entity.petEntity.petSP.DqmPetEntitySuraimuemperor;
import dqr.entity.petEntity.petSP.DqmPetEntitySuraimujeneraru;
import dqr.entity.petEntity.petSP.DqmPetEntityTattyan;
import dqr.entity.petEntity.petSP.DqmPetEntityTororubakkosu;
import dqr.entity.petEntity.petSP.DqmPetEntityUragirikozou;
import dqr.entity.petEntity.petSP.DqmPetEntityWanpakusatan;
import dqr.entity.petEntity.petSP.DqmPetEntityYamatanooroti;
import dqr.entity.petEntity.petTensei.DqmPetEntityArukemisuton;
import dqr.entity.petEntity.petTensei.DqmPetEntityBebingosatan;
import dqr.entity.petEntity.petTensei.DqmPetEntityDebirurodo;
import dqr.entity.petEntity.petTensei.DqmPetEntityGoldmanto;
import dqr.entity.petEntity.petTensei.DqmPetEntityGorudenkon;
import dqr.entity.petEntity.petTensei.DqmPetEntityHatonaito;
import dqr.entity.petEntity.petTensei.DqmPetEntityKirapike;
import dqr.entity.petEntity.petTensei.DqmPetEntityKuinmomon;
import dqr.entity.petEntity.petTensei.DqmPetEntityMaaburun;
import dqr.entity.petEntity.petTensei.DqmPetEntityMadrainbow;
import dqr.entity.petEntity.petTensei.DqmPetEntityMetaruhoimin;
import dqr.entity.petEntity.petTensei.DqmPetEntityMomoirosansimai;
import dqr.entity.petEntity.petTensei.DqmPetEntityMoonkimera;
import dqr.entity.petEntity.petTensei.DqmPetEntityNoroinoiwa;
import dqr.entity.petEntity.petTensei.DqmPetEntityPinkbonbon;
import dqr.entity.petEntity.petTensei.DqmPetEntityReddoatya;
import dqr.entity.petEntity.petTensei.DqmPetEntitySabotengold;
import dqr.entity.petEntity.petTensei.DqmPetEntitySeigin;
import dqr.entity.petEntity.petTensei.DqmPetEntityShuvaluts;
import dqr.entity.petEntity.petTensei.DqmPetEntitySirudoaniki;
import dqr.entity.petEntity.petTensei.DqmPetEntitySweetbag;
import dqr.entity.petEntity.petTensei.DqmPetEntityTaipug;
import dqr.entity.petEntity.petTensei.DqmPetEntityTogekonbou;
import dqr.entity.petEntity.petTensei.DqmPetEntityTumurinmama;
import dqr.entity.petEntity.petTensei.DqmPetEntityTyokonuba;

public class PetRegister {

	private int idxID = DQR.conf.PetMonsterIDidx;

	public PetRegister()
	{
		//EntityRegistry.registerModEntity(EntityMeleeSkeleton.class, "PetMeleeSkeleton", 0, DQR.instance, 250, 1, false);
		//EntityRegistry.registerModEntity(DqmPetEntitySura.class, "PetSuraimu", idxID + 8000, DQR.instance, 250, 1, false);
		//EntityRegistry.registerModEntity(DqmPetEntityKingsura.class, "PetKingsura", idxID + 8001, DQR.instance, 250, 1, false);
		//EntityRegistry.registerModEntity(EntitySample.class, "PetSampleEntity", 99, DQR.instance, 250, 1, false);

		EntityRegistry.registerModEntity(DqmPetEntityAyasiikage.class, "PetAyasiikage", idxID + 4, DQR.instance, 250, 1, false);
		EntityRegistry.registerModEntity(DqmPetEntityBigCrow.class, "PetBigCrow", idxID + 5, DQR.instance, 250, 1, false);
		EntityRegistry.registerModEntity(DqmPetEntityBigguhatto.class, "PetBigguhatto", idxID + 6, DQR.instance, 250, 1, false);
		EntityRegistry.registerModEntity(DqmPetEntityBubsura.class, "PetBubsura", idxID + 7, DQR.instance, 250, 1, false);
		EntityRegistry.registerModEntity(DqmPetEntityBurauni.class, "PetBurauni", idxID + 8, DQR.instance, 250, 1, false);
		EntityRegistry.registerModEntity(DqmPetEntityButisuraimu.class, "PetButisuraimu", idxID + 9, DQR.instance, 250, 1, false);
		EntityRegistry.registerModEntity(DqmPetEntityDokuroarai.class, "PetDokuroarai", idxID + 10, DQR.instance, 250, 1, false);
		EntityRegistry.registerModEntity(DqmPetEntityDoronuba.class, "PetDoronuba", idxID + 11, DQR.instance, 250, 1, false);
		EntityRegistry.registerModEntity(DqmPetEntityDorozara.class, "PetDorozara", idxID + 12, DQR.instance, 250, 1, false);
		EntityRegistry.registerModEntity(DqmPetEntityDragosuraimu.class, "PetDragosuraimu", idxID + 13, DQR.instance, 250, 1, false);
		EntityRegistry.registerModEntity(DqmPetEntityDucksbill.class, "PetDucksbill", idxID + 14, DQR.instance, 250, 1, false);
		EntityRegistry.registerModEntity(DqmPetEntityGizumo.class, "PetGizumo", idxID + 15, DQR.instance, 250, 1, false);
		EntityRegistry.registerModEntity(DqmPetEntityGizumoAZ.class, "PetGizumoAZ", idxID + 16, DQR.instance, 250, 1, false);
		EntityRegistry.registerModEntity(DqmPetEntityGuntaigani.class, "PetGuntaigani", idxID + 17, DQR.instance, 250, 1, false);
		EntityRegistry.registerModEntity(DqmPetEntityHitokuikibako.class, "PetHitokuikibako", idxID + 18, DQR.instance, 250, 1, false);
		EntityRegistry.registerModEntity(DqmPetEntityHitokuisaberu.class, "PetHitokuisaberu", idxID + 19, DQR.instance, 250, 1, false);
		EntityRegistry.registerModEntity(DqmPetEntityHoimisura.class, "PetHoimisura", idxID + 20, DQR.instance, 250, 1, false);
		EntityRegistry.registerModEntity(DqmPetEntityIkkakuusagi.class, "PetIkkakuusagi", idxID + 21, DQR.instance, 250, 1, false);
		EntityRegistry.registerModEntity(DqmPetEntityItamogu.class, "PetItamogu", idxID + 22, DQR.instance, 250, 1, false);
		EntityRegistry.registerModEntity(DqmPetEntityKimera.class, "PetKimera", idxID + 23, DQR.instance, 250, 1, false);
		EntityRegistry.registerModEntity(DqmPetEntityKirapan.class, "PetKirapan", idxID + 24, DQR.instance, 250, 1, false);
		EntityRegistry.registerModEntity(DqmPetEntityKirikabuobake.class, "PetKirikabuobake", idxID + 25, DQR.instance, 250, 1, false);
		EntityRegistry.registerModEntity(DqmPetEntityMadohando.class, "PetMadohando", idxID + 26, DQR.instance, 250, 1, false);
		EntityRegistry.registerModEntity(DqmPetEntityMomon.class, "PetMomon", idxID + 27, DQR.instance, 250, 1, false);
		EntityRegistry.registerModEntity(DqmPetEntityMomonja.class, "PetMomonja", idxID + 28, DQR.instance, 250, 1, false);
		EntityRegistry.registerModEntity(DqmPetEntityObakekinoko.class, "PetObakekinoko", idxID + 29, DQR.instance, 250, 1, false);
		EntityRegistry.registerModEntity(DqmPetEntityObakeumiusi.class, "PetObakeumiusi", idxID + 30, DQR.instance, 250, 1, false);
		EntityRegistry.registerModEntity(DqmPetEntityOnikozou.class, "PetOnikozou", idxID + 31, DQR.instance, 250, 1, false);
		EntityRegistry.registerModEntity(DqmPetEntityOokiduti.class, "PetOokiduti", idxID + 32, DQR.instance, 250, 1, false);
		EntityRegistry.registerModEntity(DqmPetEntityOokutibasi.class, "PetOokutibasi", idxID + 33, DQR.instance, 250, 1, false);
		EntityRegistry.registerModEntity(DqmPetEntityOomedama.class, "PetOomedama", idxID + 34, DQR.instance, 250, 1, false);
		EntityRegistry.registerModEntity(DqmPetEntityOonamekuji.class, "PetOonamekuji", idxID + 35, DQR.instance, 250, 1, false);
		EntityRegistry.registerModEntity(DqmPetEntityPapetkozou.class, "PetPapetkozou", idxID + 36, DQR.instance, 250, 1, false);
		EntityRegistry.registerModEntity(DqmPetEntityPurizunyan.class, "PetPurizunyan", idxID + 37, DQR.instance, 250, 1, false);
		EntityRegistry.registerModEntity(DqmPetEntityRippusu.class, "PetRippusu", idxID + 38, DQR.instance, 250, 1, false);
		EntityRegistry.registerModEntity(DqmPetEntityRiripat.class, "PetRiripat", idxID + 39, DQR.instance, 250, 1, false);
		EntityRegistry.registerModEntity(DqmPetEntitySibirekurage.class, "PetSibirekurage", idxID + 40, DQR.instance, 250, 1, false);
		EntityRegistry.registerModEntity(DqmPetEntitySimasimacat.class, "PetSimasimacat", idxID + 41, DQR.instance, 250, 1, false);
		EntityRegistry.registerModEntity(DqmPetEntitySirudokozou.class, "PetSirudokozou", idxID + 42, DQR.instance, 250, 1, false);
		EntityRegistry.registerModEntity(DqmPetEntitySukippaa.class, "PetSukippaa", idxID + 43, DQR.instance, 250, 1, false);
		EntityRegistry.registerModEntity(DqmPetEntitySunomon.class, "PetSunomon", idxID + 44, DQR.instance, 250, 1, false);
		EntityRegistry.registerModEntity(DqmPetEntitySupini.class, "PetSupini", idxID + 45, DQR.instance, 250, 1, false);
		EntityRegistry.registerModEntity(DqmPetEntitySura.class, "PetSura", idxID + 46, DQR.instance, 250, 1, false);
		EntityRegistry.registerModEntity(DqmPetEntitySuraimubesu.class, "PetSuraimubesu", idxID + 47, DQR.instance, 250, 1, false);
		EntityRegistry.registerModEntity(DqmPetEntitySuraimunaito.class, "PetSuraimunaito", idxID + 48, DQR.instance, 250, 1, false);
		EntityRegistry.registerModEntity(DqmPetEntitySuraimutawa.class, "PetSuraimutawa", idxID + 49, DQR.instance, 250, 1, false);
		EntityRegistry.registerModEntity(DqmPetEntitySuraimutumuri.class, "PetSuraimutumuri", idxID + 50, DQR.instance, 250, 1, false);
		EntityRegistry.registerModEntity(DqmPetEntityTogebouzu.class, "PetTogebouzu", idxID + 51, DQR.instance, 250, 1, false);
		EntityRegistry.registerModEntity(DqmPetEntityTubo.class, "PetTubo", idxID + 52, DQR.instance, 250, 1, false);
		EntityRegistry.registerModEntity(DqmPetEntityTukaima.class, "PetTukaima", idxID + 53, DQR.instance, 250, 1, false);
		EntityRegistry.registerModEntity(DqmPetEntityUzusioking.class, "PetUzusioking", idxID + 54, DQR.instance, 250, 1, false);
		EntityRegistry.registerModEntity(DqmPetEntityWaraibukuro.class, "PetWaraibukuro", idxID + 55, DQR.instance, 250, 1, false);
		EntityRegistry.registerModEntity(DqmPetEntityZinmentyou.class, "PetZinmentyou", idxID + 56, DQR.instance, 250, 1, false);
		EntityRegistry.registerModEntity(DqmPetEntityZukkinya.class, "PetZukkinya", idxID + 57, DQR.instance, 250, 1, false);


		EntityRegistry.registerModEntity(DqmPetEntityAkumanosyo.class, "PetAkumanosyo", idxID + 60, DQR.instance, 250, 1, false);
		EntityRegistry.registerModEntity(DqmPetEntityAkumanotubo.class, "PetAkumanotubo", idxID + 61, DQR.instance, 250, 1, false);
		EntityRegistry.registerModEntity(DqmPetEntityAnimaruzonbi.class, "PetAnimaruzonbi", idxID + 64, DQR.instance, 250, 1, false);
		EntityRegistry.registerModEntity(DqmPetEntityArumiraji.class, "PetArumiraji", idxID + 65, DQR.instance, 250, 1, false);
		EntityRegistry.registerModEntity(DqmPetEntityBaburin.class, "PetBaburin", idxID + 66, DQR.instance, 250, 1, false);
		EntityRegistry.registerModEntity(DqmPetEntityBakudanbebi.class, "PetBakudanbebi", idxID + 67, DQR.instance, 250, 1, false);
		EntityRegistry.registerModEntity(DqmPetEntityBakudaniwa.class, "PetBakudaniwa", idxID + 68, DQR.instance, 250, 1, false);
		EntityRegistry.registerModEntity(DqmPetEntityBebisatan.class, "PetBebisatan", idxID + 69, DQR.instance, 250, 1, false);
		EntityRegistry.registerModEntity(DqmPetEntityBehoimisuraimu.class, "PetBehoimisuraimu", idxID + 70, DQR.instance, 250, 1, false);
		EntityRegistry.registerModEntity(DqmPetEntityBehoimusuraimu.class, "PetBehoimusuraimu", idxID + 71, DQR.instance, 250, 1, false);
		EntityRegistry.registerModEntity(DqmPetEntityBerobero.class, "PetBerobero", idxID + 72, DQR.instance, 250, 1, false);
		EntityRegistry.registerModEntity(DqmPetEntityBeronyaago.class, "PetBeronyaago", idxID + 73, DQR.instance, 250, 1, false);
		EntityRegistry.registerModEntity(DqmPetEntityBuchunpa.class, "PetBuchunpa", idxID + 74, DQR.instance, 250, 1, false);
		EntityRegistry.registerModEntity(DqmPetEntityBuraddihando.class, "PetBuraddihando", idxID + 75, DQR.instance, 250, 1, false);
		EntityRegistry.registerModEntity(DqmPetEntityButtizukinya.class, "PetButtizukinya", idxID + 76, DQR.instance, 250, 1, false);
		EntityRegistry.registerModEntity(DqmPetEntityDesufuratta.class, "PetDesufuratta", idxID + 77, DQR.instance, 250, 1, false);
		EntityRegistry.registerModEntity(DqmPetEntityDokuyazukin.class, "PetDokuyazukin", idxID + 78, DQR.instance, 250, 1, false);
		EntityRegistry.registerModEntity(DqmPetEntityDoraki.class, "PetDoraki", idxID + 79, DQR.instance, 250, 1, false);
		EntityRegistry.registerModEntity(DqmPetEntityDorakima.class, "PetDorakima", idxID + 80, DQR.instance, 250, 1, false);
		EntityRegistry.registerModEntity(DqmPetEntityEnzeruslime.class, "PetEnzeruslime", idxID + 81, DQR.instance, 250, 1, false);
		EntityRegistry.registerModEntity(DqmPetEntityFgizumo.class, "PetFgizumo", idxID + 82, DQR.instance, 250, 1, false);
		EntityRegistry.registerModEntity(DqmPetEntityFurosutogizumo.class, "PetFurosutogizumo", idxID + 83, DQR.instance, 250, 1, false);
		EntityRegistry.registerModEntity(DqmPetEntityGaikotukensi.class, "PetGaikotukensi", idxID + 84, DQR.instance, 250, 1, false);
		EntityRegistry.registerModEntity(DqmPetEntityGhost.class, "PetGhost", idxID + 85, DQR.instance, 250, 1, false);
		EntityRegistry.registerModEntity(DqmPetEntityGorudentotemu.class, "PetGorudentotemu", idxID + 86, DQR.instance, 250, 1, false);
		EntityRegistry.registerModEntity(DqmPetEntityHerughost.class, "PetHerughost", idxID + 87, DQR.instance, 250, 1, false);
		EntityRegistry.registerModEntity(DqmPetEntityHgizumo.class, "PetHgizumo", idxID + 88, DQR.instance, 250, 1, false);
		EntityRegistry.registerModEntity(DqmPetEntityHiitogizumo.class, "PetHiitogizumo", idxID + 89, DQR.instance, 250, 1, false);
		EntityRegistry.registerModEntity(DqmPetEntityHitokuibako.class, "PetHitokuibako", idxID + 90, DQR.instance, 250, 1, false);
		EntityRegistry.registerModEntity(DqmPetEntityHitokuiga.class, "PetHitokuiga", idxID + 91, DQR.instance, 250, 1, false);
		EntityRegistry.registerModEntity(DqmPetEntityHoroghost.class, "PetHoroghost", idxID + 92, DQR.instance, 250, 1, false);
		EntityRegistry.registerModEntity(DqmPetEntityHyouganmajin.class, "PetHyouganmajin", idxID + 93, DQR.instance, 250, 1, false);
		EntityRegistry.registerModEntity(DqmPetEntityJeriman.class, "PetJeriman", idxID + 94, DQR.instance, 250, 1, false);
		EntityRegistry.registerModEntity(DqmPetEntityKingsura.class, "PetKingsura", idxID + 95, DQR.instance, 250, 1, false);
		EntityRegistry.registerModEntity(DqmPetEntityKirapan2.class, "PetKirapan2", idxID + 96, DQR.instance, 250, 1, false);
		EntityRegistry.registerModEntity(DqmPetEntityKirasuko.class, "PetKirasuko", idxID + 97, DQR.instance, 250, 1, false);
		EntityRegistry.registerModEntity(DqmPetEntityMapetman.class, "PetMapetman", idxID + 98, DQR.instance, 250, 1, false);
		EntityRegistry.registerModEntity(DqmPetEntityMarinsuraimu.class, "PetMarinsuraimu", idxID + 99, DQR.instance, 250, 1, false);
		EntityRegistry.registerModEntity(DqmPetEntityMatango.class, "PetMatango", idxID + 100, DQR.instance, 250, 1, false);
		EntityRegistry.registerModEntity(DqmPetEntityMeijidoraki.class, "PetMeijidoraki", idxID + 101, DQR.instance, 250, 1, false);
		EntityRegistry.registerModEntity(DqmPetEntityMeijikimera.class, "PetMeijikimera", idxID + 102, DQR.instance, 250, 1, false);
		EntityRegistry.registerModEntity(DqmPetEntityMeragosuto.class, "PetMeragosuto", idxID + 103, DQR.instance, 250, 1, false);
		EntityRegistry.registerModEntity(DqmPetEntityMetaruraida.class, "PetMetaruraida", idxID + 104, DQR.instance, 250, 1, false);
		EntityRegistry.registerModEntity(DqmPetEntityMetoroghost.class, "PetMetoroghost", idxID + 105, DQR.instance, 250, 1, false);
		EntityRegistry.registerModEntity(DqmPetEntityMimikku.class, "PetMimikku", idxID + 106, DQR.instance, 250, 1, false);
		EntityRegistry.registerModEntity(DqmPetEntityMimikkukibako.class, "PetMimikkukibako", idxID + 107, DQR.instance, 250, 1, false);
		EntityRegistry.registerModEntity(DqmPetEntityMinidemon.class, "PetMinidemon", idxID + 108, DQR.instance, 250, 1, false);
		EntityRegistry.registerModEntity(DqmPetEntityMrippusu.class, "PetMrippusu", idxID + 109, DQR.instance, 250, 1, false);
		EntityRegistry.registerModEntity(DqmPetEntityNightwalker.class, "PetNightwalker", idxID + 110, DQR.instance, 250, 1, false);
		EntityRegistry.registerModEntity(DqmPetEntityObakekyandoru.class, "PetObakekyandoru", idxID + 111, DQR.instance, 250, 1, false);
		EntityRegistry.registerModEntity(DqmPetEntityOdoruhouseki.class, "PetOdoruhouseki", idxID + 112, DQR.instance, 250, 1, false);
		EntityRegistry.registerModEntity(DqmPetEntityPinkmomon.class, "PetPinkmomon", idxID + 113, DQR.instance, 250, 1, false);
		EntityRegistry.registerModEntity(DqmPetEntitySamayoutamasii.class, "PetSamayoutamasii", idxID + 114, DQR.instance, 250, 1, false);
		EntityRegistry.registerModEntity(DqmPetEntitySibireageha.class, "PetSibireageha", idxID + 115, DQR.instance, 250, 1, false);
		EntityRegistry.registerModEntity(DqmPetEntitySibiredanbira.class, "PetSibiredanbira", idxID + 116, DQR.instance, 250, 1, false);
		EntityRegistry.registerModEntity(DqmPetEntitySkullgaroo.class, "PetSkullgaroo", idxID + 117, DQR.instance, 250, 1, false);
		EntityRegistry.registerModEntity(DqmPetEntitySumairurokku.class, "PetSumairurokku", idxID + 118, DQR.instance, 250, 1, false);
		EntityRegistry.registerModEntity(DqmPetEntitySumoruguru.class, "PetSumoruguru", idxID + 119, DQR.instance, 250, 1, false);
		EntityRegistry.registerModEntity(DqmPetEntitySupekutetto.class, "PetSupekutetto", idxID + 120, DQR.instance, 250, 1, false);
		EntityRegistry.registerModEntity(DqmPetEntitySura2.class, "PetSura2", idxID + 121, DQR.instance, 250, 1, false);
		EntityRegistry.registerModEntity(DqmPetEntitySuraimubogu.class, "PetSuraimubogu", idxID + 122, DQR.instance, 250, 1, false);
		EntityRegistry.registerModEntity(DqmPetEntitySuraimuburesu.class, "PetSuraimuburesu", idxID + 123, DQR.instance, 250, 1, false);
		EntityRegistry.registerModEntity(DqmPetEntitySuraimuking.class, "PetSuraimuking", idxID + 124, DQR.instance, 250, 1, false);
		EntityRegistry.registerModEntity(DqmPetEntitySyado.class, "PetSyado", idxID + 125, DQR.instance, 250, 1, false);
		EntityRegistry.registerModEntity(DqmPetEntityTahodoraki.class, "PetTahodoraki", idxID + 126, DQR.instance, 250, 1, false);
		EntityRegistry.registerModEntity(DqmPetEntityTomosibikozou.class, "PetTomosibikozou", idxID + 127, DQR.instance, 250, 1, false);
		EntityRegistry.registerModEntity(DqmPetEntityTonburero.class, "PetTonburero", idxID + 128, DQR.instance, 250, 1, false);
		EntityRegistry.registerModEntity(DqmPetEntityTutiwarasi.class, "PetTutiwarasi", idxID + 129, DQR.instance, 250, 1, false);
		EntityRegistry.registerModEntity(DqmPetEntityUmiusi.class, "PetUmiusi", idxID + 130, DQR.instance, 250, 1, false);
		EntityRegistry.registerModEntity(DqmPetEntityYouganmajin.class, "PetYouganmajin", idxID + 131, DQR.instance, 250, 1, false);


		EntityRegistry.registerModEntity(DqmPetEntityAnkokumajin.class, "PetAnkokumajin", idxID + 152, DQR.instance, 250, 1, false);
		EntityRegistry.registerModEntity(DqmPetEntityAroinpu.class, "PetAroinpu", idxID + 153, DQR.instance, 250, 1, false);
		EntityRegistry.registerModEntity(DqmPetEntityBaburuking.class, "PetBaburuking", idxID + 154, DQR.instance, 250, 1, false);
		EntityRegistry.registerModEntity(DqmPetEntityBarakku.class, "PetBarakku", idxID + 155, DQR.instance, 250, 1, false);
		EntityRegistry.registerModEntity(DqmPetEntityBariidodog.class, "PetBariidodog", idxID + 156, DQR.instance, 250, 1, false);
		EntityRegistry.registerModEntity(DqmPetEntityBatorurex.class, "PetBatorurex", idxID + 157, DQR.instance, 250, 1, false);
		EntityRegistry.registerModEntity(DqmPetEntityBehomasuraimu.class, "PetBehomasuraimu", idxID + 158, DQR.instance, 250, 1, false);
		EntityRegistry.registerModEntity(DqmPetEntityBiggufeisu.class, "PetBiggufeisu", idxID + 159, DQR.instance, 250, 1, false);
		EntityRegistry.registerModEntity(DqmPetEntityBoureikensi.class, "PetBoureikensi", idxID + 160, DQR.instance, 250, 1, false);
		EntityRegistry.registerModEntity(DqmPetEntityBuraddosodo.class, "PetBuraddosodo", idxID + 161, DQR.instance, 250, 1, false);
		EntityRegistry.registerModEntity(DqmPetEntityBurakkubejita.class, "PetBurakkubejita", idxID + 162, DQR.instance, 250, 1, false);
		EntityRegistry.registerModEntity(DqmPetEntityDarkslime.class, "PetDarkslime", idxID + 163, DQR.instance, 250, 1, false);
		EntityRegistry.registerModEntity(DqmPetEntityDeddopekka.class, "PetDeddopekka", idxID + 164, DQR.instance, 250, 1, false);
		EntityRegistry.registerModEntity(DqmPetEntityDgizumo.class, "PetDgizumo", idxID + 165, DQR.instance, 250, 1, false);
		EntityRegistry.registerModEntity(DqmPetEntityDollmaster.class, "PetDollmaster", idxID + 166, DQR.instance, 250, 1, false);
		EntityRegistry.registerModEntity(DqmPetEntityDqmdragon.class, "PetDqmdragon", idxID + 167, DQR.instance, 250, 1, false);
		EntityRegistry.registerModEntity(DqmPetEntityDragonnaito.class, "PetDragonnaito", idxID + 168, DQR.instance, 250, 1, false);
		EntityRegistry.registerModEntity(DqmPetEntityDragonraida.class, "PetDragonraida", idxID + 169, DQR.instance, 250, 1, false);
		EntityRegistry.registerModEntity(DqmPetEntityGamegon.class, "PetGamegon", idxID + 170, DQR.instance, 250, 1, false);
		EntityRegistry.registerModEntity(DqmPetEntityGamegonload.class, "PetGamegonload", idxID + 171, DQR.instance, 250, 1, false);
		EntityRegistry.registerModEntity(DqmPetEntityGanirasu.class, "PetGanirasu", idxID + 172, DQR.instance, 250, 1, false);
		EntityRegistry.registerModEntity(DqmPetEntityGoldman.class, "PetGoldman", idxID + 173, DQR.instance, 250, 1, false);
		EntityRegistry.registerModEntity(DqmPetEntityGoremu.class, "PetGoremu", idxID + 174, DQR.instance, 250, 1, false);
		EntityRegistry.registerModEntity(DqmPetEntityGorudensuraimu.class, "PetGorudensuraimu", idxID + 175, DQR.instance, 250, 1, false);
		EntityRegistry.registerModEntity(DqmPetEntityHotatewarabi.class, "PetHotatewarabi", idxID + 176, DQR.instance, 250, 1, false);
		EntityRegistry.registerModEntity(DqmPetEntityJigokunohasami.class, "PetJigokunohasami", idxID + 177, DQR.instance, 250, 1, false);
		EntityRegistry.registerModEntity(DqmPetEntityKemunkurusu.class, "PetKemunkurusu", idxID + 178, DQR.instance, 250, 1, false);
		EntityRegistry.registerModEntity(DqmPetEntityKirakurabu.class, "PetKirakurabu", idxID + 179, DQR.instance, 250, 1, false);
		EntityRegistry.registerModEntity(DqmPetEntityKiramasin.class, "PetKiramasin", idxID + 180, DQR.instance, 250, 1, false);
		EntityRegistry.registerModEntity(DqmPetEntityKisudragon.class, "PetKisudragon", idxID + 181, DQR.instance, 250, 1, false);
		EntityRegistry.registerModEntity(DqmPetEntityKuinsuraimu.class, "PetKuinsuraimu", idxID + 182, DQR.instance, 250, 1, false);
		EntityRegistry.registerModEntity(DqmPetEntityMagematango.class, "PetMagematango", idxID + 183, DQR.instance, 250, 1, false);
		EntityRegistry.registerModEntity(DqmPetEntityMagemomonja.class, "PetMagemomonja", idxID + 184, DQR.instance, 250, 1, false);
		EntityRegistry.registerModEntity(DqmPetEntityMagumaron.class, "PetMagumaron", idxID + 185, DQR.instance, 250, 1, false);
		EntityRegistry.registerModEntity(DqmPetEntityMajikaruhatto.class, "PetMajikaruhatto", idxID + 186, DQR.instance, 250, 1, false);
		EntityRegistry.registerModEntity(DqmPetEntityMaounokage.class, "PetMaounokage", idxID + 187, DQR.instance, 250, 1, false);
		EntityRegistry.registerModEntity(DqmPetEntityMaporena.class, "PetMaporena", idxID + 188, DQR.instance, 250, 1, false);
		EntityRegistry.registerModEntity(DqmPetEntityMegazarurokku.class, "PetMegazarurokku", idxID + 189, DQR.instance, 250, 1, false);
		EntityRegistry.registerModEntity(DqmPetEntityMetaruhanta.class, "PetMetaruhanta", idxID + 190, DQR.instance, 250, 1, false);
		EntityRegistry.registerModEntity(DqmPetEntityMetaruhantaken.class, "PetMetaruhantaken", idxID + 191, DQR.instance, 250, 1, false);
		EntityRegistry.registerModEntity(DqmPetEntityPandorabox.class, "PetPandorabox", idxID + 192, DQR.instance, 250, 1, false);
		EntityRegistry.registerModEntity(DqmPetEntityPandorakibako.class, "PetPandorakibako", idxID + 193, DQR.instance, 250, 1, false);
		EntityRegistry.registerModEntity(DqmPetEntityPikusi.class, "PetPikusi", idxID + 194, DQR.instance, 250, 1, false);
		EntityRegistry.registerModEntity(DqmPetEntityPombom.class, "PetPombom", idxID + 195, DQR.instance, 250, 1, false);
		EntityRegistry.registerModEntity(DqmPetEntityPuyon.class, "PetPuyon", idxID + 196, DQR.instance, 250, 1, false);
		EntityRegistry.registerModEntity(DqmPetEntityRedsaikuron.class, "PetRedsaikuron", idxID + 197, DQR.instance, 250, 1, false);
		EntityRegistry.registerModEntity(DqmPetEntitySaikuropusu.class, "PetSaikuropusu", idxID + 198, DQR.instance, 250, 1, false);
		EntityRegistry.registerModEntity(DqmPetEntitySirubadebiru.class, "PetSirubadebiru", idxID + 199, DQR.instance, 250, 1, false);
		EntityRegistry.registerModEntity(DqmPetEntitySiryounokisi.class, "PetSiryounokisi", idxID + 200, DQR.instance, 250, 1, false);
		EntityRegistry.registerModEntity(DqmPetEntitySodofantomu.class, "PetSodofantomu", idxID + 201, DQR.instance, 250, 1, false);
		EntityRegistry.registerModEntity(DqmPetEntityStarkimera.class, "PetStarkimera", idxID + 202, DQR.instance, 250, 1, false);
		EntityRegistry.registerModEntity(DqmPetEntityStonman.class, "PetStonman", idxID + 203, DQR.instance, 250, 1, false);
		EntityRegistry.registerModEntity(DqmPetEntitySuraimubehomazun.class, "PetSuraimubehomazun", idxID + 204, DQR.instance, 250, 1, false);
		EntityRegistry.registerModEntity(DqmPetEntitySuraimuhaitawa.class, "PetSuraimuhaitawa", idxID + 205, DQR.instance, 250, 1, false);
		EntityRegistry.registerModEntity(DqmPetEntitySuraimumadyura.class, "PetSuraimumadyura", idxID + 206, DQR.instance, 250, 1, false);
		EntityRegistry.registerModEntity(DqmPetEntityTubokku.class, "PetTubokku", idxID + 207, DQR.instance, 250, 1, false);
		EntityRegistry.registerModEntity(DqmPetEntityUmibouzu.class, "PetUmibouzu", idxID + 208, DQR.instance, 250, 1, false);

		EntityRegistry.registerModEntity(DqmPetEntityAkairai.class, "PetAkairai", idxID + 250, DQR.instance, 250, 1, false);
		EntityRegistry.registerModEntity(DqmPetEntityBiggumoai.class, "PetBiggumoai", idxID + 253, DQR.instance, 250, 1, false);
		EntityRegistry.registerModEntity(DqmPetEntityDakuhobitto.class, "PetDakuhobitto", idxID + 254, DQR.instance, 250, 1, false);
		EntityRegistry.registerModEntity(DqmPetEntityDakunaito.class, "PetDakunaito", idxID + 255, DQR.instance, 250, 1, false);
		EntityRegistry.registerModEntity(DqmPetEntityDasudragon.class, "PetDasudragon", idxID + 256, DQR.instance, 250, 1, false);
		EntityRegistry.registerModEntity(DqmPetEntityDebirurodo.class, "PetDebirurodo", idxID + 257, DQR.instance, 250, 1, false);
		EntityRegistry.registerModEntity(DqmPetEntityDenga.class, "PetDenga", idxID + 258, DQR.instance, 250, 1, false);
		EntityRegistry.registerModEntity(DqmPetEntityDesujakkaru.class, "PetDesujakkaru", idxID + 259, DQR.instance, 250, 1, false);
		EntityRegistry.registerModEntity(DqmPetEntityDragondarknaito.class, "PetDragondarknaito", idxID + 260, DQR.instance, 250, 1, false);
		EntityRegistry.registerModEntity(DqmPetEntityGamegonrejendo.class, "PetGamegonrejendo", idxID + 261, DQR.instance, 250, 1, false);
		EntityRegistry.registerModEntity(DqmPetEntityGigantesu.class, "PetGigantesu", idxID + 262, DQR.instance, 250, 1, false);
		EntityRegistry.registerModEntity(DqmPetEntityGodraida.class, "PetGodraida", idxID + 263, DQR.instance, 250, 1, false);
		EntityRegistry.registerModEntity(DqmPetEntityKagenokisi.class, "PetKagenokisi", idxID + 264, DQR.instance, 250, 1, false);
		EntityRegistry.registerModEntity(DqmPetEntityRyuiso.class, "PetRyuiso", idxID + 265, DQR.instance, 250, 1, false);


		EntityRegistry.registerModEntity(DqmPetEntityArukemisuton.class, "PetArukemisuton", idxID + 271, DQR.instance, 250, 1, false);
		EntityRegistry.registerModEntity(DqmPetEntityAtorasu.class, "PetAtorasu", idxID + 273, DQR.instance, 250, 1, false);
		EntityRegistry.registerModEntity(DqmPetEntityGodonheddo.class, "PetGodonheddo", idxID + 276, DQR.instance, 250, 1, false);
		EntityRegistry.registerModEntity(DqmPetEntityGorudenkon.class, "PetGorudenkon", idxID + 277, DQR.instance, 250, 1, false);
		EntityRegistry.registerModEntity(DqmPetEntityKirapike.class, "PetKirapike", idxID + 279, DQR.instance, 250, 1, false);
		EntityRegistry.registerModEntity(DqmPetEntityKiratoti.class, "PetKiratoti", idxID + 280, DQR.instance, 250, 1, false);
		EntityRegistry.registerModEntity(DqmPetEntityKuinmomon.class, "PetKuinmomon", idxID + 281, DQR.instance, 250, 1, false);
		EntityRegistry.registerModEntity(DqmPetEntityMaaburun.class, "PetMaaburun", idxID + 283, DQR.instance, 250, 1, false);
		EntityRegistry.registerModEntity(DqmPetEntityMashougumo.class, "PetMashougumo", idxID + 284, DQR.instance, 250, 1, false);
		EntityRegistry.registerModEntity(DqmPetEntityMoonkimera.class, "PetMoonkimera", idxID + 286, DQR.instance, 250, 1, false);
		EntityRegistry.registerModEntity(DqmPetEntityReddoatya.class, "PetReddoatya", idxID + 289, DQR.instance, 250, 1, false);
		EntityRegistry.registerModEntity(DqmPetEntitySeigin.class, "PetSeigin", idxID + 291, DQR.instance, 250, 1, false);
		EntityRegistry.registerModEntity(DqmPetEntitySirubamanto.class, "PetSirubamanto", idxID + 292, DQR.instance, 250, 1, false);
		EntityRegistry.registerModEntity(DqmPetEntityTaipug.class, "PetTaipug", idxID + 294, DQR.instance, 250, 1, false);
		EntityRegistry.registerModEntity(DqmPetEntityTogekonbou.class, "PetTogekonbou", idxID + 295, DQR.instance, 250, 1, false);
		EntityRegistry.registerModEntity(DqmPetEntityTyokonuba.class, "PetTyokonuba", idxID + 296, DQR.instance, 250, 1, false);
		EntityRegistry.registerModEntity(DqmPetEntityWanpakusatan.class, "PetWanpakusatan", idxID + 297, DQR.instance, 250, 1, false);

		EntityRegistry.registerModEntity(DqmPetEntityDaiyamondosuraimu.class, "PetDaiyamondosuraimu", idxID + 304, DQR.instance, 250, 1, false);
		EntityRegistry.registerModEntity(DqmPetEntityDragometaru.class, "PetDragometaru", idxID + 305, DQR.instance, 250, 1, false);
		EntityRegistry.registerModEntity(DqmPetEntityHagumeta.class, "PetHagumeta", idxID + 306, DQR.instance, 250, 1, false);
		EntityRegistry.registerModEntity(DqmPetEntityHaguremetaruking.class, "PetHaguremetaruking", idxID + 307, DQR.instance, 250, 1, false);
		EntityRegistry.registerModEntity(DqmPetEntityMetaking.class, "PetMetaking", idxID + 308, DQR.instance, 250, 1, false);
		EntityRegistry.registerModEntity(DqmPetEntityMetaruburazazu.class, "PetMetaruburazazu", idxID + 309, DQR.instance, 250, 1, false);
		EntityRegistry.registerModEntity(DqmPetEntityMetasura.class, "PetMetasura", idxID + 310, DQR.instance, 250, 1, false);
		EntityRegistry.registerModEntity(DqmPetEntityPuratinaking.class, "PetPuratinaking", idxID + 311, DQR.instance, 250, 1, false);

		EntityRegistry.registerModEntity(DqmPetEntityBazuzu.class, "PetBazuzu", idxID + 321, DQR.instance, 250, 1, false);
		EntityRegistry.registerModEntity(DqmPetEntityDarkRamia.class, "PetDarkRamia", idxID + 322, DQR.instance, 250, 1, false);
		EntityRegistry.registerModEntity(DqmPetEntityDesupisaro1.class, "PetDesupisaro1", idxID + 323, DQR.instance, 250, 1, false);
		EntityRegistry.registerModEntity(DqmPetEntityDesupisaro2.class, "PetDesupisaro2", idxID + 324, DQR.instance, 250, 1, false);
		EntityRegistry.registerModEntity(DqmPetEntityDesupisaro3.class, "PetDesupisaro3", idxID + 325, DQR.instance, 250, 1, false);
		EntityRegistry.registerModEntity(DqmPetEntityEsterk.class, "PetEsterk", idxID + 326, DQR.instance, 250, 1, false);
		EntityRegistry.registerModEntity(DqmPetEntityGod.class, "PetGod", idxID + 327, DQR.instance, 250, 1, false);
		EntityRegistry.registerModEntity(DqmPetEntityKiramajinga.class, "PetKiramajinga", idxID + 328, DQR.instance, 250, 1, false);
		EntityRegistry.registerModEntity(DqmPetEntityMasterdoragon.class, "PetMasterdoragon", idxID + 329, DQR.instance, 250, 1, false);
		EntityRegistry.registerModEntity(DqmPetEntityNorowaretaturugi.class, "PetNorowaretaturugi", idxID + 330, DQR.instance, 250, 1, false);
		EntityRegistry.registerModEntity(DqmPetEntityRyuuou.class, "PetRyuuou", idxID + 331, DQR.instance, 250, 1, false);
		EntityRegistry.registerModEntity(DqmPetEntityRyuuou2.class, "PetRyuuou2", idxID + 332, DQR.instance, 250, 1, false);
		EntityRegistry.registerModEntity(DqmPetEntitySuraimujeneraru.class, "PetSuraimujeneraru", idxID + 333, DQR.instance, 250, 1, false);
		EntityRegistry.registerModEntity(DqmPetEntityYamatanooroti.class, "PetYamatanooroti", idxID + 334, DQR.instance, 250, 1, false);
		EntityRegistry.registerModEntity(DqmPetEntityZoma.class, "PetZoma", idxID + 335, DQR.instance, 250, 1, false);

		EntityRegistry.registerModEntity(DqmPetEntityAxedoragon.class, "PetAxedoragon", idxID + 500, DQR.instance, 250, 1, false);
		EntityRegistry.registerModEntity(DqmPetEntityBassaimasin.class, "PetBassaimasin", idxID + 501, DQR.instance, 250, 1, false);
		EntityRegistry.registerModEntity(DqmPetEntityBesuking.class, "PetBesuking", idxID + 502, DQR.instance, 250, 1, false);
		EntityRegistry.registerModEntity(DqmPetEntityBighanma.class, "PetBighanma", idxID + 503, DQR.instance, 250, 1, false);
		EntityRegistry.registerModEntity(DqmPetEntityBosutororu.class, "PetBosutororu", idxID + 504, DQR.instance, 250, 1, false);
		EntityRegistry.registerModEntity(DqmPetEntityBurizado.class, "PetBurizado", idxID + 505, DQR.instance, 250, 1, false);
		EntityRegistry.registerModEntity(DqmPetEntityDansunidoru.class, "PetDansunidoru", idxID + 506, DQR.instance, 250, 1, false);
		EntityRegistry.registerModEntity(DqmPetEntityDarktororu.class, "PetDarktororu", idxID + 507, DQR.instance, 250, 1, false);
		EntityRegistry.registerModEntity(DqmPetEntityDesunyago.class, "PetDesunyago", idxID + 508, DQR.instance, 250, 1, false);
		EntityRegistry.registerModEntity(DqmPetEntityDoragonsoruja.class, "PetDoragonsoruja", idxID + 509, DQR.instance, 250, 1, false);
		EntityRegistry.registerModEntity(DqmPetEntityDoroningyou.class, "PetDoroningyou", idxID + 510, DQR.instance, 250, 1, false);
		EntityRegistry.registerModEntity(DqmPetEntityDoruido.class, "PetDoruido", idxID + 511, DQR.instance, 250, 1, false);
		EntityRegistry.registerModEntity(DqmPetEntityEbiruapple.class, "PetEbiruapple", idxID + 512, DQR.instance, 250, 1, false);
		EntityRegistry.registerModEntity(DqmPetEntityFaratto.class, "PetFaratto", idxID + 513, DQR.instance, 250, 1, false);
		EntityRegistry.registerModEntity(DqmPetEntityFureimu.class, "PetFureimu", idxID + 514, DQR.instance, 250, 1, false);
		EntityRegistry.registerModEntity(DqmPetEntityGaikotu.class, "PetGaikotu", idxID + 515, DQR.instance, 250, 1, false);
		EntityRegistry.registerModEntity(DqmPetEntityGappurin.class, "PetGappurin", idxID + 516, DQR.instance, 250, 1, false);
		EntityRegistry.registerModEntity(DqmPetEntityGenjutusi.class, "PetGenjutusi", idxID + 517, DQR.instance, 250, 1, false);
		EntityRegistry.registerModEntity(DqmPetEntityGoldmanto.class, "PetGoldmanto", idxID + 518, DQR.instance, 250, 1, false);
		EntityRegistry.registerModEntity(DqmPetEntityHatonaito.class, "PetHatonaito", idxID + 519, DQR.instance, 250, 1, false);
		EntityRegistry.registerModEntity(DqmPetEntityJigokunoyoroi.class, "PetJigokunoyoroi", idxID + 520, DQR.instance, 250, 1, false);
		EntityRegistry.registerModEntity(DqmPetEntityKandatakobun.class, "PetKandatakobun", idxID + 521, DQR.instance, 250, 1, false);
		EntityRegistry.registerModEntity(DqmPetEntityKedamon.class, "PetKedamon", idxID + 522, DQR.instance, 250, 1, false);
		EntityRegistry.registerModEntity(DqmPetEntityKimendousi.class, "PetKimendousi", idxID + 523, DQR.instance, 250, 1, false);
		EntityRegistry.registerModEntity(DqmPetEntityKiraama.class, "PetKiraama", idxID + 524, DQR.instance, 250, 1, false);
		EntityRegistry.registerModEntity(DqmPetEntityKiramasin2.class, "PetKiramasin2", idxID + 525, DQR.instance, 250, 1, false);
		EntityRegistry.registerModEntity(DqmPetEntityManemane.class, "PetManemane", idxID + 526, DQR.instance, 250, 1, false);
		EntityRegistry.registerModEntity(DqmPetEntityMasso.class, "PetMasso", idxID + 527, DQR.instance, 250, 1, false);
		EntityRegistry.registerModEntity(DqmPetEntityMetaruhoimin.class, "PetMetaruhoimin", idxID + 528, DQR.instance, 250, 1, false);
		EntityRegistry.registerModEntity(DqmPetEntityMokomokojuu.class, "PetMokomokojuu", idxID + 529, DQR.instance, 250, 1, false);
		EntityRegistry.registerModEntity(DqmPetEntityMomoirosansimai.class, "PetMomoirosansimai", idxID + 530, DQR.instance, 250, 1, false);
		EntityRegistry.registerModEntity(DqmPetEntityNoroinoiwa.class, "PetNoroinoiwa", idxID + 531, DQR.instance, 250, 1, false);
		EntityRegistry.registerModEntity(DqmPetEntityPapettoman.class, "PetPapettoman", idxID + 532, DQR.instance, 250, 1, false);
		EntityRegistry.registerModEntity(DqmPetEntityPinkbonbon.class, "PetPinkbonbon", idxID + 533, DQR.instance, 250, 1, false);
		EntityRegistry.registerModEntity(DqmPetEntityPisaronaito.class, "PetPisaronaito", idxID + 534, DQR.instance, 250, 1, false);
		EntityRegistry.registerModEntity(DqmPetEntityPuremiasuraimu.class, "PetPuremiasuraimu", idxID + 535, DQR.instance, 250, 1, false);
		EntityRegistry.registerModEntity(DqmPetEntityRaimusuraimu.class, "PetRaimusuraimu", idxID + 536, DQR.instance, 250, 1, false);
		EntityRegistry.registerModEntity(DqmPetEntityRemonsuraimu.class, "PetRemonsuraimu", idxID + 537, DQR.instance, 250, 1, false);
		EntityRegistry.registerModEntity(DqmPetEntitySabotenboru.class, "PetSabotenboru", idxID + 538, DQR.instance, 250, 1, false);
		EntityRegistry.registerModEntity(DqmPetEntitySabotengold.class, "PetSabotengold", idxID + 539, DQR.instance, 250, 1, false);
		EntityRegistry.registerModEntity(DqmPetEntitySamayouyoroi.class, "PetSamayouyoroi", idxID + 540, DQR.instance, 250, 1, false);
		EntityRegistry.registerModEntity(DqmPetEntitySirudoaniki.class, "PetSirudoaniki", idxID + 541, DQR.instance, 250, 1, false);
		EntityRegistry.registerModEntity(DqmPetEntitySiryou.class, "PetSiryou", idxID + 542, DQR.instance, 250, 1, false);
		EntityRegistry.registerModEntity(DqmPetEntityTattyan.class, "PetTattyan", idxID + 543, DQR.instance, 250, 1, false);
		EntityRegistry.registerModEntity(DqmPetEntityTororu.class, "PetTororu", idxID + 544, DQR.instance, 250, 1, false);
		EntityRegistry.registerModEntity(DqmPetEntityTororubakkosu.class, "PetTororubakkosu", idxID + 545, DQR.instance, 250, 1, false);
		EntityRegistry.registerModEntity(DqmPetEntityTororubonba.class, "PetTororubonba", idxID + 546, DQR.instance, 250, 1, false);
		EntityRegistry.registerModEntity(DqmPetEntityTororuking.class, "PetTororuking", idxID + 547, DQR.instance, 250, 1, false);
		EntityRegistry.registerModEntity(DqmPetEntityTumurinmama.class, "PetTumurinmama", idxID + 548, DQR.instance, 250, 1, false);
		EntityRegistry.registerModEntity(DqmPetEntityUragirikozou.class, "PetUragirikozou", idxID + 549, DQR.instance, 250, 1, false);

		EntityRegistry.registerModEntity(DqmPetEntityMadrainbow.class, "PetMadrainbow", idxID + 550, DQR.instance, 250, 1, false);
		EntityRegistry.registerModEntity(DqmPetEntitySweetbag.class, "PetSweetbag", idxID + 551, DQR.instance, 250, 1, false);
		EntityRegistry.registerModEntity(DqmPetEntityShuvaluts.class, "PetShuvaluts", idxID + 552, DQR.instance, 250, 1, false);
		EntityRegistry.registerModEntity(DqmPetEntityBebingosatan.class, "PetBebingosatan", idxID + 553, DQR.instance, 250, 1, false);
		EntityRegistry.registerModEntity(DqmPetEntityKinghidora.class, "PetKinghidora", idxID + 554, DQR.instance, 250, 1, false);
		EntityRegistry.registerModEntity(DqmPetEntityKingbesu.class, "PetKingbesu", idxID + 555, DQR.instance, 250, 1, false);
		EntityRegistry.registerModEntity(DqmPetEntityBurasu.class, "PetBurasu", idxID + 556, DQR.instance, 250, 1, false);
		EntityRegistry.registerModEntity(DqmPetEntityGoldenmetalslime.class, "PetGoldenmetalslime", idxID + 557, DQR.instance, 250, 1, false);
		EntityRegistry.registerModEntity(DqmPetEntityFureizado.class, "PetFureizado", idxID + 558, DQR.instance, 250, 1, false);

		EntityRegistry.registerModEntity(DqmPetEntityGorotuki.class, "PetGorotuki", idxID + 559, DQR.instance, 250, 1, false);
		EntityRegistry.registerModEntity(DqmPetEntityEriminator.class, "PetEriminator", idxID + 560, DQR.instance, 250, 1, false);
		EntityRegistry.registerModEntity(DqmPetEntityDesusutoka.class, "PetDesusutoka", idxID + 561, DQR.instance, 250, 1, false);
		//EntityRegistry.registerModEntity(DqmPetEntityKandata.class, "PetGorotuki", idxID + 559, DQR.instance, 250, 1, false);

		EntityRegistry.registerModEntity(DqmPetEntityBlackchack.class, "PetBlackchack", idxID + 563, DQR.instance, 250, 1, false);
		EntityRegistry.registerModEntity(DqmPetEntitySuraimuemperor.class, "PetSuraimuemperor", idxID + 564, DQR.instance, 250, 1, false);
		EntityRegistry.registerModEntity(DqmPetEntityDarkdoriado.class, "PetDarkdoriado", idxID + 565, DQR.instance, 250, 1, false);

		EntityRegistry.registerModEntity(DqmPetEntityShadopan.class, "PetShadopan", idxID + 566, DQR.instance, 250, 1, false);
		EntityRegistry.registerModEntity(DqmPetEntityShadopan2.class, "PetShadopan2", idxID + 567, DQR.instance, 250, 1, false);

		EntityRegistry.registerModEntity(DqmPetEntityKandata.class, "PetKandata", idxID + 568, DQR.instance, 250, 1, false);
		EntityRegistry.registerModEntity(DqmPetEntityOrutega.class, "PetOrutega", idxID + 569, DQR.instance, 250, 1, false);
	}
}
