package dqr.entity.mobEntity;

import cpw.mods.fml.common.registry.EntityRegistry;
import dqr.DQR;
import dqr.entity.mobEntity.monsterBoss.DqmEntityDesupisaro1;
import dqr.entity.mobEntity.monsterBoss.DqmEntityDesupisaro2;
import dqr.entity.mobEntity.monsterBoss.DqmEntityDesupisaro3;
import dqr.entity.mobEntity.monsterBoss.DqmEntityEsterk;
import dqr.entity.mobEntity.monsterBoss.DqmEntityGod;
import dqr.entity.mobEntity.monsterBoss.DqmEntityMasterdoragon;
import dqr.entity.mobEntity.monsterBoss.DqmEntityRyuuou;
import dqr.entity.mobEntity.monsterBoss.DqmEntityRyuuou2;
import dqr.entity.mobEntity.monsterBoss.DqmEntityZoma;
import dqr.entity.mobEntity.monsterDay.DqmEntityAyasiikage;
import dqr.entity.mobEntity.monsterDay.DqmEntityBigCrow;
import dqr.entity.mobEntity.monsterDay.DqmEntityBigguhatto;
import dqr.entity.mobEntity.monsterDay.DqmEntityBubsura;
import dqr.entity.mobEntity.monsterDay.DqmEntityBurauni;
import dqr.entity.mobEntity.monsterDay.DqmEntityButisuraimu;
import dqr.entity.mobEntity.monsterDay.DqmEntityDokuroarai;
import dqr.entity.mobEntity.monsterDay.DqmEntityDoronuba;
import dqr.entity.mobEntity.monsterDay.DqmEntityDorozara;
import dqr.entity.mobEntity.monsterDay.DqmEntityDoruido;
import dqr.entity.mobEntity.monsterDay.DqmEntityDragosuraimu;
import dqr.entity.mobEntity.monsterDay.DqmEntityDucksbill;
import dqr.entity.mobEntity.monsterDay.DqmEntityEbiruapple;
import dqr.entity.mobEntity.monsterDay.DqmEntityFaratto;
import dqr.entity.mobEntity.monsterDay.DqmEntityGaikotu;
import dqr.entity.mobEntity.monsterDay.DqmEntityGizumoAZ;
import dqr.entity.mobEntity.monsterDay.DqmEntityGuntaigani;
import dqr.entity.mobEntity.monsterDay.DqmEntityHitokuikibako;
import dqr.entity.mobEntity.monsterDay.DqmEntityHitokuisaberu;
import dqr.entity.mobEntity.monsterDay.DqmEntityHoimisura;
import dqr.entity.mobEntity.monsterDay.DqmEntityIkkakuusagi;
import dqr.entity.mobEntity.monsterDay.DqmEntityItamogu;
import dqr.entity.mobEntity.monsterDay.DqmEntityKimera;
import dqr.entity.mobEntity.monsterDay.DqmEntityKirapan;
import dqr.entity.mobEntity.monsterDay.DqmEntityKirikabuobake;
import dqr.entity.mobEntity.monsterDay.DqmEntityMadohando;
import dqr.entity.mobEntity.monsterDay.DqmEntityMomon;
import dqr.entity.mobEntity.monsterDay.DqmEntityMomonja;
import dqr.entity.mobEntity.monsterDay.DqmEntityObakekinoko;
import dqr.entity.mobEntity.monsterDay.DqmEntityObakeumiusi;
import dqr.entity.mobEntity.monsterDay.DqmEntityOnikozou;
import dqr.entity.mobEntity.monsterDay.DqmEntityOokiduti;
import dqr.entity.mobEntity.monsterDay.DqmEntityOokutibasi;
import dqr.entity.mobEntity.monsterDay.DqmEntityOomedama;
import dqr.entity.mobEntity.monsterDay.DqmEntityOonamekuji;
import dqr.entity.mobEntity.monsterDay.DqmEntityPapetkozou;
import dqr.entity.mobEntity.monsterDay.DqmEntityPurizunyan;
import dqr.entity.mobEntity.monsterDay.DqmEntityRemonsuraimu;
import dqr.entity.mobEntity.monsterDay.DqmEntityRippusu;
import dqr.entity.mobEntity.monsterDay.DqmEntityRiripat;
import dqr.entity.mobEntity.monsterDay.DqmEntitySabotenboru;
import dqr.entity.mobEntity.monsterDay.DqmEntitySibirekurage;
import dqr.entity.mobEntity.monsterDay.DqmEntitySimasimacat;
import dqr.entity.mobEntity.monsterDay.DqmEntitySirudokozou;
import dqr.entity.mobEntity.monsterDay.DqmEntitySukippaa;
import dqr.entity.mobEntity.monsterDay.DqmEntitySunomon;
import dqr.entity.mobEntity.monsterDay.DqmEntitySupini;
import dqr.entity.mobEntity.monsterDay.DqmEntitySura;
import dqr.entity.mobEntity.monsterDay.DqmEntitySuraimubesu;
import dqr.entity.mobEntity.monsterDay.DqmEntitySuraimunaito;
import dqr.entity.mobEntity.monsterDay.DqmEntitySuraimutawa;
import dqr.entity.mobEntity.monsterDay.DqmEntitySuraimutumuri;
import dqr.entity.mobEntity.monsterDay.DqmEntityTogebouzu;
import dqr.entity.mobEntity.monsterDay.DqmEntityTukaima;
import dqr.entity.mobEntity.monsterDay.DqmEntityUzusioking;
import dqr.entity.mobEntity.monsterDay.DqmEntityWaraibukuro;
import dqr.entity.mobEntity.monsterDay.DqmEntityZinmentyou;
import dqr.entity.mobEntity.monsterDay.DqmEntityZukkinya;
import dqr.entity.mobEntity.monsterEnd.DqmEntityAkairai;
import dqr.entity.mobEntity.monsterEnd.DqmEntityBassaimasin;
import dqr.entity.mobEntity.monsterEnd.DqmEntityBatorurex;
import dqr.entity.mobEntity.monsterEnd.DqmEntityBiggumoai;
import dqr.entity.mobEntity.monsterEnd.DqmEntityBurizado;
import dqr.entity.mobEntity.monsterEnd.DqmEntityDakuhobitto;
import dqr.entity.mobEntity.monsterEnd.DqmEntityDakunaito;
import dqr.entity.mobEntity.monsterEnd.DqmEntityDarktororu;
import dqr.entity.mobEntity.monsterEnd.DqmEntityDasudragon;
import dqr.entity.mobEntity.monsterEnd.DqmEntityDenga;
import dqr.entity.mobEntity.monsterEnd.DqmEntityDesujakkaru;
import dqr.entity.mobEntity.monsterEnd.DqmEntityDesunyago;
import dqr.entity.mobEntity.monsterEnd.DqmEntityDesusutoka;
import dqr.entity.mobEntity.monsterEnd.DqmEntityDragondarknaito;
import dqr.entity.mobEntity.monsterEnd.DqmEntityGamegonrejendo;
import dqr.entity.mobEntity.monsterEnd.DqmEntityGigantesu;
import dqr.entity.mobEntity.monsterEnd.DqmEntityGodraida;
import dqr.entity.mobEntity.monsterEnd.DqmEntityGorudensuraimu;
import dqr.entity.mobEntity.monsterEnd.DqmEntityJigokunoyoroi;
import dqr.entity.mobEntity.monsterEnd.DqmEntityKagenokisi;
import dqr.entity.mobEntity.monsterEnd.DqmEntityManemane;
import dqr.entity.mobEntity.monsterEnd.DqmEntityPandorabox;
import dqr.entity.mobEntity.monsterEnd.DqmEntityRyuiso;
import dqr.entity.mobEntity.monsterEnd.DqmEntityShadopan2;
import dqr.entity.mobEntity.monsterEnd.DqmEntityTororubonba;
import dqr.entity.mobEntity.monsterEtc.DqmEntityFurosutogizumo;
import dqr.entity.mobEntity.monsterEtc.DqmEntityGanseki;
import dqr.entity.mobEntity.monsterEtc.DqmEntityGizumo;
import dqr.entity.mobEntity.monsterEtc.DqmEntityHiitogizumo;
import dqr.entity.mobEntity.monsterEtc.DqmEntityHitokuibako;
import dqr.entity.mobEntity.monsterEtc.DqmEntityKingbesu;
import dqr.entity.mobEntity.monsterEtc.DqmEntityMimikkukibako;
import dqr.entity.mobEntity.monsterEtc.DqmEntityNorowaretaturugi;
import dqr.entity.mobEntity.monsterEtc.DqmEntityPandorakibako;
import dqr.entity.mobEntity.monsterEtc.DqmEntitySuraimuking;
import dqr.entity.mobEntity.monsterEtc.DqmEntityTubo;
import dqr.entity.mobEntity.monsterHell.DqmEntityAnkokumajin;
import dqr.entity.mobEntity.monsterHell.DqmEntityAroinpu;
import dqr.entity.mobEntity.monsterHell.DqmEntityBaburuking;
import dqr.entity.mobEntity.monsterHell.DqmEntityBarakku;
import dqr.entity.mobEntity.monsterHell.DqmEntityBariidodog;
import dqr.entity.mobEntity.monsterHell.DqmEntityBehomasuraimu;
import dqr.entity.mobEntity.monsterHell.DqmEntityBiggufeisu;
import dqr.entity.mobEntity.monsterHell.DqmEntityBighanma;
import dqr.entity.mobEntity.monsterHell.DqmEntityBosutororu;
import dqr.entity.mobEntity.monsterHell.DqmEntityBoureikensi;
import dqr.entity.mobEntity.monsterHell.DqmEntityBuraddosodo;
import dqr.entity.mobEntity.monsterHell.DqmEntityBurakkubejita;
import dqr.entity.mobEntity.monsterHell.DqmEntityDarkdoriado;
import dqr.entity.mobEntity.monsterHell.DqmEntityDarkslime;
import dqr.entity.mobEntity.monsterHell.DqmEntityDeddopekka;
import dqr.entity.mobEntity.monsterHell.DqmEntityDgizumo;
import dqr.entity.mobEntity.monsterHell.DqmEntityDollmaster;
import dqr.entity.mobEntity.monsterHell.DqmEntityDoragonsoruja;
import dqr.entity.mobEntity.monsterHell.DqmEntityDqmdragon;
import dqr.entity.mobEntity.monsterHell.DqmEntityDragonnaito;
import dqr.entity.mobEntity.monsterHell.DqmEntityDragonraida;
import dqr.entity.mobEntity.monsterHell.DqmEntityEriminator;
import dqr.entity.mobEntity.monsterHell.DqmEntityFureimu;
import dqr.entity.mobEntity.monsterHell.DqmEntityGamegon;
import dqr.entity.mobEntity.monsterHell.DqmEntityGamegonload;
import dqr.entity.mobEntity.monsterHell.DqmEntityGanirasu;
import dqr.entity.mobEntity.monsterHell.DqmEntityGoldman;
import dqr.entity.mobEntity.monsterHell.DqmEntityGoremu;
import dqr.entity.mobEntity.monsterHell.DqmEntityGorudentotemu;
import dqr.entity.mobEntity.monsterHell.DqmEntityHotatewarabi;
import dqr.entity.mobEntity.monsterHell.DqmEntityJigokunohasami;
import dqr.entity.mobEntity.monsterHell.DqmEntityKedamon;
import dqr.entity.mobEntity.monsterHell.DqmEntityKemunkurusu;
import dqr.entity.mobEntity.monsterHell.DqmEntityKimendousi;
import dqr.entity.mobEntity.monsterHell.DqmEntityKiraama;
import dqr.entity.mobEntity.monsterHell.DqmEntityKirakurabu;
import dqr.entity.mobEntity.monsterHell.DqmEntityKiramasin;
import dqr.entity.mobEntity.monsterHell.DqmEntityKiramasin2;
import dqr.entity.mobEntity.monsterHell.DqmEntityKisudragon;
import dqr.entity.mobEntity.monsterHell.DqmEntityKuinsuraimu;
import dqr.entity.mobEntity.monsterHell.DqmEntityMagematango;
import dqr.entity.mobEntity.monsterHell.DqmEntityMagemomonja;
import dqr.entity.mobEntity.monsterHell.DqmEntityMagumaron;
import dqr.entity.mobEntity.monsterHell.DqmEntityMajikaruhatto;
import dqr.entity.mobEntity.monsterHell.DqmEntityMaounokage;
import dqr.entity.mobEntity.monsterHell.DqmEntityMaporena;
import dqr.entity.mobEntity.monsterHell.DqmEntityMegazarurokku;
import dqr.entity.mobEntity.monsterHell.DqmEntityMetaruhanta;
import dqr.entity.mobEntity.monsterHell.DqmEntityMimikku;
import dqr.entity.mobEntity.monsterHell.DqmEntityPapettoman;
import dqr.entity.mobEntity.monsterHell.DqmEntityPikusi;
import dqr.entity.mobEntity.monsterHell.DqmEntityPombom;
import dqr.entity.mobEntity.monsterHell.DqmEntityPuyon;
import dqr.entity.mobEntity.monsterHell.DqmEntityRedsaikuron;
import dqr.entity.mobEntity.monsterHell.DqmEntitySaikuropusu;
import dqr.entity.mobEntity.monsterHell.DqmEntityShadopan;
import dqr.entity.mobEntity.monsterHell.DqmEntitySirubadebiru;
import dqr.entity.mobEntity.monsterHell.DqmEntitySiryou;
import dqr.entity.mobEntity.monsterHell.DqmEntitySiryounokisi;
import dqr.entity.mobEntity.monsterHell.DqmEntitySodofantomu;
import dqr.entity.mobEntity.monsterHell.DqmEntityStarkimera;
import dqr.entity.mobEntity.monsterHell.DqmEntityStonman;
import dqr.entity.mobEntity.monsterHell.DqmEntitySuraimubehomazun;
import dqr.entity.mobEntity.monsterHell.DqmEntitySuraimuhaitawa;
import dqr.entity.mobEntity.monsterHell.DqmEntitySuraimumadyura;
import dqr.entity.mobEntity.monsterHell.DqmEntityTororuking;
import dqr.entity.mobEntity.monsterHell.DqmEntityTubokku;
import dqr.entity.mobEntity.monsterHell.DqmEntityUmibouzu;
import dqr.entity.mobEntity.monsterHell.DqmEntityWhitepan2;
import dqr.entity.mobEntity.monsterMetaru.DqmEntityDaiyamondosuraimu;
import dqr.entity.mobEntity.monsterMetaru.DqmEntityDragometaru;
import dqr.entity.mobEntity.monsterMetaru.DqmEntityGoldenmetalslime;
import dqr.entity.mobEntity.monsterMetaru.DqmEntityHagumeta;
import dqr.entity.mobEntity.monsterMetaru.DqmEntityHaguremetaruking;
import dqr.entity.mobEntity.monsterMetaru.DqmEntityMetaking;
import dqr.entity.mobEntity.monsterMetaru.DqmEntityMetaruburazazu;
import dqr.entity.mobEntity.monsterMetaru.DqmEntityMetasura;
import dqr.entity.mobEntity.monsterMetaru.DqmEntityPuratinaking;
import dqr.entity.mobEntity.monsterNight.DqmEntityAkumanosyo;
import dqr.entity.mobEntity.monsterNight.DqmEntityAkumanotubo;
import dqr.entity.mobEntity.monsterNight.DqmEntityAnimaruzonbi;
import dqr.entity.mobEntity.monsterNight.DqmEntityArumiraji;
import dqr.entity.mobEntity.monsterNight.DqmEntityAxedoragon;
import dqr.entity.mobEntity.monsterNight.DqmEntityBaburin;
import dqr.entity.mobEntity.monsterNight.DqmEntityBakudanbebi;
import dqr.entity.mobEntity.monsterNight.DqmEntityBakudaniwa;
import dqr.entity.mobEntity.monsterNight.DqmEntityBebisatan;
import dqr.entity.mobEntity.monsterNight.DqmEntityBehoimisuraimu;
import dqr.entity.mobEntity.monsterNight.DqmEntityBehoimusuraimu;
import dqr.entity.mobEntity.monsterNight.DqmEntityBerobero;
import dqr.entity.mobEntity.monsterNight.DqmEntityBeronyaago;
import dqr.entity.mobEntity.monsterNight.DqmEntityBesuking;
import dqr.entity.mobEntity.monsterNight.DqmEntityBuchunpa;
import dqr.entity.mobEntity.monsterNight.DqmEntityBuraddihando;
import dqr.entity.mobEntity.monsterNight.DqmEntityButtizukinya;
import dqr.entity.mobEntity.monsterNight.DqmEntityDansunidoru;
import dqr.entity.mobEntity.monsterNight.DqmEntityDesufuratta;
import dqr.entity.mobEntity.monsterNight.DqmEntityDokuyazukin;
import dqr.entity.mobEntity.monsterNight.DqmEntityDoraki;
import dqr.entity.mobEntity.monsterNight.DqmEntityDorakima;
import dqr.entity.mobEntity.monsterNight.DqmEntityDoroningyou;
import dqr.entity.mobEntity.monsterNight.DqmEntityEnzeruslime;
import dqr.entity.mobEntity.monsterNight.DqmEntityFgizumo;
import dqr.entity.mobEntity.monsterNight.DqmEntityGaikotukensi;
import dqr.entity.mobEntity.monsterNight.DqmEntityGappurin;
import dqr.entity.mobEntity.monsterNight.DqmEntityGenjutusi;
import dqr.entity.mobEntity.monsterNight.DqmEntityGhost;
import dqr.entity.mobEntity.monsterNight.DqmEntityGorotuki;
import dqr.entity.mobEntity.monsterNight.DqmEntityHerughost;
import dqr.entity.mobEntity.monsterNight.DqmEntityHgizumo;
import dqr.entity.mobEntity.monsterNight.DqmEntityHitokuiga;
import dqr.entity.mobEntity.monsterNight.DqmEntityHoroghost;
import dqr.entity.mobEntity.monsterNight.DqmEntityHyouganmajin;
import dqr.entity.mobEntity.monsterNight.DqmEntityJeriman;
import dqr.entity.mobEntity.monsterNight.DqmEntityKingsura;
import dqr.entity.mobEntity.monsterNight.DqmEntityKirapan2;
import dqr.entity.mobEntity.monsterNight.DqmEntityKirasuko;
import dqr.entity.mobEntity.monsterNight.DqmEntityMapetman;
import dqr.entity.mobEntity.monsterNight.DqmEntityMarinsuraimu;
import dqr.entity.mobEntity.monsterNight.DqmEntityMatango;
import dqr.entity.mobEntity.monsterNight.DqmEntityMeijidoraki;
import dqr.entity.mobEntity.monsterNight.DqmEntityMeijikimera;
import dqr.entity.mobEntity.monsterNight.DqmEntityMeragosuto;
import dqr.entity.mobEntity.monsterNight.DqmEntityMetaruhantaken;
import dqr.entity.mobEntity.monsterNight.DqmEntityMetaruraida;
import dqr.entity.mobEntity.monsterNight.DqmEntityMetoroghost;
import dqr.entity.mobEntity.monsterNight.DqmEntityMinidemon;
import dqr.entity.mobEntity.monsterNight.DqmEntityMokomokojuu;
import dqr.entity.mobEntity.monsterNight.DqmEntityMrippusu;
import dqr.entity.mobEntity.monsterNight.DqmEntityNightwalker;
import dqr.entity.mobEntity.monsterNight.DqmEntityObakekyandoru;
import dqr.entity.mobEntity.monsterNight.DqmEntityOdoruhouseki;
import dqr.entity.mobEntity.monsterNight.DqmEntityPinkmomon;
import dqr.entity.mobEntity.monsterNight.DqmEntityRaimusuraimu;
import dqr.entity.mobEntity.monsterNight.DqmEntitySamayoutamasii;
import dqr.entity.mobEntity.monsterNight.DqmEntitySamayouyoroi;
import dqr.entity.mobEntity.monsterNight.DqmEntitySibireageha;
import dqr.entity.mobEntity.monsterNight.DqmEntitySibiredanbira;
import dqr.entity.mobEntity.monsterNight.DqmEntitySkullgaroo;
import dqr.entity.mobEntity.monsterNight.DqmEntitySumairurokku;
import dqr.entity.mobEntity.monsterNight.DqmEntitySumoruguru;
import dqr.entity.mobEntity.monsterNight.DqmEntitySupekutetto;
import dqr.entity.mobEntity.monsterNight.DqmEntitySura2;
import dqr.entity.mobEntity.monsterNight.DqmEntitySuraimubogu;
import dqr.entity.mobEntity.monsterNight.DqmEntitySuraimuburesu;
import dqr.entity.mobEntity.monsterNight.DqmEntitySyado;
import dqr.entity.mobEntity.monsterNight.DqmEntityTahodoraki;
import dqr.entity.mobEntity.monsterNight.DqmEntityTomosibikozou;
import dqr.entity.mobEntity.monsterNight.DqmEntityTonburero;
import dqr.entity.mobEntity.monsterNight.DqmEntityTororu;
import dqr.entity.mobEntity.monsterNight.DqmEntityTutiwarasi;
import dqr.entity.mobEntity.monsterNight.DqmEntityUmiusi;
import dqr.entity.mobEntity.monsterNight.DqmEntityYouganmajin;
import dqr.entity.mobEntity.monsterSP.DqmEntityAtorasu;
import dqr.entity.mobEntity.monsterSP.DqmEntityBazuzu;
import dqr.entity.mobEntity.monsterSP.DqmEntityBlackchack;
import dqr.entity.mobEntity.monsterSP.DqmEntityBurasu;
import dqr.entity.mobEntity.monsterSP.DqmEntityDarkRamia;
import dqr.entity.mobEntity.monsterSP.DqmEntityFureizado;
import dqr.entity.mobEntity.monsterSP.DqmEntityGodonheddo;
import dqr.entity.mobEntity.monsterSP.DqmEntityKandata;
import dqr.entity.mobEntity.monsterSP.DqmEntityKandatakobun;
import dqr.entity.mobEntity.monsterSP.DqmEntityKinghidora;
import dqr.entity.mobEntity.monsterSP.DqmEntityKiramajinga;
import dqr.entity.mobEntity.monsterSP.DqmEntityKiratoti;
import dqr.entity.mobEntity.monsterSP.DqmEntityMashougumo;
import dqr.entity.mobEntity.monsterSP.DqmEntityMasso;
import dqr.entity.mobEntity.monsterSP.DqmEntityOrutega;
import dqr.entity.mobEntity.monsterSP.DqmEntityPisaronaito;
import dqr.entity.mobEntity.monsterSP.DqmEntityPuremiasuraimu;
import dqr.entity.mobEntity.monsterSP.DqmEntitySirubamanto;
import dqr.entity.mobEntity.monsterSP.DqmEntitySuraimuemperor;
import dqr.entity.mobEntity.monsterSP.DqmEntitySuraimujeneraru;
import dqr.entity.mobEntity.monsterSP.DqmEntityTattyan;
import dqr.entity.mobEntity.monsterSP.DqmEntityTororubakkosu;
import dqr.entity.mobEntity.monsterSP.DqmEntityUragirikozou;
import dqr.entity.mobEntity.monsterSP.DqmEntityWanpakusatan;
import dqr.entity.mobEntity.monsterSP.DqmEntityYamatanooroti;
import dqr.entity.mobEntity.monsterTensei.DqmEntityArukemisuton;
import dqr.entity.mobEntity.monsterTensei.DqmEntityBebingosatan;
import dqr.entity.mobEntity.monsterTensei.DqmEntityDebirurodo;
import dqr.entity.mobEntity.monsterTensei.DqmEntityGoldmanto;
import dqr.entity.mobEntity.monsterTensei.DqmEntityGorudenkon;
import dqr.entity.mobEntity.monsterTensei.DqmEntityHatonaito;
import dqr.entity.mobEntity.monsterTensei.DqmEntityKirapike;
import dqr.entity.mobEntity.monsterTensei.DqmEntityKuinmomon;
import dqr.entity.mobEntity.monsterTensei.DqmEntityMaaburun;
import dqr.entity.mobEntity.monsterTensei.DqmEntityMadrainbow;
import dqr.entity.mobEntity.monsterTensei.DqmEntityMetaruhoimin;
import dqr.entity.mobEntity.monsterTensei.DqmEntityMomoirosansimai;
import dqr.entity.mobEntity.monsterTensei.DqmEntityMoonkimera;
import dqr.entity.mobEntity.monsterTensei.DqmEntityNoroinoiwa;
import dqr.entity.mobEntity.monsterTensei.DqmEntityPinkbonbon;
import dqr.entity.mobEntity.monsterTensei.DqmEntityReddoatya;
import dqr.entity.mobEntity.monsterTensei.DqmEntitySabotengold;
import dqr.entity.mobEntity.monsterTensei.DqmEntitySeigin;
import dqr.entity.mobEntity.monsterTensei.DqmEntityShuvaluts;
import dqr.entity.mobEntity.monsterTensei.DqmEntitySirudoaniki;
import dqr.entity.mobEntity.monsterTensei.DqmEntitySweetbag;
import dqr.entity.mobEntity.monsterTensei.DqmEntityTaipug;
import dqr.entity.mobEntity.monsterTensei.DqmEntityTogekonbou;
import dqr.entity.mobEntity.monsterTensei.DqmEntityTumurinmama;
import dqr.entity.mobEntity.monsterTensei.DqmEntityTyokonuba;

public class MobRegister {

	private int idxID = DQR.conf.MonsterIDidx;

	public MobRegister()
	{
		//EntityRegistry.registerModEntity(EntityMeleeSkeleton.class, "MeleeSkeleton", 0, DQR.instance, 250, 1, false);
		//EntityRegistry.registerModEntity(DqmEntitySura.class, "Suraimu", idxID + 8000, DQR.instance, 250, 1, false);
		//EntityRegistry.registerModEntity(DqmEntityKingsura.class, "Kingsura", idxID + 8001, DQR.instance, 250, 1, false);
		//EntityRegistry.registerModEntity(EntitySample.class, "SampleEntity", 99, DQR.instance, 250, 1, false);

		EntityRegistry.registerModEntity(DqmEntityAyasiikage.class, "Ayasiikage", idxID + 4, DQR.instance, 250, 1, false);
		EntityRegistry.registerModEntity(DqmEntityBigCrow.class, "BigCrow", idxID + 5, DQR.instance, 250, 1, false);
		EntityRegistry.registerModEntity(DqmEntityBigguhatto.class, "Bigguhatto", idxID + 6, DQR.instance, 250, 1, false);
		EntityRegistry.registerModEntity(DqmEntityBubsura.class, "Bubsura", idxID + 7, DQR.instance, 250, 1, false);
		EntityRegistry.registerModEntity(DqmEntityBurauni.class, "Burauni", idxID + 8, DQR.instance, 250, 1, false);
		EntityRegistry.registerModEntity(DqmEntityButisuraimu.class, "Butisuraimu", idxID + 9, DQR.instance, 250, 1, false);
		EntityRegistry.registerModEntity(DqmEntityDokuroarai.class, "Dokuroarai", idxID + 10, DQR.instance, 250, 1, false);
		EntityRegistry.registerModEntity(DqmEntityDoronuba.class, "Doronuba", idxID + 11, DQR.instance, 250, 1, false);
		EntityRegistry.registerModEntity(DqmEntityDorozara.class, "Dorozara", idxID + 12, DQR.instance, 250, 1, false);
		EntityRegistry.registerModEntity(DqmEntityDragosuraimu.class, "Dragosuraimu", idxID + 13, DQR.instance, 250, 1, false);
		EntityRegistry.registerModEntity(DqmEntityDucksbill.class, "Ducksbill", idxID + 14, DQR.instance, 250, 1, false);
		EntityRegistry.registerModEntity(DqmEntityGizumo.class, "Gizumo", idxID + 15, DQR.instance, 250, 1, false);
		EntityRegistry.registerModEntity(DqmEntityGizumoAZ.class, "GizumoAZ", idxID + 16, DQR.instance, 250, 1, false);
		EntityRegistry.registerModEntity(DqmEntityGuntaigani.class, "Guntaigani", idxID + 17, DQR.instance, 250, 1, false);
		EntityRegistry.registerModEntity(DqmEntityHitokuikibako.class, "Hitokuikibako", idxID + 18, DQR.instance, 250, 1, false);
		EntityRegistry.registerModEntity(DqmEntityHitokuisaberu.class, "Hitokuisaberu", idxID + 19, DQR.instance, 250, 1, false);
		EntityRegistry.registerModEntity(DqmEntityHoimisura.class, "Hoimisura", idxID + 20, DQR.instance, 250, 1, false);
		EntityRegistry.registerModEntity(DqmEntityIkkakuusagi.class, "Ikkakuusagi", idxID + 21, DQR.instance, 250, 1, false);
		EntityRegistry.registerModEntity(DqmEntityItamogu.class, "Itamogu", idxID + 22, DQR.instance, 250, 1, false);
		EntityRegistry.registerModEntity(DqmEntityKimera.class, "Kimera", idxID + 23, DQR.instance, 250, 1, false);
		EntityRegistry.registerModEntity(DqmEntityKirapan.class, "Kirapan", idxID + 24, DQR.instance, 250, 1, false);
		EntityRegistry.registerModEntity(DqmEntityKirikabuobake.class, "Kirikabuobake", idxID + 25, DQR.instance, 250, 1, false);
		EntityRegistry.registerModEntity(DqmEntityMadohando.class, "Madohando", idxID + 26, DQR.instance, 250, 1, false);
		EntityRegistry.registerModEntity(DqmEntityMomon.class, "Momon", idxID + 27, DQR.instance, 250, 1, false);
		EntityRegistry.registerModEntity(DqmEntityMomonja.class, "Momonja", idxID + 28, DQR.instance, 250, 1, false);
		EntityRegistry.registerModEntity(DqmEntityObakekinoko.class, "Obakekinoko", idxID + 29, DQR.instance, 250, 1, false);
		EntityRegistry.registerModEntity(DqmEntityObakeumiusi.class, "Obakeumiusi", idxID + 30, DQR.instance, 250, 1, false);
		EntityRegistry.registerModEntity(DqmEntityOnikozou.class, "Onikozou", idxID + 31, DQR.instance, 250, 1, false);
		EntityRegistry.registerModEntity(DqmEntityOokiduti.class, "Ookiduti", idxID + 32, DQR.instance, 250, 1, false);
		EntityRegistry.registerModEntity(DqmEntityOokutibasi.class, "Ookutibasi", idxID + 33, DQR.instance, 250, 1, false);
		EntityRegistry.registerModEntity(DqmEntityOomedama.class, "Oomedama", idxID + 34, DQR.instance, 250, 1, false);
		EntityRegistry.registerModEntity(DqmEntityOonamekuji.class, "Oonamekuji", idxID + 35, DQR.instance, 250, 1, false);
		EntityRegistry.registerModEntity(DqmEntityPapetkozou.class, "Papetkozou", idxID + 36, DQR.instance, 250, 1, false);
		EntityRegistry.registerModEntity(DqmEntityPurizunyan.class, "Purizunyan", idxID + 37, DQR.instance, 250, 1, false);
		EntityRegistry.registerModEntity(DqmEntityRippusu.class, "Rippusu", idxID + 38, DQR.instance, 250, 1, false);
		EntityRegistry.registerModEntity(DqmEntityRiripat.class, "Riripat", idxID + 39, DQR.instance, 250, 1, false);
		EntityRegistry.registerModEntity(DqmEntitySibirekurage.class, "Sibirekurage", idxID + 40, DQR.instance, 250, 1, false);
		EntityRegistry.registerModEntity(DqmEntitySimasimacat.class, "Simasimacat", idxID + 41, DQR.instance, 250, 1, false);
		EntityRegistry.registerModEntity(DqmEntitySirudokozou.class, "Sirudokozou", idxID + 42, DQR.instance, 250, 1, false);
		EntityRegistry.registerModEntity(DqmEntitySukippaa.class, "Sukippaa", idxID + 43, DQR.instance, 250, 1, false);
		EntityRegistry.registerModEntity(DqmEntitySunomon.class, "Sunomon", idxID + 44, DQR.instance, 250, 1, false);
		EntityRegistry.registerModEntity(DqmEntitySupini.class, "Supini", idxID + 45, DQR.instance, 250, 1, false);
		EntityRegistry.registerModEntity(DqmEntitySura.class, "Sura", idxID + 46, DQR.instance, 250, 1, false);
		EntityRegistry.registerModEntity(DqmEntitySuraimubesu.class, "Suraimubesu", idxID + 47, DQR.instance, 250, 1, false);
		EntityRegistry.registerModEntity(DqmEntitySuraimunaito.class, "Suraimunaito", idxID + 48, DQR.instance, 250, 1, false);
		EntityRegistry.registerModEntity(DqmEntitySuraimutawa.class, "Suraimutawa", idxID + 49, DQR.instance, 250, 1, false);
		EntityRegistry.registerModEntity(DqmEntitySuraimutumuri.class, "Suraimutumuri", idxID + 50, DQR.instance, 250, 1, false);
		EntityRegistry.registerModEntity(DqmEntityTogebouzu.class, "Togebouzu", idxID + 51, DQR.instance, 250, 1, false);
		EntityRegistry.registerModEntity(DqmEntityTubo.class, "Tubo", idxID + 52, DQR.instance, 250, 1, false);
		EntityRegistry.registerModEntity(DqmEntityTukaima.class, "Tukaima", idxID + 53, DQR.instance, 250, 1, false);
		EntityRegistry.registerModEntity(DqmEntityUzusioking.class, "Uzusioking", idxID + 54, DQR.instance, 250, 1, false);
		EntityRegistry.registerModEntity(DqmEntityWaraibukuro.class, "Waraibukuro", idxID + 55, DQR.instance, 250, 1, false);
		EntityRegistry.registerModEntity(DqmEntityZinmentyou.class, "Zinmentyou", idxID + 56, DQR.instance, 250, 1, false);
		EntityRegistry.registerModEntity(DqmEntityZukkinya.class, "Zukkinya", idxID + 57, DQR.instance, 250, 1, false);


		EntityRegistry.registerModEntity(DqmEntityAkumanosyo.class, "Akumanosyo", idxID + 60, DQR.instance, 250, 1, false);
		EntityRegistry.registerModEntity(DqmEntityAkumanotubo.class, "Akumanotubo", idxID + 61, DQR.instance, 250, 1, false);
		EntityRegistry.registerModEntity(DqmEntityAnimaruzonbi.class, "Animaruzonbi", idxID + 64, DQR.instance, 250, 1, false);
		EntityRegistry.registerModEntity(DqmEntityArumiraji.class, "Arumiraji", idxID + 65, DQR.instance, 250, 1, false);
		EntityRegistry.registerModEntity(DqmEntityBaburin.class, "Baburin", idxID + 66, DQR.instance, 250, 1, false);
		EntityRegistry.registerModEntity(DqmEntityBakudanbebi.class, "Bakudanbebi", idxID + 67, DQR.instance, 250, 1, false);
		EntityRegistry.registerModEntity(DqmEntityBakudaniwa.class, "Bakudaniwa", idxID + 68, DQR.instance, 250, 1, false);
		EntityRegistry.registerModEntity(DqmEntityBebisatan.class, "Bebisatan", idxID + 69, DQR.instance, 250, 1, false);
		EntityRegistry.registerModEntity(DqmEntityBehoimisuraimu.class, "Behoimisuraimu", idxID + 70, DQR.instance, 250, 1, false);
		EntityRegistry.registerModEntity(DqmEntityBehoimusuraimu.class, "Behoimusuraimu", idxID + 71, DQR.instance, 250, 1, false);
		EntityRegistry.registerModEntity(DqmEntityBerobero.class, "Berobero", idxID + 72, DQR.instance, 250, 1, false);
		EntityRegistry.registerModEntity(DqmEntityBeronyaago.class, "Beronyaago", idxID + 73, DQR.instance, 250, 1, false);
		EntityRegistry.registerModEntity(DqmEntityBuchunpa.class, "Buchunpa", idxID + 74, DQR.instance, 250, 1, false);
		EntityRegistry.registerModEntity(DqmEntityBuraddihando.class, "Buraddihando", idxID + 75, DQR.instance, 250, 1, false);
		EntityRegistry.registerModEntity(DqmEntityButtizukinya.class, "Buttizukinya", idxID + 76, DQR.instance, 250, 1, false);
		EntityRegistry.registerModEntity(DqmEntityDesufuratta.class, "Desufuratta", idxID + 77, DQR.instance, 250, 1, false);
		EntityRegistry.registerModEntity(DqmEntityDokuyazukin.class, "Dokuyazukin", idxID + 78, DQR.instance, 250, 1, false);
		EntityRegistry.registerModEntity(DqmEntityDoraki.class, "Doraki", idxID + 79, DQR.instance, 250, 1, false);
		EntityRegistry.registerModEntity(DqmEntityDorakima.class, "Dorakima", idxID + 80, DQR.instance, 250, 1, false);
		EntityRegistry.registerModEntity(DqmEntityEnzeruslime.class, "Enzeruslime", idxID + 81, DQR.instance, 250, 1, false);
		EntityRegistry.registerModEntity(DqmEntityFgizumo.class, "Fgizumo", idxID + 82, DQR.instance, 250, 1, false);
		EntityRegistry.registerModEntity(DqmEntityFurosutogizumo.class, "Furosutogizumo", idxID + 83, DQR.instance, 250, 1, false);
		EntityRegistry.registerModEntity(DqmEntityGaikotukensi.class, "Gaikotukensi", idxID + 84, DQR.instance, 250, 1, false);
		EntityRegistry.registerModEntity(DqmEntityGhost.class, "Ghost", idxID + 85, DQR.instance, 250, 1, false);
		EntityRegistry.registerModEntity(DqmEntityGorudentotemu.class, "Gorudentotemu", idxID + 86, DQR.instance, 250, 1, false);
		EntityRegistry.registerModEntity(DqmEntityHerughost.class, "Herughost", idxID + 87, DQR.instance, 250, 1, false);
		EntityRegistry.registerModEntity(DqmEntityHgizumo.class, "Hgizumo", idxID + 88, DQR.instance, 250, 1, false);
		EntityRegistry.registerModEntity(DqmEntityHiitogizumo.class, "Hiitogizumo", idxID + 89, DQR.instance, 250, 1, false);
		EntityRegistry.registerModEntity(DqmEntityHitokuibako.class, "Hitokuibako", idxID + 90, DQR.instance, 250, 1, false);
		EntityRegistry.registerModEntity(DqmEntityHitokuiga.class, "Hitokuiga", idxID + 91, DQR.instance, 250, 1, false);
		EntityRegistry.registerModEntity(DqmEntityHoroghost.class, "Horoghost", idxID + 92, DQR.instance, 250, 1, false);
		EntityRegistry.registerModEntity(DqmEntityHyouganmajin.class, "Hyouganmajin", idxID + 93, DQR.instance, 250, 1, false);
		EntityRegistry.registerModEntity(DqmEntityJeriman.class, "Jeriman", idxID + 94, DQR.instance, 250, 1, false);
		EntityRegistry.registerModEntity(DqmEntityKingsura.class, "Kingsura", idxID + 95, DQR.instance, 250, 1, false);
		EntityRegistry.registerModEntity(DqmEntityKirapan2.class, "Kirapan2", idxID + 96, DQR.instance, 250, 1, false);
		EntityRegistry.registerModEntity(DqmEntityKirasuko.class, "Kirasuko", idxID + 97, DQR.instance, 250, 1, false);
		EntityRegistry.registerModEntity(DqmEntityMapetman.class, "Mapetman", idxID + 98, DQR.instance, 250, 1, false);
		EntityRegistry.registerModEntity(DqmEntityMarinsuraimu.class, "Marinsuraimu", idxID + 99, DQR.instance, 250, 1, false);
		EntityRegistry.registerModEntity(DqmEntityMatango.class, "Matango", idxID + 100, DQR.instance, 250, 1, false);
		EntityRegistry.registerModEntity(DqmEntityMeijidoraki.class, "Meijidoraki", idxID + 101, DQR.instance, 250, 1, false);
		EntityRegistry.registerModEntity(DqmEntityMeijikimera.class, "Meijikimera", idxID + 102, DQR.instance, 250, 1, false);
		EntityRegistry.registerModEntity(DqmEntityMeragosuto.class, "Meragosuto", idxID + 103, DQR.instance, 250, 1, false);
		EntityRegistry.registerModEntity(DqmEntityMetaruraida.class, "Metaruraida", idxID + 104, DQR.instance, 250, 1, false);
		EntityRegistry.registerModEntity(DqmEntityMetoroghost.class, "Metoroghost", idxID + 105, DQR.instance, 250, 1, false);
		EntityRegistry.registerModEntity(DqmEntityMimikku.class, "Mimikku", idxID + 106, DQR.instance, 250, 1, false);
		EntityRegistry.registerModEntity(DqmEntityMimikkukibako.class, "Mimikkukibako", idxID + 107, DQR.instance, 250, 1, false);
		EntityRegistry.registerModEntity(DqmEntityMinidemon.class, "Minidemon", idxID + 108, DQR.instance, 250, 1, false);
		EntityRegistry.registerModEntity(DqmEntityMrippusu.class, "Mrippusu", idxID + 109, DQR.instance, 250, 1, false);
		EntityRegistry.registerModEntity(DqmEntityNightwalker.class, "Nightwalker", idxID + 110, DQR.instance, 250, 1, false);
		EntityRegistry.registerModEntity(DqmEntityObakekyandoru.class, "Obakekyandoru", idxID + 111, DQR.instance, 250, 1, false);
		EntityRegistry.registerModEntity(DqmEntityOdoruhouseki.class, "Odoruhouseki", idxID + 112, DQR.instance, 250, 1, false);
		EntityRegistry.registerModEntity(DqmEntityPinkmomon.class, "Pinkmomon", idxID + 113, DQR.instance, 250, 1, false);
		EntityRegistry.registerModEntity(DqmEntitySamayoutamasii.class, "Samayoutamasii", idxID + 114, DQR.instance, 250, 1, false);
		EntityRegistry.registerModEntity(DqmEntitySibireageha.class, "Sibireageha", idxID + 115, DQR.instance, 250, 1, false);
		EntityRegistry.registerModEntity(DqmEntitySibiredanbira.class, "Sibiredanbira", idxID + 116, DQR.instance, 250, 1, false);
		EntityRegistry.registerModEntity(DqmEntitySkullgaroo.class, "Skullgaroo", idxID + 117, DQR.instance, 250, 1, false);
		EntityRegistry.registerModEntity(DqmEntitySumairurokku.class, "Sumairurokku", idxID + 118, DQR.instance, 250, 1, false);
		EntityRegistry.registerModEntity(DqmEntitySumoruguru.class, "Sumoruguru", idxID + 119, DQR.instance, 250, 1, false);
		EntityRegistry.registerModEntity(DqmEntitySupekutetto.class, "Supekutetto", idxID + 120, DQR.instance, 250, 1, false);
		EntityRegistry.registerModEntity(DqmEntitySura2.class, "Sura2", idxID + 121, DQR.instance, 250, 1, false);
		EntityRegistry.registerModEntity(DqmEntitySuraimubogu.class, "Suraimubogu", idxID + 122, DQR.instance, 250, 1, false);
		EntityRegistry.registerModEntity(DqmEntitySuraimuburesu.class, "Suraimuburesu", idxID + 123, DQR.instance, 250, 1, false);
		EntityRegistry.registerModEntity(DqmEntitySuraimuking.class, "Suraimuking", idxID + 124, DQR.instance, 250, 1, false);
		EntityRegistry.registerModEntity(DqmEntitySyado.class, "Syado", idxID + 125, DQR.instance, 250, 1, false);
		EntityRegistry.registerModEntity(DqmEntityTahodoraki.class, "Tahodoraki", idxID + 126, DQR.instance, 250, 1, false);
		EntityRegistry.registerModEntity(DqmEntityTomosibikozou.class, "Tomosibikozou", idxID + 127, DQR.instance, 250, 1, false);
		EntityRegistry.registerModEntity(DqmEntityTonburero.class, "Tonburero", idxID + 128, DQR.instance, 250, 1, false);
		EntityRegistry.registerModEntity(DqmEntityTutiwarasi.class, "Tutiwarasi", idxID + 129, DQR.instance, 250, 1, false);
		EntityRegistry.registerModEntity(DqmEntityUmiusi.class, "Umiusi", idxID + 130, DQR.instance, 250, 1, false);
		EntityRegistry.registerModEntity(DqmEntityYouganmajin.class, "Youganmajin", idxID + 131, DQR.instance, 250, 1, false);


		EntityRegistry.registerModEntity(DqmEntityAnkokumajin.class, "Ankokumajin", idxID + 152, DQR.instance, 250, 1, false);
		EntityRegistry.registerModEntity(DqmEntityAroinpu.class, "Aroinpu", idxID + 153, DQR.instance, 250, 1, false);
		EntityRegistry.registerModEntity(DqmEntityBaburuking.class, "Baburuking", idxID + 154, DQR.instance, 250, 1, false);
		EntityRegistry.registerModEntity(DqmEntityBarakku.class, "Barakku", idxID + 155, DQR.instance, 250, 1, false);
		EntityRegistry.registerModEntity(DqmEntityBariidodog.class, "Bariidodog", idxID + 156, DQR.instance, 250, 1, false);
		EntityRegistry.registerModEntity(DqmEntityBatorurex.class, "Batorurex", idxID + 157, DQR.instance, 250, 1, false);
		EntityRegistry.registerModEntity(DqmEntityBehomasuraimu.class, "Behomasuraimu", idxID + 158, DQR.instance, 250, 1, false);
		EntityRegistry.registerModEntity(DqmEntityBiggufeisu.class, "Biggufeisu", idxID + 159, DQR.instance, 250, 1, false);
		EntityRegistry.registerModEntity(DqmEntityBoureikensi.class, "Boureikensi", idxID + 160, DQR.instance, 250, 1, false);
		EntityRegistry.registerModEntity(DqmEntityBuraddosodo.class, "Buraddosodo", idxID + 161, DQR.instance, 250, 1, false);
		EntityRegistry.registerModEntity(DqmEntityBurakkubejita.class, "Burakkubejita", idxID + 162, DQR.instance, 250, 1, false);
		EntityRegistry.registerModEntity(DqmEntityDarkslime.class, "Darkslime", idxID + 163, DQR.instance, 250, 1, false);
		EntityRegistry.registerModEntity(DqmEntityDeddopekka.class, "Deddopekka", idxID + 164, DQR.instance, 250, 1, false);
		EntityRegistry.registerModEntity(DqmEntityDgizumo.class, "Dgizumo", idxID + 165, DQR.instance, 250, 1, false);
		EntityRegistry.registerModEntity(DqmEntityDollmaster.class, "Dollmaster", idxID + 166, DQR.instance, 250, 1, false);
		EntityRegistry.registerModEntity(DqmEntityDqmdragon.class, "Dqmdragon", idxID + 167, DQR.instance, 250, 1, false);
		EntityRegistry.registerModEntity(DqmEntityDragonnaito.class, "Dragonnaito", idxID + 168, DQR.instance, 250, 1, false);
		EntityRegistry.registerModEntity(DqmEntityDragonraida.class, "Dragonraida", idxID + 169, DQR.instance, 250, 1, false);
		EntityRegistry.registerModEntity(DqmEntityGamegon.class, "Gamegon", idxID + 170, DQR.instance, 250, 1, false);
		EntityRegistry.registerModEntity(DqmEntityGamegonload.class, "Gamegonload", idxID + 171, DQR.instance, 250, 1, false);
		EntityRegistry.registerModEntity(DqmEntityGanirasu.class, "Ganirasu", idxID + 172, DQR.instance, 250, 1, false);
		EntityRegistry.registerModEntity(DqmEntityGoldman.class, "Goldman", idxID + 173, DQR.instance, 250, 1, false);
		EntityRegistry.registerModEntity(DqmEntityGoremu.class, "Goremu", idxID + 174, DQR.instance, 250, 1, false);
		EntityRegistry.registerModEntity(DqmEntityGorudensuraimu.class, "Gorudensuraimu", idxID + 175, DQR.instance, 250, 1, false);
		EntityRegistry.registerModEntity(DqmEntityHotatewarabi.class, "Hotatewarabi", idxID + 176, DQR.instance, 250, 1, false);
		EntityRegistry.registerModEntity(DqmEntityJigokunohasami.class, "Jigokunohasami", idxID + 177, DQR.instance, 250, 1, false);
		EntityRegistry.registerModEntity(DqmEntityKemunkurusu.class, "Kemunkurusu", idxID + 178, DQR.instance, 250, 1, false);
		EntityRegistry.registerModEntity(DqmEntityKirakurabu.class, "Kirakurabu", idxID + 179, DQR.instance, 250, 1, false);
		EntityRegistry.registerModEntity(DqmEntityKiramasin.class, "Kiramasin", idxID + 180, DQR.instance, 250, 1, false);
		EntityRegistry.registerModEntity(DqmEntityKisudragon.class, "Kisudragon", idxID + 181, DQR.instance, 250, 1, false);
		EntityRegistry.registerModEntity(DqmEntityKuinsuraimu.class, "Kuinsuraimu", idxID + 182, DQR.instance, 250, 1, false);
		EntityRegistry.registerModEntity(DqmEntityMagematango.class, "Magematango", idxID + 183, DQR.instance, 250, 1, false);
		EntityRegistry.registerModEntity(DqmEntityMagemomonja.class, "Magemomonja", idxID + 184, DQR.instance, 250, 1, false);
		EntityRegistry.registerModEntity(DqmEntityMagumaron.class, "Magumaron", idxID + 185, DQR.instance, 250, 1, false);
		EntityRegistry.registerModEntity(DqmEntityMajikaruhatto.class, "Majikaruhatto", idxID + 186, DQR.instance, 250, 1, false);
		EntityRegistry.registerModEntity(DqmEntityMaounokage.class, "Maounokage", idxID + 187, DQR.instance, 250, 1, false);
		EntityRegistry.registerModEntity(DqmEntityMaporena.class, "Maporena", idxID + 188, DQR.instance, 250, 1, false);
		EntityRegistry.registerModEntity(DqmEntityMegazarurokku.class, "Megazarurokku", idxID + 189, DQR.instance, 250, 1, false);
		EntityRegistry.registerModEntity(DqmEntityMetaruhanta.class, "Metaruhanta", idxID + 190, DQR.instance, 250, 1, false);
		EntityRegistry.registerModEntity(DqmEntityMetaruhantaken.class, "Metaruhantaken", idxID + 191, DQR.instance, 250, 1, false);
		EntityRegistry.registerModEntity(DqmEntityPandorabox.class, "Pandorabox", idxID + 192, DQR.instance, 250, 1, false);
		EntityRegistry.registerModEntity(DqmEntityPandorakibako.class, "Pandorakibako", idxID + 193, DQR.instance, 250, 1, false);
		EntityRegistry.registerModEntity(DqmEntityPikusi.class, "Pikusi", idxID + 194, DQR.instance, 250, 1, false);
		EntityRegistry.registerModEntity(DqmEntityPombom.class, "Pombom", idxID + 195, DQR.instance, 250, 1, false);
		EntityRegistry.registerModEntity(DqmEntityPuyon.class, "Puyon", idxID + 196, DQR.instance, 250, 1, false);
		EntityRegistry.registerModEntity(DqmEntityRedsaikuron.class, "Redsaikuron", idxID + 197, DQR.instance, 250, 1, false);
		EntityRegistry.registerModEntity(DqmEntitySaikuropusu.class, "Saikuropusu", idxID + 198, DQR.instance, 250, 1, false);
		EntityRegistry.registerModEntity(DqmEntitySirubadebiru.class, "Sirubadebiru", idxID + 199, DQR.instance, 250, 1, false);
		EntityRegistry.registerModEntity(DqmEntitySiryounokisi.class, "Siryounokisi", idxID + 200, DQR.instance, 250, 1, false);
		EntityRegistry.registerModEntity(DqmEntitySodofantomu.class, "Sodofantomu", idxID + 201, DQR.instance, 250, 1, false);
		EntityRegistry.registerModEntity(DqmEntityStarkimera.class, "Starkimera", idxID + 202, DQR.instance, 250, 1, false);
		EntityRegistry.registerModEntity(DqmEntityStonman.class, "Stonman", idxID + 203, DQR.instance, 250, 1, false);
		EntityRegistry.registerModEntity(DqmEntitySuraimubehomazun.class, "Suraimubehomazun", idxID + 204, DQR.instance, 250, 1, false);
		EntityRegistry.registerModEntity(DqmEntitySuraimuhaitawa.class, "Suraimuhaitawa", idxID + 205, DQR.instance, 250, 1, false);
		EntityRegistry.registerModEntity(DqmEntitySuraimumadyura.class, "Suraimumadyura", idxID + 206, DQR.instance, 250, 1, false);
		EntityRegistry.registerModEntity(DqmEntityTubokku.class, "Tubokku", idxID + 207, DQR.instance, 250, 1, false);
		EntityRegistry.registerModEntity(DqmEntityUmibouzu.class, "Umibouzu", idxID + 208, DQR.instance, 250, 1, false);

		EntityRegistry.registerModEntity(DqmEntityAkairai.class, "Akairai", idxID + 250, DQR.instance, 250, 1, false);
		EntityRegistry.registerModEntity(DqmEntityBiggumoai.class, "Biggumoai", idxID + 253, DQR.instance, 250, 1, false);
		EntityRegistry.registerModEntity(DqmEntityDakuhobitto.class, "Dakuhobitto", idxID + 254, DQR.instance, 250, 1, false);
		EntityRegistry.registerModEntity(DqmEntityDakunaito.class, "Dakunaito", idxID + 255, DQR.instance, 250, 1, false);
		EntityRegistry.registerModEntity(DqmEntityDasudragon.class, "Dasudragon", idxID + 256, DQR.instance, 250, 1, false);
		EntityRegistry.registerModEntity(DqmEntityDebirurodo.class, "Debirurodo", idxID + 257, DQR.instance, 250, 1, false);
		EntityRegistry.registerModEntity(DqmEntityDenga.class, "Denga", idxID + 258, DQR.instance, 250, 1, false);
		EntityRegistry.registerModEntity(DqmEntityDesujakkaru.class, "Desujakkaru", idxID + 259, DQR.instance, 250, 1, false);
		EntityRegistry.registerModEntity(DqmEntityDragondarknaito.class, "Dragondarknaito", idxID + 260, DQR.instance, 250, 1, false);
		EntityRegistry.registerModEntity(DqmEntityGamegonrejendo.class, "Gamegonrejendo", idxID + 261, DQR.instance, 250, 1, false);
		EntityRegistry.registerModEntity(DqmEntityGigantesu.class, "Gigantesu", idxID + 262, DQR.instance, 250, 1, false);
		EntityRegistry.registerModEntity(DqmEntityGodraida.class, "Godraida", idxID + 263, DQR.instance, 250, 1, false);
		EntityRegistry.registerModEntity(DqmEntityKagenokisi.class, "Kagenokisi", idxID + 264, DQR.instance, 250, 1, false);
		EntityRegistry.registerModEntity(DqmEntityRyuiso.class, "Ryuiso", idxID + 265, DQR.instance, 250, 1, false);


		EntityRegistry.registerModEntity(DqmEntityArukemisuton.class, "Arukemisuton", idxID + 271, DQR.instance, 250, 1, false);
		EntityRegistry.registerModEntity(DqmEntityAtorasu.class, "Atorasu", idxID + 273, DQR.instance, 250, 1, false);
		EntityRegistry.registerModEntity(DqmEntityGodonheddo.class, "Godonheddo", idxID + 276, DQR.instance, 250, 1, false);
		EntityRegistry.registerModEntity(DqmEntityGorudenkon.class, "Gorudenkon", idxID + 277, DQR.instance, 250, 1, false);
		EntityRegistry.registerModEntity(DqmEntityKirapike.class, "Kirapike", idxID + 279, DQR.instance, 250, 1, false);
		EntityRegistry.registerModEntity(DqmEntityKiratoti.class, "Kiratoti", idxID + 280, DQR.instance, 250, 1, false);
		EntityRegistry.registerModEntity(DqmEntityKuinmomon.class, "Kuinmomon", idxID + 281, DQR.instance, 250, 1, false);
		EntityRegistry.registerModEntity(DqmEntityMaaburun.class, "Maaburun", idxID + 283, DQR.instance, 250, 1, false);
		EntityRegistry.registerModEntity(DqmEntityMashougumo.class, "Mashougumo", idxID + 284, DQR.instance, 250, 1, false);
		EntityRegistry.registerModEntity(DqmEntityMoonkimera.class, "Moonkimera", idxID + 286, DQR.instance, 250, 1, false);
		EntityRegistry.registerModEntity(DqmEntityReddoatya.class, "Reddoatya", idxID + 289, DQR.instance, 250, 1, false);
		EntityRegistry.registerModEntity(DqmEntitySeigin.class, "Seigin", idxID + 291, DQR.instance, 250, 1, false);
		EntityRegistry.registerModEntity(DqmEntitySirubamanto.class, "Sirubamanto", idxID + 292, DQR.instance, 250, 1, false);
		EntityRegistry.registerModEntity(DqmEntityTaipug.class, "Taipug", idxID + 294, DQR.instance, 250, 1, false);
		EntityRegistry.registerModEntity(DqmEntityTogekonbou.class, "Togekonbou", idxID + 295, DQR.instance, 250, 1, false);
		EntityRegistry.registerModEntity(DqmEntityTyokonuba.class, "Tyokonuba", idxID + 296, DQR.instance, 250, 1, false);
		EntityRegistry.registerModEntity(DqmEntityWanpakusatan.class, "Wanpakusatan", idxID + 297, DQR.instance, 250, 1, false);

		EntityRegistry.registerModEntity(DqmEntityDaiyamondosuraimu.class, "Daiyamondosuraimu", idxID + 304, DQR.instance, 250, 1, false);
		EntityRegistry.registerModEntity(DqmEntityDragometaru.class, "Dragometaru", idxID + 305, DQR.instance, 250, 1, false);
		EntityRegistry.registerModEntity(DqmEntityHagumeta.class, "Hagumeta", idxID + 306, DQR.instance, 250, 1, false);
		EntityRegistry.registerModEntity(DqmEntityHaguremetaruking.class, "Haguremetaruking", idxID + 307, DQR.instance, 250, 1, false);
		EntityRegistry.registerModEntity(DqmEntityMetaking.class, "Metaking", idxID + 308, DQR.instance, 250, 1, false);
		EntityRegistry.registerModEntity(DqmEntityMetaruburazazu.class, "Metaruburazazu", idxID + 309, DQR.instance, 250, 1, false);
		EntityRegistry.registerModEntity(DqmEntityMetasura.class, "Metasura", idxID + 310, DQR.instance, 250, 1, false);
		EntityRegistry.registerModEntity(DqmEntityPuratinaking.class, "Puratinaking", idxID + 311, DQR.instance, 250, 1, false);

		EntityRegistry.registerModEntity(DqmEntityBazuzu.class, "Bazuzu", idxID + 321, DQR.instance, 250, 1, false);
		EntityRegistry.registerModEntity(DqmEntityDarkRamia.class, "DarkRamia", idxID + 322, DQR.instance, 250, 1, false);
		EntityRegistry.registerModEntity(DqmEntityDesupisaro1.class, "Desupisaro1", idxID + 323, DQR.instance, 250, 1, false);
		EntityRegistry.registerModEntity(DqmEntityDesupisaro2.class, "Desupisaro2", idxID + 324, DQR.instance, 250, 1, false);
		EntityRegistry.registerModEntity(DqmEntityDesupisaro3.class, "Desupisaro3", idxID + 325, DQR.instance, 250, 1, false);
		EntityRegistry.registerModEntity(DqmEntityEsterk.class, "Esterk", idxID + 326, DQR.instance, 250, 1, false);
		EntityRegistry.registerModEntity(DqmEntityGod.class, "God", idxID + 327, DQR.instance, 250, 1, false);
		EntityRegistry.registerModEntity(DqmEntityKiramajinga.class, "Kiramajinga", idxID + 328, DQR.instance, 250, 1, false);
		EntityRegistry.registerModEntity(DqmEntityMasterdoragon.class, "Masterdoragon", idxID + 329, DQR.instance, 250, 1, false);
		EntityRegistry.registerModEntity(DqmEntityNorowaretaturugi.class, "Norowaretaturugi", idxID + 330, DQR.instance, 250, 1, false);
		EntityRegistry.registerModEntity(DqmEntityRyuuou.class, "Ryuuou", idxID + 331, DQR.instance, 250, 1, false);
		EntityRegistry.registerModEntity(DqmEntityRyuuou2.class, "Ryuuou2", idxID + 332, DQR.instance, 250, 1, false);
		EntityRegistry.registerModEntity(DqmEntitySuraimujeneraru.class, "Suraimujeneraru", idxID + 333, DQR.instance, 250, 1, false);
		EntityRegistry.registerModEntity(DqmEntityYamatanooroti.class, "Yamatanooroti", idxID + 334, DQR.instance, 250, 1, false);
		EntityRegistry.registerModEntity(DqmEntityZoma.class, "Zoma", idxID + 335, DQR.instance, 250, 1, false);

		EntityRegistry.registerModEntity(DqmEntityAxedoragon.class, "Axedoragon", idxID + 500, DQR.instance, 250, 1, false);
		EntityRegistry.registerModEntity(DqmEntityBassaimasin.class, "Bassaimasin", idxID + 501, DQR.instance, 250, 1, false);
		EntityRegistry.registerModEntity(DqmEntityBesuking.class, "Besuking", idxID + 502, DQR.instance, 250, 1, false);
		EntityRegistry.registerModEntity(DqmEntityBighanma.class, "Bighanma", idxID + 503, DQR.instance, 250, 1, false);
		EntityRegistry.registerModEntity(DqmEntityBosutororu.class, "Bosutororu", idxID + 504, DQR.instance, 250, 1, false);
		EntityRegistry.registerModEntity(DqmEntityBurizado.class, "Burizado", idxID + 505, DQR.instance, 250, 1, false);
		EntityRegistry.registerModEntity(DqmEntityDansunidoru.class, "Dansunidoru", idxID + 506, DQR.instance, 250, 1, false);
		EntityRegistry.registerModEntity(DqmEntityDarktororu.class, "Darktororu", idxID + 507, DQR.instance, 250, 1, false);
		EntityRegistry.registerModEntity(DqmEntityDesunyago.class, "Desunyago", idxID + 508, DQR.instance, 250, 1, false);
		EntityRegistry.registerModEntity(DqmEntityDoragonsoruja.class, "Doragonsoruja", idxID + 509, DQR.instance, 250, 1, false);
		EntityRegistry.registerModEntity(DqmEntityDoroningyou.class, "Doroningyou", idxID + 510, DQR.instance, 250, 1, false);
		EntityRegistry.registerModEntity(DqmEntityDoruido.class, "Doruido", idxID + 511, DQR.instance, 250, 1, false);
		EntityRegistry.registerModEntity(DqmEntityEbiruapple.class, "Ebiruapple", idxID + 512, DQR.instance, 250, 1, false);
		EntityRegistry.registerModEntity(DqmEntityFaratto.class, "Faratto", idxID + 513, DQR.instance, 250, 1, false);
		EntityRegistry.registerModEntity(DqmEntityFureimu.class, "Fureimu", idxID + 514, DQR.instance, 250, 1, false);
		EntityRegistry.registerModEntity(DqmEntityGaikotu.class, "Gaikotu", idxID + 515, DQR.instance, 250, 1, false);
		EntityRegistry.registerModEntity(DqmEntityGappurin.class, "Gappurin", idxID + 516, DQR.instance, 250, 1, false);
		EntityRegistry.registerModEntity(DqmEntityGenjutusi.class, "Genjutusi", idxID + 517, DQR.instance, 250, 1, false);
		EntityRegistry.registerModEntity(DqmEntityGoldmanto.class, "Goldmanto", idxID + 518, DQR.instance, 250, 1, false);
		EntityRegistry.registerModEntity(DqmEntityHatonaito.class, "Hatonaito", idxID + 519, DQR.instance, 250, 1, false);
		EntityRegistry.registerModEntity(DqmEntityJigokunoyoroi.class, "Jigokunoyoroi", idxID + 520, DQR.instance, 250, 1, false);
		EntityRegistry.registerModEntity(DqmEntityKandatakobun.class, "Kandatakobun", idxID + 521, DQR.instance, 250, 1, false);
		EntityRegistry.registerModEntity(DqmEntityKedamon.class, "Kedamon", idxID + 522, DQR.instance, 250, 1, false);
		EntityRegistry.registerModEntity(DqmEntityKimendousi.class, "Kimendousi", idxID + 523, DQR.instance, 250, 1, false);
		EntityRegistry.registerModEntity(DqmEntityKiraama.class, "Kiraama", idxID + 524, DQR.instance, 250, 1, false);
		EntityRegistry.registerModEntity(DqmEntityKiramasin2.class, "Kiramasin2", idxID + 525, DQR.instance, 250, 1, false);
		EntityRegistry.registerModEntity(DqmEntityManemane.class, "Manemane", idxID + 526, DQR.instance, 250, 1, false);
		EntityRegistry.registerModEntity(DqmEntityMasso.class, "Masso", idxID + 527, DQR.instance, 250, 1, false);
		EntityRegistry.registerModEntity(DqmEntityMetaruhoimin.class, "Metaruhoimin", idxID + 528, DQR.instance, 250, 1, false);
		EntityRegistry.registerModEntity(DqmEntityMokomokojuu.class, "Mokomokojuu", idxID + 529, DQR.instance, 250, 1, false);
		EntityRegistry.registerModEntity(DqmEntityMomoirosansimai.class, "Momoirosansimai", idxID + 530, DQR.instance, 250, 1, false);
		EntityRegistry.registerModEntity(DqmEntityNoroinoiwa.class, "Noroinoiwa", idxID + 531, DQR.instance, 250, 1, false);
		EntityRegistry.registerModEntity(DqmEntityPapettoman.class, "Papettoman", idxID + 532, DQR.instance, 250, 1, false);
		EntityRegistry.registerModEntity(DqmEntityPinkbonbon.class, "Pinkbonbon", idxID + 533, DQR.instance, 250, 1, false);
		EntityRegistry.registerModEntity(DqmEntityPisaronaito.class, "Pisaronaito", idxID + 534, DQR.instance, 250, 1, false);
		EntityRegistry.registerModEntity(DqmEntityPuremiasuraimu.class, "Puremiasuraimu", idxID + 535, DQR.instance, 250, 1, false);
		EntityRegistry.registerModEntity(DqmEntityRaimusuraimu.class, "Raimusuraimu", idxID + 536, DQR.instance, 250, 1, false);
		EntityRegistry.registerModEntity(DqmEntityRemonsuraimu.class, "Remonsuraimu", idxID + 537, DQR.instance, 250, 1, false);
		EntityRegistry.registerModEntity(DqmEntitySabotenboru.class, "Sabotenboru", idxID + 538, DQR.instance, 250, 1, false);
		EntityRegistry.registerModEntity(DqmEntitySabotengold.class, "Sabotengold", idxID + 539, DQR.instance, 250, 1, false);
		EntityRegistry.registerModEntity(DqmEntitySamayouyoroi.class, "Samayouyoroi", idxID + 540, DQR.instance, 250, 1, false);
		EntityRegistry.registerModEntity(DqmEntitySirudoaniki.class, "Sirudoaniki", idxID + 541, DQR.instance, 250, 1, false);
		EntityRegistry.registerModEntity(DqmEntitySiryou.class, "Siryou", idxID + 542, DQR.instance, 250, 1, false);
		EntityRegistry.registerModEntity(DqmEntityTattyan.class, "Tattyan", idxID + 543, DQR.instance, 250, 1, false);
		EntityRegistry.registerModEntity(DqmEntityTororu.class, "Tororu", idxID + 544, DQR.instance, 250, 1, false);
		EntityRegistry.registerModEntity(DqmEntityTororubakkosu.class, "Tororubakkosu", idxID + 545, DQR.instance, 250, 1, false);
		EntityRegistry.registerModEntity(DqmEntityTororubonba.class, "Tororubonba", idxID + 546, DQR.instance, 250, 1, false);
		EntityRegistry.registerModEntity(DqmEntityTororuking.class, "Tororuking", idxID + 547, DQR.instance, 250, 1, false);
		EntityRegistry.registerModEntity(DqmEntityTumurinmama.class, "Tumurinmama", idxID + 548, DQR.instance, 250, 1, false);
		EntityRegistry.registerModEntity(DqmEntityUragirikozou.class, "Uragirikozou", idxID + 549, DQR.instance, 250, 1, false);

		EntityRegistry.registerModEntity(DqmEntityMadrainbow.class, "Madrainbow", idxID + 550, DQR.instance, 250, 1, false);
		EntityRegistry.registerModEntity(DqmEntitySweetbag.class, "Sweetbag", idxID + 551, DQR.instance, 250, 1, false);
		EntityRegistry.registerModEntity(DqmEntityShuvaluts.class, "Shuvaluts", idxID + 552, DQR.instance, 250, 1, false);
		EntityRegistry.registerModEntity(DqmEntityBebingosatan.class, "Bebingosatan", idxID + 553, DQR.instance, 250, 1, false);
		EntityRegistry.registerModEntity(DqmEntityKinghidora.class, "Kinghidora", idxID + 554, DQR.instance, 250, 1, false);
		EntityRegistry.registerModEntity(DqmEntityKingbesu.class, "Kingbesu", idxID + 555, DQR.instance, 250, 1, false);
		EntityRegistry.registerModEntity(DqmEntityBurasu.class, "Burasu", idxID + 556, DQR.instance, 250, 1, false);
		EntityRegistry.registerModEntity(DqmEntityGoldenmetalslime.class, "Goldenmetalslime", idxID + 557, DQR.instance, 250, 1, false);
		EntityRegistry.registerModEntity(DqmEntityFureizado.class, "Fureizado", idxID + 558, DQR.instance, 250, 1, false);

		EntityRegistry.registerModEntity(DqmEntityGorotuki.class, "Gorotuki", idxID + 559, DQR.instance, 250, 1, false);
		EntityRegistry.registerModEntity(DqmEntityEriminator.class, "Eriminator", idxID + 560, DQR.instance, 250, 1, false);
		EntityRegistry.registerModEntity(DqmEntityDesusutoka.class, "Desusutoka", idxID + 561, DQR.instance, 250, 1, false);
		//EntityRegistry.registerModEntity(DqmEntityKandata.class, "Gorotuki", idxID + 559, DQR.instance, 250, 1, false);

		EntityRegistry.registerModEntity(DqmEntityGanseki.class, "GansekiOtoshi", idxID + 562, DQR.instance, 250, 1, false);
		EntityRegistry.registerModEntity(DqmEntityBlackchack.class, "Blackchack", idxID + 563, DQR.instance, 250, 1, false);
		EntityRegistry.registerModEntity(DqmEntitySuraimuemperor.class, "Suraimuemperor", idxID + 564, DQR.instance, 250, 1, false);
		EntityRegistry.registerModEntity(DqmEntityDarkdoriado.class, "Darkdoriado", idxID + 565, DQR.instance, 250, 1, false);

		EntityRegistry.registerModEntity(DqmEntityShadopan.class, "Shadopan", idxID + 566, DQR.instance, 250, 1, false);
		EntityRegistry.registerModEntity(DqmEntityShadopan2.class, "Shadopan2", idxID + 567, DQR.instance, 250, 1, false);
		EntityRegistry.registerModEntity(DqmEntityKandata.class, "Kandata", idxID + 568, DQR.instance, 250, 1, false);

		EntityRegistry.registerModEntity(DqmEntityOrutega.class, "Orutega", idxID + 569, DQR.instance, 250, 1, false);
		EntityRegistry.registerModEntity(DqmEntityWhitepan2.class, "Whitepan2", idxID + 570, DQR.instance, 250, 1, false);

	}
}
